-- 052: short_links — the shareable NAME of a view, and (optionally) a
-- read-only capability that opens it without a password.
--
-- PART ONE: THE NAME.
--
-- Every "Copy link" in this app produced 300-500 characters of state
-- (lat/lng/z, dates, layer set, pinned ids, the selected place, which panel,
-- which admin tab). That is a correct link and an unusable one: it cannot be
-- read aloud, footnoted in a report, or typed off a second screen, and in a
-- phone's clipboard preview it wraps to six lines. /s/{slug} is the same view
-- with a name, and the name is editable — you copy a link while looking at the
-- thing and name it a second later while sending it. `url` is always stored
-- with `pwd` STRIPPED, and a plain short link resolves behind the ordinary
-- password gate like every other page.
--
-- PART TWO: SHARING WITHOUT SHARING THE PASSWORD.
--
-- The real request behind "put the password in the link" is: let a donor, a
-- minister's office or a co-worker see this AOI without becoming us. Sending
-- them the access password does exactly the wrong thing — it is the same
-- secret for everyone, it grants writing as well as reading, it cannot be
-- taken back from one recipient, and once it has been forwarded twice nobody
-- can say who holds it.
--
-- A PIN on top of a password-carrying link does not fix any of that: six
-- digits is a million guesses, the link and the digits travel through the same
-- chat window, and the thing behind them is still the password.
--
-- So a share link may instead be a CAPABILITY (`guest = 1`), which is what the
-- principals/aoi_grants tables were built for ("a principal is a password
-- today, a user or an NGO tomorrow"):
--
--   * The slug IS the secret for these — 16 characters from a 27-symbol
--     alphabet, ~76 bits, generated by crypto/rand. They are therefore NOT
--     renameable and not guessable, and the pretty-name feature stays with
--     ordinary links, where a guessable name is harmless.
--   * READ ONLY, mechanically: the guest branch of PasswordMiddleware admits
--     GET/HEAD only and refuses /admin*, /api/admin*, uploads, AOI writes and
--     link minting. A capability that can mint capabilities is a password.
--   * Scoped to the creator's tenant (`env`) and acting as the creator's
--     principal (`principal_id`), so a private AOI shared this way is visible
--     and nothing else becomes so.
--   * Expiring (`expires_at`) and revocable one at a time (the admin sheet's
--     Clear), with `hits`/`last_hit_at` so "has anyone actually opened it"
--     is answerable. None of those five properties is available when the
--     thing you sent was the password.
--   * The guest never learns the password: it is not in this table, not in
--     the URL, and the session chip shows the link's name instead of it.
--
-- WHERE THIS IS HONEST ABOUT ITS LIMITS. A guest slug is a bearer token stored
-- in cleartext, because the admin sheet has to be able to show and re-copy it.
-- A database leak therefore leaks these links — but the same database holds
-- the AOI data they grant sight of, so the token adds no exposure. What it
-- must never do is grant more than that database already holds, which is why
-- write access is refused in the middleware rather than by convention.
--
-- `pwd_ref` is the non-secret sha256 handle of the password that CREATED the
-- link (principalRef, the handle the Access tab already prints). It is what
-- makes "shared links per password" a real grouping, and it never contains the
-- password itself.
--
-- A RENAME LEAVES AN ALIAS (`alias_of`) rather than freeing the name: by the
-- time you rename, the old link may already be in somebody's chat window.
CREATE TABLE IF NOT EXISTS short_links (
    slug        TEXT PRIMARY KEY,          -- [a-z0-9-]{1,64}; also the URL
    url         TEXT NOT NULL DEFAULT '',  -- absolute path + query, pwd removed
    alias_of    TEXT,                      -- set on the OLD slug after a rename
    kind        TEXT NOT NULL DEFAULT 'view',   -- view|download|report
    title       TEXT NOT NULL DEFAULT '',
    env         TEXT NOT NULL DEFAULT 'prod',
    pwd_ref     TEXT NOT NULL DEFAULT '',  -- principalRef of the creating password
    guest        INTEGER NOT NULL DEFAULT 0,  -- 1 = the slug is a read-only capability
    principal_id INTEGER,                    -- whose visibility a guest borrows
    expires_at   TEXT,                       -- guests expire; named links do not
    revoked_at   TEXT,
    created_at  TEXT NOT NULL,
    hits        INTEGER NOT NULL DEFAULT 0,
    last_hit_at TEXT
);

-- The dedupe path: the same view shared twice is one link, not two names for
-- one picture. Aliases have an empty url and must not collide here. A guest
-- link is never deduped into — it is a credential issued to one recipient,
-- not a name for a view.
CREATE INDEX IF NOT EXISTS idx_short_links_url ON short_links(url, env) WHERE url <> '';
CREATE INDEX IF NOT EXISTS idx_short_links_owner ON short_links(pwd_ref, created_at DESC);
