// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gpx_learning.sql

package dbgen

import (
	"context"
	"time"
)

const approveAirstrip = `-- name: ApproveAirstrip :exec
UPDATE learned_airstrips SET status = 'approved', approved_by = ?, approved_at = CURRENT_TIMESTAMP WHERE id = ?
`

type ApproveAirstripParams struct {
	ApprovedBy *string `json:"approved_by"`
	ID         int64   `json:"id"`
}

func (q *Queries) ApproveAirstrip(ctx context.Context, arg ApproveAirstripParams) error {
	_, err := q.db.ExecContext(ctx, approveAirstrip, arg.ApprovedBy, arg.ID)
	return err
}

const approvePlace = `-- name: ApprovePlace :exec
UPDATE learned_places SET status = 'approved', approved_by = ?, approved_at = CURRENT_TIMESTAMP WHERE id = ?
`

type ApprovePlaceParams struct {
	ApprovedBy *string `json:"approved_by"`
	ID         int64   `json:"id"`
}

func (q *Queries) ApprovePlace(ctx context.Context, arg ApprovePlaceParams) error {
	_, err := q.db.ExecContext(ctx, approvePlace, arg.ApprovedBy, arg.ID)
	return err
}

const approveRoad = `-- name: ApproveRoad :exec
UPDATE learned_roads SET status = 'approved', approved_by = ?, approved_at = CURRENT_TIMESTAMP WHERE id = ?
`

type ApproveRoadParams struct {
	ApprovedBy *string `json:"approved_by"`
	ID         int64   `json:"id"`
}

func (q *Queries) ApproveRoad(ctx context.Context, arg ApproveRoadParams) error {
	_, err := q.db.ExecContext(ctx, approveRoad, arg.ApprovedBy, arg.ID)
	return err
}

const completeLearningJob = `-- name: CompleteLearningJob :exec
UPDATE gpx_learning_queue SET status = 'completed', completed_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) CompleteLearningJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeLearningJob, id)
	return err
}

const createAircraftPattern = `-- name: CreateAircraftPattern :one
INSERT INTO aircraft_patterns (park_id, upload_id, pattern_type, aircraft_type, start_lat, start_lon, end_lat, end_lon, geojson, avg_speed_kmh)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateAircraftPatternParams struct {
	ParkID       string   `json:"park_id"`
	UploadID     *int64   `json:"upload_id"`
	PatternType  string   `json:"pattern_type"`
	AircraftType *string  `json:"aircraft_type"`
	StartLat     *float64 `json:"start_lat"`
	StartLon     *float64 `json:"start_lon"`
	EndLat       *float64 `json:"end_lat"`
	EndLon       *float64 `json:"end_lon"`
	Geojson      *string  `json:"geojson"`
	AvgSpeedKmh  *float64 `json:"avg_speed_kmh"`
}

func (q *Queries) CreateAircraftPattern(ctx context.Context, arg CreateAircraftPatternParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAircraftPattern,
		arg.ParkID,
		arg.UploadID,
		arg.PatternType,
		arg.AircraftType,
		arg.StartLat,
		arg.StartLon,
		arg.EndLat,
		arg.EndLon,
		arg.Geojson,
		arg.AvgSpeedKmh,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createLearnedAirstrip = `-- name: CreateLearnedAirstrip :one
INSERT INTO learned_airstrips (park_id, lat, lon, heading_deg, length_m, aircraft_type, landing_count, takeoff_count, confidence_pct, approach_json)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateLearnedAirstripParams struct {
	ParkID        string   `json:"park_id"`
	Lat           float64  `json:"lat"`
	Lon           float64  `json:"lon"`
	HeadingDeg    *float64 `json:"heading_deg"`
	LengthM       *float64 `json:"length_m"`
	AircraftType  *string  `json:"aircraft_type"`
	LandingCount  *int64   `json:"landing_count"`
	TakeoffCount  *int64   `json:"takeoff_count"`
	ConfidencePct *float64 `json:"confidence_pct"`
	ApproachJson  *string  `json:"approach_json"`
}

func (q *Queries) CreateLearnedAirstrip(ctx context.Context, arg CreateLearnedAirstripParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createLearnedAirstrip,
		arg.ParkID,
		arg.Lat,
		arg.Lon,
		arg.HeadingDeg,
		arg.LengthM,
		arg.AircraftType,
		arg.LandingCount,
		arg.TakeoffCount,
		arg.ConfidencePct,
		arg.ApproachJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createLearnedPlace = `-- name: CreateLearnedPlace :one
INSERT INTO learned_places (park_id, lat, lon, place_type, visit_count, avg_duration_minutes, confidence_pct)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateLearnedPlaceParams struct {
	ParkID             string   `json:"park_id"`
	Lat                float64  `json:"lat"`
	Lon                float64  `json:"lon"`
	PlaceType          *string  `json:"place_type"`
	VisitCount         *int64   `json:"visit_count"`
	AvgDurationMinutes *float64 `json:"avg_duration_minutes"`
	ConfidencePct      *float64 `json:"confidence_pct"`
}

func (q *Queries) CreateLearnedPlace(ctx context.Context, arg CreateLearnedPlaceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createLearnedPlace,
		arg.ParkID,
		arg.Lat,
		arg.Lon,
		arg.PlaceType,
		arg.VisitCount,
		arg.AvgDurationMinutes,
		arg.ConfidencePct,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createLearnedRoad = `-- name: CreateLearnedRoad :one
INSERT INTO learned_roads (park_id, geojson, length_m, match_count, confidence_pct)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type CreateLearnedRoadParams struct {
	ParkID        string   `json:"park_id"`
	Geojson       string   `json:"geojson"`
	LengthM       *float64 `json:"length_m"`
	MatchCount    *int64   `json:"match_count"`
	ConfidencePct *float64 `json:"confidence_pct"`
}

func (q *Queries) CreateLearnedRoad(ctx context.Context, arg CreateLearnedRoadParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createLearnedRoad,
		arg.ParkID,
		arg.Geojson,
		arg.LengthM,
		arg.MatchCount,
		arg.ConfidencePct,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createLearningResult = `-- name: CreateLearningResult :one
INSERT INTO gpx_learning_results (upload_id, park_id, park_name, vehicle_median_speed_kmh, vehicle_max_speed_kmh, foot_median_speed_kmh, foot_max_speed_kmh, foot_mcp_area_km2, new_roads_found, new_roads_km, road_confidence_pct, new_airstrips_found, airstrip_confidence_pct, new_places_found, place_types_json, place_confidence_pct, summary_text, discoveries_json)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateLearningResultParams struct {
	UploadID              *int64   `json:"upload_id"`
	ParkID                string   `json:"park_id"`
	ParkName              *string  `json:"park_name"`
	VehicleMedianSpeedKmh *float64 `json:"vehicle_median_speed_kmh"`
	VehicleMaxSpeedKmh    *float64 `json:"vehicle_max_speed_kmh"`
	FootMedianSpeedKmh    *float64 `json:"foot_median_speed_kmh"`
	FootMaxSpeedKmh       *float64 `json:"foot_max_speed_kmh"`
	FootMcpAreaKm2        *float64 `json:"foot_mcp_area_km2"`
	NewRoadsFound         *int64   `json:"new_roads_found"`
	NewRoadsKm            *float64 `json:"new_roads_km"`
	RoadConfidencePct     *float64 `json:"road_confidence_pct"`
	NewAirstripsFound     *int64   `json:"new_airstrips_found"`
	AirstripConfidencePct *float64 `json:"airstrip_confidence_pct"`
	NewPlacesFound        *int64   `json:"new_places_found"`
	PlaceTypesJson        *string  `json:"place_types_json"`
	PlaceConfidencePct    *float64 `json:"place_confidence_pct"`
	SummaryText           *string  `json:"summary_text"`
	DiscoveriesJson       *string  `json:"discoveries_json"`
}

func (q *Queries) CreateLearningResult(ctx context.Context, arg CreateLearningResultParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createLearningResult,
		arg.UploadID,
		arg.ParkID,
		arg.ParkName,
		arg.VehicleMedianSpeedKmh,
		arg.VehicleMaxSpeedKmh,
		arg.FootMedianSpeedKmh,
		arg.FootMaxSpeedKmh,
		arg.FootMcpAreaKm2,
		arg.NewRoadsFound,
		arg.NewRoadsKm,
		arg.RoadConfidencePct,
		arg.NewAirstripsFound,
		arg.AirstripConfidencePct,
		arg.NewPlacesFound,
		arg.PlaceTypesJson,
		arg.PlaceConfidencePct,
		arg.SummaryText,
		arg.DiscoveriesJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createVehicleTrack = `-- name: CreateVehicleTrack :one
INSERT INTO vehicle_tracks (park_id, upload_id, geojson, length_m, movement_type)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type CreateVehicleTrackParams struct {
	ParkID       string   `json:"park_id"`
	UploadID     *int64   `json:"upload_id"`
	Geojson      string   `json:"geojson"`
	LengthM      *float64 `json:"length_m"`
	MovementType *string  `json:"movement_type"`
}

func (q *Queries) CreateVehicleTrack(ctx context.Context, arg CreateVehicleTrackParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createVehicleTrack,
		arg.ParkID,
		arg.UploadID,
		arg.Geojson,
		arg.LengthM,
		arg.MovementType,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const failLearningJob = `-- name: FailLearningJob :exec
UPDATE gpx_learning_queue SET status = 'failed', completed_at = CURRENT_TIMESTAMP, error_message = ? WHERE id = ?
`

type FailLearningJobParams struct {
	ErrorMessage *string `json:"error_message"`
	ID           int64   `json:"id"`
}

func (q *Queries) FailLearningJob(ctx context.Context, arg FailLearningJobParams) error {
	_, err := q.db.ExecContext(ctx, failLearningJob, arg.ErrorMessage, arg.ID)
	return err
}

const findNearbyAirstrips = `-- name: FindNearbyAirstrips :many
SELECT id, park_id, lat, lon, heading_deg, length_m, aircraft_type, landing_count, takeoff_count, confidence_pct, status, approved_by, approved_at, approach_json, created_at, updated_at FROM learned_airstrips WHERE park_id = ? AND ABS(lat - ?) < 0.01 AND ABS(lon - ?) < 0.01
`

type FindNearbyAirstripsParams struct {
	ParkID string  `json:"park_id"`
	Lat    float64 `json:"lat"`
	Lon    float64 `json:"lon"`
}

func (q *Queries) FindNearbyAirstrips(ctx context.Context, arg FindNearbyAirstripsParams) ([]LearnedAirstrip, error) {
	rows, err := q.db.QueryContext(ctx, findNearbyAirstrips, arg.ParkID, arg.Lat, arg.Lon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearnedAirstrip{}
	for rows.Next() {
		var i LearnedAirstrip
		if err := rows.Scan(
			&i.ID,
			&i.ParkID,
			&i.Lat,
			&i.Lon,
			&i.HeadingDeg,
			&i.LengthM,
			&i.AircraftType,
			&i.LandingCount,
			&i.TakeoffCount,
			&i.ConfidencePct,
			&i.Status,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.ApproachJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNearbyPlaces = `-- name: FindNearbyPlaces :many
SELECT id, park_id, lat, lon, place_type, name, visit_count, avg_duration_minutes, confidence_pct, status, approved_by, approved_at, created_at, updated_at FROM learned_places WHERE park_id = ? AND ABS(lat - ?) < 0.005 AND ABS(lon - ?) < 0.005
`

type FindNearbyPlacesParams struct {
	ParkID string  `json:"park_id"`
	Lat    float64 `json:"lat"`
	Lon    float64 `json:"lon"`
}

func (q *Queries) FindNearbyPlaces(ctx context.Context, arg FindNearbyPlacesParams) ([]LearnedPlace, error) {
	rows, err := q.db.QueryContext(ctx, findNearbyPlaces, arg.ParkID, arg.Lat, arg.Lon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearnedPlace{}
	for rows.Next() {
		var i LearnedPlace
		if err := rows.Scan(
			&i.ID,
			&i.ParkID,
			&i.Lat,
			&i.Lon,
			&i.PlaceType,
			&i.Name,
			&i.VisitCount,
			&i.AvgDurationMinutes,
			&i.ConfidencePct,
			&i.Status,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNearbyVehicleTracks = `-- name: FindNearbyVehicleTracks :many
SELECT id, park_id, geojson, length_m FROM vehicle_tracks 
WHERE park_id = ? LIMIT 1000
`

type FindNearbyVehicleTracksRow struct {
	ID      int64    `json:"id"`
	ParkID  string   `json:"park_id"`
	Geojson string   `json:"geojson"`
	LengthM *float64 `json:"length_m"`
}

func (q *Queries) FindNearbyVehicleTracks(ctx context.Context, parkID string) ([]FindNearbyVehicleTracksRow, error) {
	rows, err := q.db.QueryContext(ctx, findNearbyVehicleTracks, parkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindNearbyVehicleTracksRow{}
	for rows.Next() {
		var i FindNearbyVehicleTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.ParkID,
			&i.Geojson,
			&i.LengthM,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAirstripHistory = `-- name: GetAirstripHistory :many
SELECT history_id, original_id, park_id, lat, lon, heading_deg, length_m, aircraft_type, landing_count, confidence, is_approved, is_rejected, version, "action", action_by, action_at FROM learned_airstrips_history WHERE original_id = ? ORDER BY history_id DESC
`

func (q *Queries) GetAirstripHistory(ctx context.Context, originalID int64) ([]LearnedAirstripsHistory, error) {
	rows, err := q.db.QueryContext(ctx, getAirstripHistory, originalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearnedAirstripsHistory{}
	for rows.Next() {
		var i LearnedAirstripsHistory
		if err := rows.Scan(
			&i.HistoryID,
			&i.OriginalID,
			&i.ParkID,
			&i.Lat,
			&i.Lon,
			&i.HeadingDeg,
			&i.LengthM,
			&i.AircraftType,
			&i.LandingCount,
			&i.Confidence,
			&i.IsApproved,
			&i.IsRejected,
			&i.Version,
			&i.Action,
			&i.ActionBy,
			&i.ActionAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllLearningResults = `-- name: GetAllLearningResults :many
SELECT id, upload_id, park_id, park_name, vehicle_median_speed_kmh, vehicle_max_speed_kmh, foot_median_speed_kmh, foot_max_speed_kmh, foot_mcp_area_km2, new_roads_found, new_roads_km, road_confidence_pct, new_airstrips_found, airstrip_confidence_pct, new_places_found, place_types_json, place_confidence_pct, summary_text, discoveries_json, created_at FROM gpx_learning_results ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type GetAllLearningResultsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) GetAllLearningResults(ctx context.Context, arg GetAllLearningResultsParams) ([]GpxLearningResult, error) {
	rows, err := q.db.QueryContext(ctx, getAllLearningResults, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GpxLearningResult{}
	for rows.Next() {
		var i GpxLearningResult
		if err := rows.Scan(
			&i.ID,
			&i.UploadID,
			&i.ParkID,
			&i.ParkName,
			&i.VehicleMedianSpeedKmh,
			&i.VehicleMaxSpeedKmh,
			&i.FootMedianSpeedKmh,
			&i.FootMaxSpeedKmh,
			&i.FootMcpAreaKm2,
			&i.NewRoadsFound,
			&i.NewRoadsKm,
			&i.RoadConfidencePct,
			&i.NewAirstripsFound,
			&i.AirstripConfidencePct,
			&i.NewPlacesFound,
			&i.PlaceTypesJson,
			&i.PlaceConfidencePct,
			&i.SummaryText,
			&i.DiscoveriesJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAutoApprovedFeatures = `-- name: GetAutoApprovedFeatures :many
SELECT id, feature_type, feature_id, park_id, geojson, bbox_minx, bbox_miny, bbox_maxx, bbox_maxy, start_date, end_date, properties_json, created_at, stat_value FROM feature_geometries 
WHERE park_id = ? 
  AND json_extract(properties_json, '$.approval_status') = 'auto_approved'
ORDER BY created_at DESC
`

func (q *Queries) GetAutoApprovedFeatures(ctx context.Context, parkID string) ([]FeatureGeometry, error) {
	rows, err := q.db.QueryContext(ctx, getAutoApprovedFeatures, parkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeatureGeometry{}
	for rows.Next() {
		var i FeatureGeometry
		if err := rows.Scan(
			&i.ID,
			&i.FeatureType,
			&i.FeatureID,
			&i.ParkID,
			&i.Geojson,
			&i.BboxMinx,
			&i.BboxMiny,
			&i.BboxMaxx,
			&i.BboxMaxy,
			&i.StartDate,
			&i.EndDate,
			&i.PropertiesJson,
			&i.CreatedAt,
			&i.StatValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLearnedAirstripsByPark = `-- name: GetLearnedAirstripsByPark :many
SELECT id, park_id, lat, lon, heading_deg, length_m, aircraft_type, landing_count, takeoff_count, confidence_pct, status, approved_by, approved_at, approach_json, created_at, updated_at FROM learned_airstrips WHERE park_id = ? AND status IN ('pending', 'approved', 'auto_approved') ORDER BY confidence_pct DESC
`

func (q *Queries) GetLearnedAirstripsByPark(ctx context.Context, parkID string) ([]LearnedAirstrip, error) {
	rows, err := q.db.QueryContext(ctx, getLearnedAirstripsByPark, parkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearnedAirstrip{}
	for rows.Next() {
		var i LearnedAirstrip
		if err := rows.Scan(
			&i.ID,
			&i.ParkID,
			&i.Lat,
			&i.Lon,
			&i.HeadingDeg,
			&i.LengthM,
			&i.AircraftType,
			&i.LandingCount,
			&i.TakeoffCount,
			&i.ConfidencePct,
			&i.Status,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.ApproachJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLearnedFeatureStats = `-- name: GetLearnedFeatureStats :one
SELECT 
    (SELECT COUNT(*) FROM learned_roads WHERE learned_roads.park_id = ?1 AND status = 'approved') as approved_roads,
    (SELECT COUNT(*) FROM learned_roads WHERE learned_roads.park_id = ?1 AND status = 'pending') as pending_roads,
    (SELECT COUNT(*) FROM learned_airstrips WHERE learned_airstrips.park_id = ?1 AND status = 'approved') as approved_airstrips,
    (SELECT COUNT(*) FROM learned_airstrips WHERE learned_airstrips.park_id = ?1 AND status = 'pending') as pending_airstrips,
    (SELECT COUNT(*) FROM learned_places WHERE learned_places.park_id = ?1 AND status = 'approved') as approved_places,
    (SELECT COUNT(*) FROM learned_places WHERE learned_places.park_id = ?1 AND status = 'pending') as pending_places,
    (SELECT COALESCE(SUM(length_m), 0) / 1000.0 FROM learned_roads WHERE learned_roads.park_id = ?1 AND status = 'approved') as total_road_km
`

type GetLearnedFeatureStatsRow struct {
	ApprovedRoads     int64 `json:"approved_roads"`
	PendingRoads      int64 `json:"pending_roads"`
	ApprovedAirstrips int64 `json:"approved_airstrips"`
	PendingAirstrips  int64 `json:"pending_airstrips"`
	ApprovedPlaces    int64 `json:"approved_places"`
	PendingPlaces     int64 `json:"pending_places"`
	TotalRoadKm       int64 `json:"total_road_km"`
}

func (q *Queries) GetLearnedFeatureStats(ctx context.Context, parkID string) (GetLearnedFeatureStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getLearnedFeatureStats, parkID)
	var i GetLearnedFeatureStatsRow
	err := row.Scan(
		&i.ApprovedRoads,
		&i.PendingRoads,
		&i.ApprovedAirstrips,
		&i.PendingAirstrips,
		&i.ApprovedPlaces,
		&i.PendingPlaces,
		&i.TotalRoadKm,
	)
	return i, err
}

const getLearnedPlacesByPark = `-- name: GetLearnedPlacesByPark :many
SELECT id, park_id, lat, lon, place_type, name, visit_count, avg_duration_minutes, confidence_pct, status, approved_by, approved_at, created_at, updated_at FROM learned_places WHERE park_id = ? AND status IN ('pending', 'approved', 'auto_approved') ORDER BY confidence_pct DESC
`

func (q *Queries) GetLearnedPlacesByPark(ctx context.Context, parkID string) ([]LearnedPlace, error) {
	rows, err := q.db.QueryContext(ctx, getLearnedPlacesByPark, parkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearnedPlace{}
	for rows.Next() {
		var i LearnedPlace
		if err := rows.Scan(
			&i.ID,
			&i.ParkID,
			&i.Lat,
			&i.Lon,
			&i.PlaceType,
			&i.Name,
			&i.VisitCount,
			&i.AvgDurationMinutes,
			&i.ConfidencePct,
			&i.Status,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLearnedRoadsByPark = `-- name: GetLearnedRoadsByPark :many
SELECT id, park_id, geojson, length_m, match_count, confidence_pct, status, approved_by, approved_at, created_at, updated_at FROM learned_roads WHERE park_id = ? AND status IN ('pending', 'approved', 'auto_approved') ORDER BY confidence_pct DESC
`

func (q *Queries) GetLearnedRoadsByPark(ctx context.Context, parkID string) ([]LearnedRoad, error) {
	rows, err := q.db.QueryContext(ctx, getLearnedRoadsByPark, parkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearnedRoad{}
	for rows.Next() {
		var i LearnedRoad
		if err := rows.Scan(
			&i.ID,
			&i.ParkID,
			&i.Geojson,
			&i.LengthM,
			&i.MatchCount,
			&i.ConfidencePct,
			&i.Status,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLearningResultsByPark = `-- name: GetLearningResultsByPark :many
SELECT id, upload_id, park_id, park_name, vehicle_median_speed_kmh, vehicle_max_speed_kmh, foot_median_speed_kmh, foot_max_speed_kmh, foot_mcp_area_km2, new_roads_found, new_roads_km, road_confidence_pct, new_airstrips_found, airstrip_confidence_pct, new_places_found, place_types_json, place_confidence_pct, summary_text, discoveries_json, created_at FROM gpx_learning_results WHERE park_id = ? ORDER BY created_at DESC LIMIT ?
`

type GetLearningResultsByParkParams struct {
	ParkID string `json:"park_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) GetLearningResultsByPark(ctx context.Context, arg GetLearningResultsByParkParams) ([]GpxLearningResult, error) {
	rows, err := q.db.QueryContext(ctx, getLearningResultsByPark, arg.ParkID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GpxLearningResult{}
	for rows.Next() {
		var i GpxLearningResult
		if err := rows.Scan(
			&i.ID,
			&i.UploadID,
			&i.ParkID,
			&i.ParkName,
			&i.VehicleMedianSpeedKmh,
			&i.VehicleMaxSpeedKmh,
			&i.FootMedianSpeedKmh,
			&i.FootMaxSpeedKmh,
			&i.FootMcpAreaKm2,
			&i.NewRoadsFound,
			&i.NewRoadsKm,
			&i.RoadConfidencePct,
			&i.NewAirstripsFound,
			&i.AirstripConfidencePct,
			&i.NewPlacesFound,
			&i.PlaceTypesJson,
			&i.PlaceConfidencePct,
			&i.SummaryText,
			&i.DiscoveriesJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLearningResultsWithUploadInfo = `-- name: GetLearningResultsWithUploadInfo :many
SELECT 
    lr.id, lr.upload_id, lr.park_id, lr.park_name, lr.vehicle_median_speed_kmh, lr.vehicle_max_speed_kmh, lr.foot_median_speed_kmh, lr.foot_max_speed_kmh, lr.foot_mcp_area_km2, lr.new_roads_found, lr.new_roads_km, lr.road_confidence_pct, lr.new_airstrips_found, lr.airstrip_confidence_pct, lr.new_places_found, lr.place_types_json, lr.place_confidence_pct, lr.summary_text, lr.discoveries_json, lr.created_at,
    ul.filename,
    ul.protected_area_name
FROM gpx_learning_results lr
LEFT JOIN gpx_upload_logs ul ON lr.upload_id = ul.upload_id
WHERE (? = '' OR lr.park_id = ?)
ORDER BY lr.processed_at DESC
LIMIT ? OFFSET ?
`

type GetLearningResultsWithUploadInfoParams struct {
	Column1 interface{} `json:"column_1"`
	ParkID  string      `json:"park_id"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
}

type GetLearningResultsWithUploadInfoRow struct {
	ID                    int64      `json:"id"`
	UploadID              *int64     `json:"upload_id"`
	ParkID                string     `json:"park_id"`
	ParkName              *string    `json:"park_name"`
	VehicleMedianSpeedKmh *float64   `json:"vehicle_median_speed_kmh"`
	VehicleMaxSpeedKmh    *float64   `json:"vehicle_max_speed_kmh"`
	FootMedianSpeedKmh    *float64   `json:"foot_median_speed_kmh"`
	FootMaxSpeedKmh       *float64   `json:"foot_max_speed_kmh"`
	FootMcpAreaKm2        *float64   `json:"foot_mcp_area_km2"`
	NewRoadsFound         *int64     `json:"new_roads_found"`
	NewRoadsKm            *float64   `json:"new_roads_km"`
	RoadConfidencePct     *float64   `json:"road_confidence_pct"`
	NewAirstripsFound     *int64     `json:"new_airstrips_found"`
	AirstripConfidencePct *float64   `json:"airstrip_confidence_pct"`
	NewPlacesFound        *int64     `json:"new_places_found"`
	PlaceTypesJson        *string    `json:"place_types_json"`
	PlaceConfidencePct    *float64   `json:"place_confidence_pct"`
	SummaryText           *string    `json:"summary_text"`
	DiscoveriesJson       *string    `json:"discoveries_json"`
	CreatedAt             *time.Time `json:"created_at"`
	Filename              *string    `json:"filename"`
	ProtectedAreaName     *string    `json:"protected_area_name"`
}

func (q *Queries) GetLearningResultsWithUploadInfo(ctx context.Context, arg GetLearningResultsWithUploadInfoParams) ([]GetLearningResultsWithUploadInfoRow, error) {
	rows, err := q.db.QueryContext(ctx, getLearningResultsWithUploadInfo,
		arg.Column1,
		arg.ParkID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLearningResultsWithUploadInfoRow{}
	for rows.Next() {
		var i GetLearningResultsWithUploadInfoRow
		if err := rows.Scan(
			&i.ID,
			&i.UploadID,
			&i.ParkID,
			&i.ParkName,
			&i.VehicleMedianSpeedKmh,
			&i.VehicleMaxSpeedKmh,
			&i.FootMedianSpeedKmh,
			&i.FootMaxSpeedKmh,
			&i.FootMcpAreaKm2,
			&i.NewRoadsFound,
			&i.NewRoadsKm,
			&i.RoadConfidencePct,
			&i.NewAirstripsFound,
			&i.AirstripConfidencePct,
			&i.NewPlacesFound,
			&i.PlaceTypesJson,
			&i.PlaceConfidencePct,
			&i.SummaryText,
			&i.DiscoveriesJson,
			&i.CreatedAt,
			&i.Filename,
			&i.ProtectedAreaName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPatrolMCP = `-- name: GetPatrolMCP :one
SELECT mcp_90_geojson, mcp_area_km2, point_count, updated_at
FROM park_patrol_mcp WHERE park_id = ?
`

type GetPatrolMCPRow struct {
	Mcp90Geojson *string    `json:"mcp_90_geojson"`
	McpAreaKm2   *float64   `json:"mcp_area_km2"`
	PointCount   *int64     `json:"point_count"`
	UpdatedAt    *time.Time `json:"updated_at"`
}

func (q *Queries) GetPatrolMCP(ctx context.Context, parkID string) (GetPatrolMCPRow, error) {
	row := q.db.QueryRowContext(ctx, getPatrolMCP, parkID)
	var i GetPatrolMCPRow
	err := row.Scan(
		&i.Mcp90Geojson,
		&i.McpAreaKm2,
		&i.PointCount,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingApprovals = `-- name: GetPendingApprovals :many
SELECT 'road' as type, id, park_id, confidence_pct, created_at FROM learned_roads WHERE status = 'pending'
UNION ALL
SELECT 'airstrip' as type, id, park_id, confidence_pct, created_at FROM learned_airstrips WHERE status = 'pending'
UNION ALL
SELECT 'place' as type, id, park_id, confidence_pct, created_at FROM learned_places WHERE status = 'pending'
ORDER BY created_at DESC LIMIT ?
`

type GetPendingApprovalsRow struct {
	Type          string     `json:"type"`
	ID            int64      `json:"id"`
	ParkID        string     `json:"park_id"`
	ConfidencePct *float64   `json:"confidence_pct"`
	CreatedAt     *time.Time `json:"created_at"`
}

func (q *Queries) GetPendingApprovals(ctx context.Context, limit int64) ([]GetPendingApprovalsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingApprovals, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingApprovalsRow{}
	for rows.Next() {
		var i GetPendingApprovalsRow
		if err := rows.Scan(
			&i.Type,
			&i.ID,
			&i.ParkID,
			&i.ConfidencePct,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingLearningJobs = `-- name: GetPendingLearningJobs :many
SELECT id, upload_id, park_id, status, error_message, created_at, started_at, completed_at FROM gpx_learning_queue WHERE status = 'pending' ORDER BY created_at LIMIT ?
`

func (q *Queries) GetPendingLearningJobs(ctx context.Context, limit int64) ([]GpxLearningQueue, error) {
	rows, err := q.db.QueryContext(ctx, getPendingLearningJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GpxLearningQueue{}
	for rows.Next() {
		var i GpxLearningQueue
		if err := rows.Scan(
			&i.ID,
			&i.UploadID,
			&i.ParkID,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaceHistory = `-- name: GetPlaceHistory :many
SELECT history_id, original_id, park_id, lat, lon, place_type, visit_count, avg_duration_minutes, confidence, is_approved, is_rejected, version, "action", action_by, action_at FROM learned_places_history WHERE original_id = ? ORDER BY history_id DESC
`

func (q *Queries) GetPlaceHistory(ctx context.Context, originalID int64) ([]LearnedPlacesHistory, error) {
	rows, err := q.db.QueryContext(ctx, getPlaceHistory, originalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearnedPlacesHistory{}
	for rows.Next() {
		var i LearnedPlacesHistory
		if err := rows.Scan(
			&i.HistoryID,
			&i.OriginalID,
			&i.ParkID,
			&i.Lat,
			&i.Lon,
			&i.PlaceType,
			&i.VisitCount,
			&i.AvgDurationMinutes,
			&i.Confidence,
			&i.IsApproved,
			&i.IsRejected,
			&i.Version,
			&i.Action,
			&i.ActionBy,
			&i.ActionAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoadHistory = `-- name: GetRoadHistory :many
SELECT history_id, original_id, park_id, geojson, distance_km, match_count, confidence, is_approved, is_rejected, version, "action", action_by, action_at FROM learned_roads_history WHERE original_id = ? ORDER BY history_id DESC
`

func (q *Queries) GetRoadHistory(ctx context.Context, originalID int64) ([]LearnedRoadsHistory, error) {
	rows, err := q.db.QueryContext(ctx, getRoadHistory, originalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearnedRoadsHistory{}
	for rows.Next() {
		var i LearnedRoadsHistory
		if err := rows.Scan(
			&i.HistoryID,
			&i.OriginalID,
			&i.ParkID,
			&i.Geojson,
			&i.DistanceKm,
			&i.MatchCount,
			&i.Confidence,
			&i.IsApproved,
			&i.IsRejected,
			&i.Version,
			&i.Action,
			&i.ActionBy,
			&i.ActionAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVehicleStatsByPark = `-- name: GetVehicleStatsByPark :many
SELECT id, park_id, movement_type, total_distance_km, total_time_hours, median_speed_kmh, max_speed_kmh, p90_speed_kmh, sample_count, updated_at FROM park_vehicle_stats WHERE park_id = ?
`

func (q *Queries) GetVehicleStatsByPark(ctx context.Context, parkID string) ([]ParkVehicleStat, error) {
	rows, err := q.db.QueryContext(ctx, getVehicleStatsByPark, parkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParkVehicleStat{}
	for rows.Next() {
		var i ParkVehicleStat
		if err := rows.Scan(
			&i.ID,
			&i.ParkID,
			&i.MovementType,
			&i.TotalDistanceKm,
			&i.TotalTimeHours,
			&i.MedianSpeedKmh,
			&i.MaxSpeedKmh,
			&i.P90SpeedKmh,
			&i.SampleCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAutoApprovedFeature = `-- name: InsertAutoApprovedFeature :exec
INSERT INTO feature_geometries (feature_type, feature_id, park_id, geojson, bbox_minx, bbox_miny, bbox_maxx, bbox_maxy, properties_json)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(feature_type, feature_id) DO UPDATE SET
    geojson = excluded.geojson,
    bbox_minx = excluded.bbox_minx,
    bbox_miny = excluded.bbox_miny,
    bbox_maxx = excluded.bbox_maxx,
    bbox_maxy = excluded.bbox_maxy,
    properties_json = excluded.properties_json
`

type InsertAutoApprovedFeatureParams struct {
	FeatureType    string   `json:"feature_type"`
	FeatureID      string   `json:"feature_id"`
	ParkID         string   `json:"park_id"`
	Geojson        string   `json:"geojson"`
	BboxMinx       *float64 `json:"bbox_minx"`
	BboxMiny       *float64 `json:"bbox_miny"`
	BboxMaxx       *float64 `json:"bbox_maxx"`
	BboxMaxy       *float64 `json:"bbox_maxy"`
	PropertiesJson *string  `json:"properties_json"`
}

func (q *Queries) InsertAutoApprovedFeature(ctx context.Context, arg InsertAutoApprovedFeatureParams) error {
	_, err := q.db.ExecContext(ctx, insertAutoApprovedFeature,
		arg.FeatureType,
		arg.FeatureID,
		arg.ParkID,
		arg.Geojson,
		arg.BboxMinx,
		arg.BboxMiny,
		arg.BboxMaxx,
		arg.BboxMaxy,
		arg.PropertiesJson,
	)
	return err
}

const queueGPXLearning = `-- name: QueueGPXLearning :one
INSERT INTO gpx_learning_queue (upload_id, park_id, status)
VALUES (?, ?, 'pending')
RETURNING id, upload_id, park_id, status, error_message, created_at, started_at, completed_at
`

type QueueGPXLearningParams struct {
	UploadID *int64  `json:"upload_id"`
	ParkID   *string `json:"park_id"`
}

func (q *Queries) QueueGPXLearning(ctx context.Context, arg QueueGPXLearningParams) (GpxLearningQueue, error) {
	row := q.db.QueryRowContext(ctx, queueGPXLearning, arg.UploadID, arg.ParkID)
	var i GpxLearningQueue
	err := row.Scan(
		&i.ID,
		&i.UploadID,
		&i.ParkID,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const recordAirstripHistory = `-- name: RecordAirstripHistory :exec
INSERT INTO learned_airstrips_history (original_id, park_id, lat, lon, heading_deg, length_m, aircraft_type, landing_count, confidence, is_approved, is_rejected, version, action, action_by)
SELECT la.id, la.park_id, la.lat, la.lon, la.heading_deg, la.length_m, la.aircraft_type, la.landing_count, la.confidence_pct,
       CASE WHEN la.status = 'approved' THEN 1 ELSE 0 END,
       CASE WHEN la.status = 'rejected' THEN 1 ELSE 0 END,
       COALESCE((SELECT MAX(version) FROM learned_airstrips_history WHERE original_id = la.id), 0) + 1,
       ?, ?
FROM learned_airstrips la WHERE la.id = ?
`

type RecordAirstripHistoryParams struct {
	Action   string  `json:"action"`
	ActionBy *string `json:"action_by"`
	ID       int64   `json:"id"`
}

func (q *Queries) RecordAirstripHistory(ctx context.Context, arg RecordAirstripHistoryParams) error {
	_, err := q.db.ExecContext(ctx, recordAirstripHistory, arg.Action, arg.ActionBy, arg.ID)
	return err
}

const recordPlaceHistory = `-- name: RecordPlaceHistory :exec
INSERT INTO learned_places_history (original_id, park_id, lat, lon, place_type, visit_count, avg_duration_minutes, confidence, is_approved, is_rejected, version, action, action_by)
SELECT lp.id, lp.park_id, lp.lat, lp.lon, lp.place_type, lp.visit_count, lp.avg_duration_minutes, lp.confidence_pct,
       CASE WHEN lp.status = 'approved' THEN 1 ELSE 0 END,
       CASE WHEN lp.status = 'rejected' THEN 1 ELSE 0 END,
       COALESCE((SELECT MAX(version) FROM learned_places_history WHERE original_id = lp.id), 0) + 1,
       ?, ?
FROM learned_places lp WHERE lp.id = ?
`

type RecordPlaceHistoryParams struct {
	Action   string  `json:"action"`
	ActionBy *string `json:"action_by"`
	ID       int64   `json:"id"`
}

func (q *Queries) RecordPlaceHistory(ctx context.Context, arg RecordPlaceHistoryParams) error {
	_, err := q.db.ExecContext(ctx, recordPlaceHistory, arg.Action, arg.ActionBy, arg.ID)
	return err
}

const recordRoadHistory = `-- name: RecordRoadHistory :exec
INSERT INTO learned_roads_history (original_id, park_id, geojson, distance_km, match_count, confidence, is_approved, is_rejected, version, action, action_by)
SELECT lr.id, lr.park_id, lr.geojson, lr.length_m, lr.match_count, lr.confidence_pct, 
       CASE WHEN lr.status = 'approved' THEN 1 ELSE 0 END, 
       CASE WHEN lr.status = 'rejected' THEN 1 ELSE 0 END, 
       COALESCE((SELECT MAX(version) FROM learned_roads_history WHERE original_id = lr.id), 0) + 1,
       ?, ?
FROM learned_roads lr WHERE lr.id = ?
`

type RecordRoadHistoryParams struct {
	Action   string  `json:"action"`
	ActionBy *string `json:"action_by"`
	ID       int64   `json:"id"`
}

func (q *Queries) RecordRoadHistory(ctx context.Context, arg RecordRoadHistoryParams) error {
	_, err := q.db.ExecContext(ctx, recordRoadHistory, arg.Action, arg.ActionBy, arg.ID)
	return err
}

const rejectAirstrip = `-- name: RejectAirstrip :exec
UPDATE learned_airstrips SET status = 'rejected', approved_by = ?, approved_at = CURRENT_TIMESTAMP WHERE id = ?
`

type RejectAirstripParams struct {
	ApprovedBy *string `json:"approved_by"`
	ID         int64   `json:"id"`
}

func (q *Queries) RejectAirstrip(ctx context.Context, arg RejectAirstripParams) error {
	_, err := q.db.ExecContext(ctx, rejectAirstrip, arg.ApprovedBy, arg.ID)
	return err
}

const rejectPlace = `-- name: RejectPlace :exec
UPDATE learned_places SET status = 'rejected', approved_by = ?, approved_at = CURRENT_TIMESTAMP WHERE id = ?
`

type RejectPlaceParams struct {
	ApprovedBy *string `json:"approved_by"`
	ID         int64   `json:"id"`
}

func (q *Queries) RejectPlace(ctx context.Context, arg RejectPlaceParams) error {
	_, err := q.db.ExecContext(ctx, rejectPlace, arg.ApprovedBy, arg.ID)
	return err
}

const rejectRoad = `-- name: RejectRoad :exec
UPDATE learned_roads SET status = 'rejected', approved_by = ?, approved_at = CURRENT_TIMESTAMP WHERE id = ?
`

type RejectRoadParams struct {
	ApprovedBy *string `json:"approved_by"`
	ID         int64   `json:"id"`
}

func (q *Queries) RejectRoad(ctx context.Context, arg RejectRoadParams) error {
	_, err := q.db.ExecContext(ctx, rejectRoad, arg.ApprovedBy, arg.ID)
	return err
}

const rollbackAirstrip = `-- name: RollbackAirstrip :exec
UPDATE learned_airstrips SET
    heading_deg = ?,
    length_m = ?,
    confidence_pct = ?,
    status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type RollbackAirstripParams struct {
	HeadingDeg    *float64 `json:"heading_deg"`
	LengthM       *float64 `json:"length_m"`
	ConfidencePct *float64 `json:"confidence_pct"`
	Status        *string  `json:"status"`
	ID            int64    `json:"id"`
}

func (q *Queries) RollbackAirstrip(ctx context.Context, arg RollbackAirstripParams) error {
	_, err := q.db.ExecContext(ctx, rollbackAirstrip,
		arg.HeadingDeg,
		arg.LengthM,
		arg.ConfidencePct,
		arg.Status,
		arg.ID,
	)
	return err
}

const rollbackPlace = `-- name: RollbackPlace :exec
UPDATE learned_places SET
    place_type = ?,
    confidence_pct = ?,
    status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type RollbackPlaceParams struct {
	PlaceType     *string  `json:"place_type"`
	ConfidencePct *float64 `json:"confidence_pct"`
	Status        *string  `json:"status"`
	ID            int64    `json:"id"`
}

func (q *Queries) RollbackPlace(ctx context.Context, arg RollbackPlaceParams) error {
	_, err := q.db.ExecContext(ctx, rollbackPlace,
		arg.PlaceType,
		arg.ConfidencePct,
		arg.Status,
		arg.ID,
	)
	return err
}

const rollbackRoad = `-- name: RollbackRoad :exec
UPDATE learned_roads SET
    geojson = ?,
    length_m = ?,
    confidence_pct = ?,
    status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type RollbackRoadParams struct {
	Geojson       string   `json:"geojson"`
	LengthM       *float64 `json:"length_m"`
	ConfidencePct *float64 `json:"confidence_pct"`
	Status        *string  `json:"status"`
	ID            int64    `json:"id"`
}

func (q *Queries) RollbackRoad(ctx context.Context, arg RollbackRoadParams) error {
	_, err := q.db.ExecContext(ctx, rollbackRoad,
		arg.Geojson,
		arg.LengthM,
		arg.ConfidencePct,
		arg.Status,
		arg.ID,
	)
	return err
}

const startLearningJob = `-- name: StartLearningJob :exec
UPDATE gpx_learning_queue SET status = 'processing', started_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) StartLearningJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, startLearningJob, id)
	return err
}

const updateAirstripStats = `-- name: UpdateAirstripStats :exec
UPDATE learned_airstrips SET landing_count = landing_count + ?, takeoff_count = takeoff_count + ?, confidence_pct = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateAirstripStatsParams struct {
	LandingCount  *int64   `json:"landing_count"`
	TakeoffCount  *int64   `json:"takeoff_count"`
	ConfidencePct *float64 `json:"confidence_pct"`
	ID            int64    `json:"id"`
}

func (q *Queries) UpdateAirstripStats(ctx context.Context, arg UpdateAirstripStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateAirstripStats,
		arg.LandingCount,
		arg.TakeoffCount,
		arg.ConfidencePct,
		arg.ID,
	)
	return err
}

const updateLearnedRoadMatch = `-- name: UpdateLearnedRoadMatch :exec
UPDATE learned_roads SET match_count = match_count + 1, confidence_pct = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateLearnedRoadMatchParams struct {
	ConfidencePct *float64 `json:"confidence_pct"`
	ID            int64    `json:"id"`
}

func (q *Queries) UpdateLearnedRoadMatch(ctx context.Context, arg UpdateLearnedRoadMatchParams) error {
	_, err := q.db.ExecContext(ctx, updateLearnedRoadMatch, arg.ConfidencePct, arg.ID)
	return err
}

const updateLearningJobStatus = `-- name: UpdateLearningJobStatus :exec
UPDATE gpx_learning_queue SET status = ?1, error_message = ?2 WHERE id = ?3
`

type UpdateLearningJobStatusParams struct {
	Status       *string `json:"status"`
	ErrorMessage *string `json:"error_message"`
	ID           int64   `json:"id"`
}

func (q *Queries) UpdateLearningJobStatus(ctx context.Context, arg UpdateLearningJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateLearningJobStatus, arg.Status, arg.ErrorMessage, arg.ID)
	return err
}

const updatePlaceStats = `-- name: UpdatePlaceStats :exec
UPDATE learned_places SET visit_count = visit_count + 1, avg_duration_minutes = ?, confidence_pct = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdatePlaceStatsParams struct {
	AvgDurationMinutes *float64 `json:"avg_duration_minutes"`
	ConfidencePct      *float64 `json:"confidence_pct"`
	ID                 int64    `json:"id"`
}

func (q *Queries) UpdatePlaceStats(ctx context.Context, arg UpdatePlaceStatsParams) error {
	_, err := q.db.ExecContext(ctx, updatePlaceStats, arg.AvgDurationMinutes, arg.ConfidencePct, arg.ID)
	return err
}

const upsertPatrolMCP = `-- name: UpsertPatrolMCP :exec
INSERT INTO park_patrol_mcp (park_id, mcp_90_geojson, mcp_area_km2, point_count, updated_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(park_id) DO UPDATE SET 
    mcp_90_geojson = excluded.mcp_90_geojson,
    mcp_area_km2 = excluded.mcp_area_km2,
    point_count = excluded.point_count,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertPatrolMCPParams struct {
	ParkID       string   `json:"park_id"`
	Mcp90Geojson *string  `json:"mcp_90_geojson"`
	McpAreaKm2   *float64 `json:"mcp_area_km2"`
	PointCount   *int64   `json:"point_count"`
}

func (q *Queries) UpsertPatrolMCP(ctx context.Context, arg UpsertPatrolMCPParams) error {
	_, err := q.db.ExecContext(ctx, upsertPatrolMCP,
		arg.ParkID,
		arg.Mcp90Geojson,
		arg.McpAreaKm2,
		arg.PointCount,
	)
	return err
}

const upsertVehicleStats = `-- name: UpsertVehicleStats :exec
INSERT INTO park_vehicle_stats (park_id, movement_type, total_distance_km, total_time_hours, median_speed_kmh, max_speed_kmh, p90_speed_kmh, sample_count)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(park_id, movement_type) DO UPDATE SET
    total_distance_km = total_distance_km + excluded.total_distance_km,
    total_time_hours = total_time_hours + excluded.total_time_hours,
    median_speed_kmh = excluded.median_speed_kmh,
    max_speed_kmh = CASE WHEN excluded.max_speed_kmh > max_speed_kmh THEN excluded.max_speed_kmh ELSE max_speed_kmh END,
    p90_speed_kmh = excluded.p90_speed_kmh,
    sample_count = sample_count + excluded.sample_count,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertVehicleStatsParams struct {
	ParkID          string   `json:"park_id"`
	MovementType    string   `json:"movement_type"`
	TotalDistanceKm *float64 `json:"total_distance_km"`
	TotalTimeHours  *float64 `json:"total_time_hours"`
	MedianSpeedKmh  *float64 `json:"median_speed_kmh"`
	MaxSpeedKmh     *float64 `json:"max_speed_kmh"`
	P90SpeedKmh     *float64 `json:"p90_speed_kmh"`
	SampleCount     *int64   `json:"sample_count"`
}

func (q *Queries) UpsertVehicleStats(ctx context.Context, arg UpsertVehicleStatsParams) error {
	_, err := q.db.ExecContext(ctx, upsertVehicleStats,
		arg.ParkID,
		arg.MovementType,
		arg.TotalDistanceKm,
		arg.TotalTimeHours,
		arg.MedianSpeedKmh,
		arg.MaxSpeedKmh,
		arg.P90SpeedKmh,
		arg.SampleCount,
	)
	return err
}
