// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gpx_learning.sql

package dbgen

import (
	"context"
	"time"
)

const approveLearnedAirstrip = `-- name: ApproveLearnedAirstrip :exec
UPDATE learned_airstrips SET status = 'approved', approved_by = ?, approved_at = CURRENT_TIMESTAMP WHERE id = ?
`

type ApproveLearnedAirstripParams struct {
	ApprovedBy *string `json:"approved_by"`
	ID         int64   `json:"id"`
}

func (q *Queries) ApproveLearnedAirstrip(ctx context.Context, arg ApproveLearnedAirstripParams) error {
	_, err := q.db.ExecContext(ctx, approveLearnedAirstrip, arg.ApprovedBy, arg.ID)
	return err
}

const approveLearnedPlace = `-- name: ApproveLearnedPlace :exec
UPDATE learned_places SET status = 'approved', approved_by = ?, approved_at = CURRENT_TIMESTAMP WHERE id = ?
`

type ApproveLearnedPlaceParams struct {
	ApprovedBy *string `json:"approved_by"`
	ID         int64   `json:"id"`
}

func (q *Queries) ApproveLearnedPlace(ctx context.Context, arg ApproveLearnedPlaceParams) error {
	_, err := q.db.ExecContext(ctx, approveLearnedPlace, arg.ApprovedBy, arg.ID)
	return err
}

const approveLearnedRoad = `-- name: ApproveLearnedRoad :exec
UPDATE learned_roads SET status = 'approved', approved_by = ?, approved_at = CURRENT_TIMESTAMP WHERE id = ?
`

type ApproveLearnedRoadParams struct {
	ApprovedBy *string `json:"approved_by"`
	ID         int64   `json:"id"`
}

func (q *Queries) ApproveLearnedRoad(ctx context.Context, arg ApproveLearnedRoadParams) error {
	_, err := q.db.ExecContext(ctx, approveLearnedRoad, arg.ApprovedBy, arg.ID)
	return err
}

const completeLearningJob = `-- name: CompleteLearningJob :exec
UPDATE gpx_learning_queue SET status = 'completed', completed_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) CompleteLearningJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeLearningJob, id)
	return err
}

const createAircraftPattern = `-- name: CreateAircraftPattern :one
INSERT INTO aircraft_patterns (park_id, upload_id, pattern_type, aircraft_type, start_lat, start_lon, end_lat, end_lon, geojson, avg_speed_kmh)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateAircraftPatternParams struct {
	ParkID       string   `json:"park_id"`
	UploadID     *int64   `json:"upload_id"`
	PatternType  string   `json:"pattern_type"`
	AircraftType *string  `json:"aircraft_type"`
	StartLat     *float64 `json:"start_lat"`
	StartLon     *float64 `json:"start_lon"`
	EndLat       *float64 `json:"end_lat"`
	EndLon       *float64 `json:"end_lon"`
	Geojson      *string  `json:"geojson"`
	AvgSpeedKmh  *float64 `json:"avg_speed_kmh"`
}

func (q *Queries) CreateAircraftPattern(ctx context.Context, arg CreateAircraftPatternParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAircraftPattern,
		arg.ParkID,
		arg.UploadID,
		arg.PatternType,
		arg.AircraftType,
		arg.StartLat,
		arg.StartLon,
		arg.EndLat,
		arg.EndLon,
		arg.Geojson,
		arg.AvgSpeedKmh,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createLearnedAirstrip = `-- name: CreateLearnedAirstrip :one
INSERT INTO learned_airstrips (park_id, lat, lon, heading_deg, length_m, aircraft_type, landing_count, takeoff_count, confidence_pct, approach_json)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateLearnedAirstripParams struct {
	ParkID        string   `json:"park_id"`
	Lat           float64  `json:"lat"`
	Lon           float64  `json:"lon"`
	HeadingDeg    *float64 `json:"heading_deg"`
	LengthM       *float64 `json:"length_m"`
	AircraftType  *string  `json:"aircraft_type"`
	LandingCount  *int64   `json:"landing_count"`
	TakeoffCount  *int64   `json:"takeoff_count"`
	ConfidencePct *float64 `json:"confidence_pct"`
	ApproachJson  *string  `json:"approach_json"`
}

func (q *Queries) CreateLearnedAirstrip(ctx context.Context, arg CreateLearnedAirstripParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createLearnedAirstrip,
		arg.ParkID,
		arg.Lat,
		arg.Lon,
		arg.HeadingDeg,
		arg.LengthM,
		arg.AircraftType,
		arg.LandingCount,
		arg.TakeoffCount,
		arg.ConfidencePct,
		arg.ApproachJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createLearnedPlace = `-- name: CreateLearnedPlace :one
INSERT INTO learned_places (park_id, lat, lon, place_type, visit_count, avg_duration_minutes, confidence_pct)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateLearnedPlaceParams struct {
	ParkID             string   `json:"park_id"`
	Lat                float64  `json:"lat"`
	Lon                float64  `json:"lon"`
	PlaceType          *string  `json:"place_type"`
	VisitCount         *int64   `json:"visit_count"`
	AvgDurationMinutes *float64 `json:"avg_duration_minutes"`
	ConfidencePct      *float64 `json:"confidence_pct"`
}

func (q *Queries) CreateLearnedPlace(ctx context.Context, arg CreateLearnedPlaceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createLearnedPlace,
		arg.ParkID,
		arg.Lat,
		arg.Lon,
		arg.PlaceType,
		arg.VisitCount,
		arg.AvgDurationMinutes,
		arg.ConfidencePct,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createLearnedRoad = `-- name: CreateLearnedRoad :one
INSERT INTO learned_roads (park_id, geojson, length_m, match_count, confidence_pct)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type CreateLearnedRoadParams struct {
	ParkID        string   `json:"park_id"`
	Geojson       string   `json:"geojson"`
	LengthM       *float64 `json:"length_m"`
	MatchCount    *int64   `json:"match_count"`
	ConfidencePct *float64 `json:"confidence_pct"`
}

func (q *Queries) CreateLearnedRoad(ctx context.Context, arg CreateLearnedRoadParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createLearnedRoad,
		arg.ParkID,
		arg.Geojson,
		arg.LengthM,
		arg.MatchCount,
		arg.ConfidencePct,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createLearningResult = `-- name: CreateLearningResult :one
INSERT INTO gpx_learning_results (upload_id, park_id, park_name, vehicle_median_speed_kmh, vehicle_max_speed_kmh, foot_median_speed_kmh, foot_max_speed_kmh, foot_mcp_area_km2, new_roads_found, new_roads_km, road_confidence_pct, new_airstrips_found, airstrip_confidence_pct, new_places_found, place_types_json, place_confidence_pct, summary_text, discoveries_json)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateLearningResultParams struct {
	UploadID              *int64   `json:"upload_id"`
	ParkID                string   `json:"park_id"`
	ParkName              *string  `json:"park_name"`
	VehicleMedianSpeedKmh *float64 `json:"vehicle_median_speed_kmh"`
	VehicleMaxSpeedKmh    *float64 `json:"vehicle_max_speed_kmh"`
	FootMedianSpeedKmh    *float64 `json:"foot_median_speed_kmh"`
	FootMaxSpeedKmh       *float64 `json:"foot_max_speed_kmh"`
	FootMcpAreaKm2        *float64 `json:"foot_mcp_area_km2"`
	NewRoadsFound         *int64   `json:"new_roads_found"`
	NewRoadsKm            *float64 `json:"new_roads_km"`
	RoadConfidencePct     *float64 `json:"road_confidence_pct"`
	NewAirstripsFound     *int64   `json:"new_airstrips_found"`
	AirstripConfidencePct *float64 `json:"airstrip_confidence_pct"`
	NewPlacesFound        *int64   `json:"new_places_found"`
	PlaceTypesJson        *string  `json:"place_types_json"`
	PlaceConfidencePct    *float64 `json:"place_confidence_pct"`
	SummaryText           *string  `json:"summary_text"`
	DiscoveriesJson       *string  `json:"discoveries_json"`
}

func (q *Queries) CreateLearningResult(ctx context.Context, arg CreateLearningResultParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createLearningResult,
		arg.UploadID,
		arg.ParkID,
		arg.ParkName,
		arg.VehicleMedianSpeedKmh,
		arg.VehicleMaxSpeedKmh,
		arg.FootMedianSpeedKmh,
		arg.FootMaxSpeedKmh,
		arg.FootMcpAreaKm2,
		arg.NewRoadsFound,
		arg.NewRoadsKm,
		arg.RoadConfidencePct,
		arg.NewAirstripsFound,
		arg.AirstripConfidencePct,
		arg.NewPlacesFound,
		arg.PlaceTypesJson,
		arg.PlaceConfidencePct,
		arg.SummaryText,
		arg.DiscoveriesJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createVehicleTrack = `-- name: CreateVehicleTrack :one
INSERT INTO vehicle_tracks (park_id, upload_id, geojson, length_m, movement_type)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type CreateVehicleTrackParams struct {
	ParkID       string   `json:"park_id"`
	UploadID     *int64   `json:"upload_id"`
	Geojson      string   `json:"geojson"`
	LengthM      *float64 `json:"length_m"`
	MovementType *string  `json:"movement_type"`
}

func (q *Queries) CreateVehicleTrack(ctx context.Context, arg CreateVehicleTrackParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createVehicleTrack,
		arg.ParkID,
		arg.UploadID,
		arg.Geojson,
		arg.LengthM,
		arg.MovementType,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const failLearningJob = `-- name: FailLearningJob :exec
UPDATE gpx_learning_queue SET status = 'failed', completed_at = CURRENT_TIMESTAMP, error_message = ? WHERE id = ?
`

type FailLearningJobParams struct {
	ErrorMessage *string `json:"error_message"`
	ID           int64   `json:"id"`
}

func (q *Queries) FailLearningJob(ctx context.Context, arg FailLearningJobParams) error {
	_, err := q.db.ExecContext(ctx, failLearningJob, arg.ErrorMessage, arg.ID)
	return err
}

const findNearbyAirstrips = `-- name: FindNearbyAirstrips :many
SELECT id, park_id, lat, lon, heading_deg, length_m, aircraft_type, landing_count, takeoff_count, confidence_pct, status, approved_by, approved_at, approach_json, created_at, updated_at FROM learned_airstrips WHERE park_id = ? AND ABS(lat - ?) < 0.01 AND ABS(lon - ?) < 0.01
`

type FindNearbyAirstripsParams struct {
	ParkID string  `json:"park_id"`
	Lat    float64 `json:"lat"`
	Lon    float64 `json:"lon"`
}

func (q *Queries) FindNearbyAirstrips(ctx context.Context, arg FindNearbyAirstripsParams) ([]LearnedAirstrip, error) {
	rows, err := q.db.QueryContext(ctx, findNearbyAirstrips, arg.ParkID, arg.Lat, arg.Lon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearnedAirstrip{}
	for rows.Next() {
		var i LearnedAirstrip
		if err := rows.Scan(
			&i.ID,
			&i.ParkID,
			&i.Lat,
			&i.Lon,
			&i.HeadingDeg,
			&i.LengthM,
			&i.AircraftType,
			&i.LandingCount,
			&i.TakeoffCount,
			&i.ConfidencePct,
			&i.Status,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.ApproachJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNearbyPlaces = `-- name: FindNearbyPlaces :many
SELECT id, park_id, lat, lon, place_type, name, visit_count, avg_duration_minutes, confidence_pct, status, approved_by, approved_at, created_at, updated_at FROM learned_places WHERE park_id = ? AND ABS(lat - ?) < 0.005 AND ABS(lon - ?) < 0.005
`

type FindNearbyPlacesParams struct {
	ParkID string  `json:"park_id"`
	Lat    float64 `json:"lat"`
	Lon    float64 `json:"lon"`
}

func (q *Queries) FindNearbyPlaces(ctx context.Context, arg FindNearbyPlacesParams) ([]LearnedPlace, error) {
	rows, err := q.db.QueryContext(ctx, findNearbyPlaces, arg.ParkID, arg.Lat, arg.Lon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearnedPlace{}
	for rows.Next() {
		var i LearnedPlace
		if err := rows.Scan(
			&i.ID,
			&i.ParkID,
			&i.Lat,
			&i.Lon,
			&i.PlaceType,
			&i.Name,
			&i.VisitCount,
			&i.AvgDurationMinutes,
			&i.ConfidencePct,
			&i.Status,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNearbyVehicleTracks = `-- name: FindNearbyVehicleTracks :many
SELECT id, park_id, geojson, length_m FROM vehicle_tracks 
WHERE park_id = ? LIMIT 1000
`

type FindNearbyVehicleTracksRow struct {
	ID      int64    `json:"id"`
	ParkID  string   `json:"park_id"`
	Geojson string   `json:"geojson"`
	LengthM *float64 `json:"length_m"`
}

func (q *Queries) FindNearbyVehicleTracks(ctx context.Context, parkID string) ([]FindNearbyVehicleTracksRow, error) {
	rows, err := q.db.QueryContext(ctx, findNearbyVehicleTracks, parkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindNearbyVehicleTracksRow{}
	for rows.Next() {
		var i FindNearbyVehicleTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.ParkID,
			&i.Geojson,
			&i.LengthM,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllLearningResults = `-- name: GetAllLearningResults :many
SELECT id, upload_id, park_id, park_name, vehicle_median_speed_kmh, vehicle_max_speed_kmh, foot_median_speed_kmh, foot_max_speed_kmh, foot_mcp_area_km2, new_roads_found, new_roads_km, road_confidence_pct, new_airstrips_found, airstrip_confidence_pct, new_places_found, place_types_json, place_confidence_pct, summary_text, discoveries_json, created_at FROM gpx_learning_results ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type GetAllLearningResultsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) GetAllLearningResults(ctx context.Context, arg GetAllLearningResultsParams) ([]GpxLearningResult, error) {
	rows, err := q.db.QueryContext(ctx, getAllLearningResults, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GpxLearningResult{}
	for rows.Next() {
		var i GpxLearningResult
		if err := rows.Scan(
			&i.ID,
			&i.UploadID,
			&i.ParkID,
			&i.ParkName,
			&i.VehicleMedianSpeedKmh,
			&i.VehicleMaxSpeedKmh,
			&i.FootMedianSpeedKmh,
			&i.FootMaxSpeedKmh,
			&i.FootMcpAreaKm2,
			&i.NewRoadsFound,
			&i.NewRoadsKm,
			&i.RoadConfidencePct,
			&i.NewAirstripsFound,
			&i.AirstripConfidencePct,
			&i.NewPlacesFound,
			&i.PlaceTypesJson,
			&i.PlaceConfidencePct,
			&i.SummaryText,
			&i.DiscoveriesJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLearnedAirstripsByPark = `-- name: GetLearnedAirstripsByPark :many
SELECT id, park_id, lat, lon, heading_deg, length_m, aircraft_type, landing_count, takeoff_count, confidence_pct, status, approved_by, approved_at, approach_json, created_at, updated_at FROM learned_airstrips WHERE park_id = ? AND status IN ('pending', 'approved') ORDER BY confidence_pct DESC
`

func (q *Queries) GetLearnedAirstripsByPark(ctx context.Context, parkID string) ([]LearnedAirstrip, error) {
	rows, err := q.db.QueryContext(ctx, getLearnedAirstripsByPark, parkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearnedAirstrip{}
	for rows.Next() {
		var i LearnedAirstrip
		if err := rows.Scan(
			&i.ID,
			&i.ParkID,
			&i.Lat,
			&i.Lon,
			&i.HeadingDeg,
			&i.LengthM,
			&i.AircraftType,
			&i.LandingCount,
			&i.TakeoffCount,
			&i.ConfidencePct,
			&i.Status,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.ApproachJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLearnedPlacesByPark = `-- name: GetLearnedPlacesByPark :many
SELECT id, park_id, lat, lon, place_type, name, visit_count, avg_duration_minutes, confidence_pct, status, approved_by, approved_at, created_at, updated_at FROM learned_places WHERE park_id = ? AND status IN ('pending', 'approved') ORDER BY confidence_pct DESC
`

func (q *Queries) GetLearnedPlacesByPark(ctx context.Context, parkID string) ([]LearnedPlace, error) {
	rows, err := q.db.QueryContext(ctx, getLearnedPlacesByPark, parkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearnedPlace{}
	for rows.Next() {
		var i LearnedPlace
		if err := rows.Scan(
			&i.ID,
			&i.ParkID,
			&i.Lat,
			&i.Lon,
			&i.PlaceType,
			&i.Name,
			&i.VisitCount,
			&i.AvgDurationMinutes,
			&i.ConfidencePct,
			&i.Status,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLearnedRoadsByPark = `-- name: GetLearnedRoadsByPark :many
SELECT id, park_id, geojson, length_m, match_count, confidence_pct, status, approved_by, approved_at, created_at, updated_at FROM learned_roads WHERE park_id = ? AND status IN ('pending', 'approved') ORDER BY confidence_pct DESC
`

func (q *Queries) GetLearnedRoadsByPark(ctx context.Context, parkID string) ([]LearnedRoad, error) {
	rows, err := q.db.QueryContext(ctx, getLearnedRoadsByPark, parkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearnedRoad{}
	for rows.Next() {
		var i LearnedRoad
		if err := rows.Scan(
			&i.ID,
			&i.ParkID,
			&i.Geojson,
			&i.LengthM,
			&i.MatchCount,
			&i.ConfidencePct,
			&i.Status,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLearningResultsByPark = `-- name: GetLearningResultsByPark :many
SELECT id, upload_id, park_id, park_name, vehicle_median_speed_kmh, vehicle_max_speed_kmh, foot_median_speed_kmh, foot_max_speed_kmh, foot_mcp_area_km2, new_roads_found, new_roads_km, road_confidence_pct, new_airstrips_found, airstrip_confidence_pct, new_places_found, place_types_json, place_confidence_pct, summary_text, discoveries_json, created_at FROM gpx_learning_results WHERE park_id = ? ORDER BY created_at DESC LIMIT ?
`

type GetLearningResultsByParkParams struct {
	ParkID string `json:"park_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) GetLearningResultsByPark(ctx context.Context, arg GetLearningResultsByParkParams) ([]GpxLearningResult, error) {
	rows, err := q.db.QueryContext(ctx, getLearningResultsByPark, arg.ParkID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GpxLearningResult{}
	for rows.Next() {
		var i GpxLearningResult
		if err := rows.Scan(
			&i.ID,
			&i.UploadID,
			&i.ParkID,
			&i.ParkName,
			&i.VehicleMedianSpeedKmh,
			&i.VehicleMaxSpeedKmh,
			&i.FootMedianSpeedKmh,
			&i.FootMaxSpeedKmh,
			&i.FootMcpAreaKm2,
			&i.NewRoadsFound,
			&i.NewRoadsKm,
			&i.RoadConfidencePct,
			&i.NewAirstripsFound,
			&i.AirstripConfidencePct,
			&i.NewPlacesFound,
			&i.PlaceTypesJson,
			&i.PlaceConfidencePct,
			&i.SummaryText,
			&i.DiscoveriesJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingApprovals = `-- name: GetPendingApprovals :many
SELECT 'road' as type, id, park_id, confidence_pct, created_at FROM learned_roads WHERE status = 'pending'
UNION ALL
SELECT 'airstrip' as type, id, park_id, confidence_pct, created_at FROM learned_airstrips WHERE status = 'pending'
UNION ALL
SELECT 'place' as type, id, park_id, confidence_pct, created_at FROM learned_places WHERE status = 'pending'
ORDER BY created_at DESC LIMIT ?
`

type GetPendingApprovalsRow struct {
	Type          string     `json:"type"`
	ID            int64      `json:"id"`
	ParkID        string     `json:"park_id"`
	ConfidencePct *float64   `json:"confidence_pct"`
	CreatedAt     *time.Time `json:"created_at"`
}

func (q *Queries) GetPendingApprovals(ctx context.Context, limit int64) ([]GetPendingApprovalsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingApprovals, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingApprovalsRow{}
	for rows.Next() {
		var i GetPendingApprovalsRow
		if err := rows.Scan(
			&i.Type,
			&i.ID,
			&i.ParkID,
			&i.ConfidencePct,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingLearningJobs = `-- name: GetPendingLearningJobs :many
SELECT id, upload_id, park_id, status, error_message, created_at, started_at, completed_at FROM gpx_learning_queue WHERE status = 'pending' ORDER BY created_at LIMIT ?
`

func (q *Queries) GetPendingLearningJobs(ctx context.Context, limit int64) ([]GpxLearningQueue, error) {
	rows, err := q.db.QueryContext(ctx, getPendingLearningJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GpxLearningQueue{}
	for rows.Next() {
		var i GpxLearningQueue
		if err := rows.Scan(
			&i.ID,
			&i.UploadID,
			&i.ParkID,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVehicleStatsByPark = `-- name: GetVehicleStatsByPark :many
SELECT id, park_id, movement_type, total_distance_km, total_time_hours, median_speed_kmh, max_speed_kmh, p90_speed_kmh, sample_count, updated_at FROM park_vehicle_stats WHERE park_id = ?
`

func (q *Queries) GetVehicleStatsByPark(ctx context.Context, parkID string) ([]ParkVehicleStat, error) {
	rows, err := q.db.QueryContext(ctx, getVehicleStatsByPark, parkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParkVehicleStat{}
	for rows.Next() {
		var i ParkVehicleStat
		if err := rows.Scan(
			&i.ID,
			&i.ParkID,
			&i.MovementType,
			&i.TotalDistanceKm,
			&i.TotalTimeHours,
			&i.MedianSpeedKmh,
			&i.MaxSpeedKmh,
			&i.P90SpeedKmh,
			&i.SampleCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueGPXLearning = `-- name: QueueGPXLearning :one
INSERT INTO gpx_learning_queue (upload_id, park_id, status)
VALUES (?, ?, 'pending')
RETURNING id, upload_id, park_id, status, error_message, created_at, started_at, completed_at
`

type QueueGPXLearningParams struct {
	UploadID *int64  `json:"upload_id"`
	ParkID   *string `json:"park_id"`
}

func (q *Queries) QueueGPXLearning(ctx context.Context, arg QueueGPXLearningParams) (GpxLearningQueue, error) {
	row := q.db.QueryRowContext(ctx, queueGPXLearning, arg.UploadID, arg.ParkID)
	var i GpxLearningQueue
	err := row.Scan(
		&i.ID,
		&i.UploadID,
		&i.ParkID,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const rejectLearnedRoad = `-- name: RejectLearnedRoad :exec
UPDATE learned_roads SET status = 'rejected', approved_by = ?, approved_at = CURRENT_TIMESTAMP WHERE id = ?
`

type RejectLearnedRoadParams struct {
	ApprovedBy *string `json:"approved_by"`
	ID         int64   `json:"id"`
}

func (q *Queries) RejectLearnedRoad(ctx context.Context, arg RejectLearnedRoadParams) error {
	_, err := q.db.ExecContext(ctx, rejectLearnedRoad, arg.ApprovedBy, arg.ID)
	return err
}

const startLearningJob = `-- name: StartLearningJob :exec
UPDATE gpx_learning_queue SET status = 'processing', started_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) StartLearningJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, startLearningJob, id)
	return err
}

const updateAirstripStats = `-- name: UpdateAirstripStats :exec
UPDATE learned_airstrips SET landing_count = landing_count + ?, takeoff_count = takeoff_count + ?, confidence_pct = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateAirstripStatsParams struct {
	LandingCount  *int64   `json:"landing_count"`
	TakeoffCount  *int64   `json:"takeoff_count"`
	ConfidencePct *float64 `json:"confidence_pct"`
	ID            int64    `json:"id"`
}

func (q *Queries) UpdateAirstripStats(ctx context.Context, arg UpdateAirstripStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateAirstripStats,
		arg.LandingCount,
		arg.TakeoffCount,
		arg.ConfidencePct,
		arg.ID,
	)
	return err
}

const updateLearnedRoadMatch = `-- name: UpdateLearnedRoadMatch :exec
UPDATE learned_roads SET match_count = match_count + 1, confidence_pct = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateLearnedRoadMatchParams struct {
	ConfidencePct *float64 `json:"confidence_pct"`
	ID            int64    `json:"id"`
}

func (q *Queries) UpdateLearnedRoadMatch(ctx context.Context, arg UpdateLearnedRoadMatchParams) error {
	_, err := q.db.ExecContext(ctx, updateLearnedRoadMatch, arg.ConfidencePct, arg.ID)
	return err
}

const updateLearningJobStatus = `-- name: UpdateLearningJobStatus :exec
UPDATE gpx_learning_queue SET status = ?1, error_message = ?2 WHERE id = ?3
`

type UpdateLearningJobStatusParams struct {
	Status       *string `json:"status"`
	ErrorMessage *string `json:"error_message"`
	ID           int64   `json:"id"`
}

func (q *Queries) UpdateLearningJobStatus(ctx context.Context, arg UpdateLearningJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateLearningJobStatus, arg.Status, arg.ErrorMessage, arg.ID)
	return err
}

const updatePlaceStats = `-- name: UpdatePlaceStats :exec
UPDATE learned_places SET visit_count = visit_count + 1, avg_duration_minutes = ?, confidence_pct = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdatePlaceStatsParams struct {
	AvgDurationMinutes *float64 `json:"avg_duration_minutes"`
	ConfidencePct      *float64 `json:"confidence_pct"`
	ID                 int64    `json:"id"`
}

func (q *Queries) UpdatePlaceStats(ctx context.Context, arg UpdatePlaceStatsParams) error {
	_, err := q.db.ExecContext(ctx, updatePlaceStats, arg.AvgDurationMinutes, arg.ConfidencePct, arg.ID)
	return err
}

const upsertVehicleStats = `-- name: UpsertVehicleStats :exec
INSERT INTO park_vehicle_stats (park_id, movement_type, total_distance_km, total_time_hours, median_speed_kmh, max_speed_kmh, p90_speed_kmh, sample_count)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(park_id, movement_type) DO UPDATE SET
    total_distance_km = total_distance_km + excluded.total_distance_km,
    total_time_hours = total_time_hours + excluded.total_time_hours,
    median_speed_kmh = excluded.median_speed_kmh,
    max_speed_kmh = CASE WHEN excluded.max_speed_kmh > max_speed_kmh THEN excluded.max_speed_kmh ELSE max_speed_kmh END,
    p90_speed_kmh = excluded.p90_speed_kmh,
    sample_count = sample_count + excluded.sample_count,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertVehicleStatsParams struct {
	ParkID          string   `json:"park_id"`
	MovementType    string   `json:"movement_type"`
	TotalDistanceKm *float64 `json:"total_distance_km"`
	TotalTimeHours  *float64 `json:"total_time_hours"`
	MedianSpeedKmh  *float64 `json:"median_speed_kmh"`
	MaxSpeedKmh     *float64 `json:"max_speed_kmh"`
	P90SpeedKmh     *float64 `json:"p90_speed_kmh"`
	SampleCount     *int64   `json:"sample_count"`
}

func (q *Queries) UpsertVehicleStats(ctx context.Context, arg UpsertVehicleStatsParams) error {
	_, err := q.db.ExecContext(ctx, upsertVehicleStats,
		arg.ParkID,
		arg.MovementType,
		arg.TotalDistanceKm,
		arg.TotalTimeHours,
		arg.MedianSpeedKmh,
		arg.MaxSpeedKmh,
		arg.P90SpeedKmh,
		arg.SampleCount,
	)
	return err
}
