// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type EffortDatum struct {
	ID               int64    `json:"id"`
	GridCellID       string   `json:"grid_cell_id"`
	Year             int64    `json:"year"`
	Month            int64    `json:"month"`
	Day              *int64   `json:"day"`
	MovementType     string   `json:"movement_type"`
	TotalDistanceKm  float64  `json:"total_distance_km"`
	TotalPoints      int64    `json:"total_points"`
	UniqueUploads    int64    `json:"unique_uploads"`
	ProtectedAreaIds *string  `json:"protected_area_ids"`
	CoveragePercent  *float64 `json:"coverage_percent"`
}

type FireDailyGrid struct {
	ID              int64    `json:"id"`
	GridCellID      string   `json:"grid_cell_id"`
	Date            string   `json:"date"`
	FireCount       int64    `json:"fire_count"`
	TotalFrp        *float64 `json:"total_frp"`
	AvgConfidence   *float64 `json:"avg_confidence"`
	InProtectedArea *int64   `json:"in_protected_area"`
	ProtectedAreaID *string  `json:"protected_area_id"`
}

type FireDataSync struct {
	ID              int64   `json:"id"`
	ParkID          string  `json:"park_id"`
	BboxWest        float64 `json:"bbox_west"`
	BboxSouth       float64 `json:"bbox_south"`
	BboxEast        float64 `json:"bbox_east"`
	BboxNorth       float64 `json:"bbox_north"`
	BufferKm        float64 `json:"buffer_km"`
	FirstDate       *string `json:"first_date"`
	LastDate        *string `json:"last_date"`
	LastSyncAt      *string `json:"last_sync_at"`
	TotalDetections *int64  `json:"total_detections"`
}

type FireDetection struct {
	ID              int64    `json:"id"`
	Latitude        float64  `json:"latitude"`
	Longitude       float64  `json:"longitude"`
	Brightness      *float64 `json:"brightness"`
	Scan            *float64 `json:"scan"`
	Track           *float64 `json:"track"`
	AcqDate         string   `json:"acq_date"`
	AcqTime         *string  `json:"acq_time"`
	Satellite       *string  `json:"satellite"`
	Instrument      *string  `json:"instrument"`
	Confidence      *string  `json:"confidence"`
	Version         *string  `json:"version"`
	BrightT31       *float64 `json:"bright_t31"`
	Frp             *float64 `json:"frp"`
	Daynight        *string  `json:"daynight"`
	GridCellID      *string  `json:"grid_cell_id"`
	InProtectedArea *int64   `json:"in_protected_area"`
	ProtectedAreaID *string  `json:"protected_area_id"`
}

type GhslDatum struct {
	ID              int64    `json:"id"`
	ParkID          string   `json:"park_id"`
	BuiltUpKm2      *float64 `json:"built_up_km2"`
	SettlementCount *int64   `json:"settlement_count"`
	AnalyzedAt      *string  `json:"analyzed_at"`
}

type GpxUpload struct {
	ID              int64      `json:"id"`
	UserID          string     `json:"user_id"`
	Filename        string     `json:"filename"`
	MovementType    string     `json:"movement_type"`
	ProtectedAreaID *string    `json:"protected_area_id"`
	UploadDate      time.Time  `json:"upload_date"`
	StartTime       *time.Time `json:"start_time"`
	EndTime         *time.Time `json:"end_time"`
	TotalDistanceKm float64    `json:"total_distance_km"`
	TotalPoints     int64      `json:"total_points"`
}

type GridCell struct {
	ID        string  `json:"id"`
	LatCenter float64 `json:"lat_center"`
	LonCenter float64 `json:"lon_center"`
	LatMin    float64 `json:"lat_min"`
	LatMax    float64 `json:"lat_max"`
	LonMin    float64 `json:"lon_min"`
	LonMax    float64 `json:"lon_max"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type OsmRoadlessDatum struct {
	ID                 int64    `json:"id"`
	ParkID             string   `json:"park_id"`
	RoadlessPercentage *float64 `json:"roadless_percentage"`
	TotalRoadKm        *float64 `json:"total_road_km"`
	AnalyzedAt         *string  `json:"analyzed_at"`
}

type PaPublication struct {
	ID           int64     `json:"id"`
	PaID         string    `json:"pa_id"`
	OpenalexID   string    `json:"openalex_id"`
	Title        string    `json:"title"`
	Authors      *string   `json:"authors"`
	Year         *int64    `json:"year"`
	Doi          *string   `json:"doi"`
	Url          *string   `json:"url"`
	Abstract     *string   `json:"abstract"`
	CitedByCount *int64    `json:"cited_by_count"`
	CreatedAt    time.Time `json:"created_at"`
}

type PaPublicationSync struct {
	PaID        string    `json:"pa_id"`
	LastSync    time.Time `json:"last_sync"`
	ResultCount int64     `json:"result_count"`
}

type ParkChecklist struct {
	ID          int64      `json:"id"`
	PaID        string     `json:"pa_id"`
	ItemID      string     `json:"item_id"`
	Status      string     `json:"status"`
	Notes       *string    `json:"notes"`
	DocumentUrl *string    `json:"document_url"`
	UpdatedBy   *string    `json:"updated_by"`
	UpdatedAt   *time.Time `json:"updated_at"`
}

type ParkDocument struct {
	ID          int64      `json:"id"`
	PaID        string     `json:"pa_id"`
	Category    string     `json:"category"`
	ItemID      *string    `json:"item_id"`
	Title       string     `json:"title"`
	Description *string    `json:"description"`
	FileUrl     *string    `json:"file_url"`
	FileType    *string    `json:"file_type"`
	UploadedBy  *string    `json:"uploaded_by"`
	UploadedAt  *time.Time `json:"uploaded_at"`
	Year        *int64     `json:"year"`
	Summary     *string    `json:"summary"`
}

type ParkFireAnalysis struct {
	ID                     int64    `json:"id"`
	ParkID                 string   `json:"park_id"`
	AnalyzedAt             *string  `json:"analyzed_at"`
	TotalFires             *int64   `json:"total_fires"`
	TotalInfractions       *int64   `json:"total_infractions"`
	InfractionRate         *float64 `json:"infraction_rate"`
	PeakInfractionDay      *string  `json:"peak_infraction_day"`
	PeakInfractionCount    *int64   `json:"peak_infraction_count"`
	NetSouthKm             *float64 `json:"net_south_km"`
	AvgDailyMovementKm     *float64 `json:"avg_daily_movement_km"`
	MonthlyStatsJson       *string  `json:"monthly_stats_json"`
	GroupsStoppedInside    *int64   `json:"groups_stopped_inside"`
	GroupsTransitedThrough *int64   `json:"groups_transited_through"`
}

type ParkGroupInfraction struct {
	ID                  int64    `json:"id"`
	ParkID              string   `json:"park_id"`
	Year                int64    `json:"year"`
	TotalGroups         *int64   `json:"total_groups"`
	GroupsStoppedInside *int64   `json:"groups_stopped_inside"`
	GroupsTransited     *int64   `json:"groups_transited"`
	AvgDaysBurning      *float64 `json:"avg_days_burning"`
	AnalyzedAt          *string  `json:"analyzed_at"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type SubcellVisit struct {
	ID         int64     `json:"id"`
	GridCellID string    `json:"grid_cell_id"`
	SubcellID  string    `json:"subcell_id"`
	VisitDate  time.Time `json:"visit_date"`
	VisitCount int64     `json:"visit_count"`
}

type TrackPoint struct {
	ID         int64      `json:"id"`
	UploadID   int64      `json:"upload_id"`
	Lat        float64    `json:"lat"`
	Lon        float64    `json:"lon"`
	Elevation  *float64   `json:"elevation"`
	Timestamp  *time.Time `json:"timestamp"`
	GridCellID *string    `json:"grid_cell_id"`
}

type User struct {
	ID               string     `json:"id"`
	Email            string     `json:"email"`
	Name             string     `json:"name"`
	Organization     string     `json:"organization"`
	OrganizationType string     `json:"organization_type"`
	Role             string     `json:"role"`
	CreatedAt        time.Time  `json:"created_at"`
	ApprovedAt       *time.Time `json:"approved_at"`
	ApprovedBy       *string    `json:"approved_by"`
	PasswordHash     string     `json:"password_hash"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
