// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type AircraftPattern struct {
	ID           int64      `json:"id"`
	ParkID       string     `json:"park_id"`
	UploadID     *int64     `json:"upload_id"`
	PatternType  string     `json:"pattern_type"`
	AircraftType *string    `json:"aircraft_type"`
	StartLat     *float64   `json:"start_lat"`
	StartLon     *float64   `json:"start_lon"`
	EndLat       *float64   `json:"end_lat"`
	EndLon       *float64   `json:"end_lon"`
	Geojson      *string    `json:"geojson"`
	AvgSpeedKmh  *float64   `json:"avg_speed_kmh"`
	CreatedAt    *time.Time `json:"created_at"`
}

type DatasetVersion struct {
	ID          int64      `json:"id"`
	ParkID      string     `json:"park_id"`
	DatasetType string     `json:"dataset_type"`
	Version     int64      `json:"version"`
	DataJson    string     `json:"data_json"`
	CreatedBy   *string    `json:"created_by"`
	CreatedAt   *time.Time `json:"created_at"`
	IsActive    *int64     `json:"is_active"`
}

type EffortDatum struct {
	ID               int64    `json:"id"`
	GridCellID       string   `json:"grid_cell_id"`
	Year             int64    `json:"year"`
	Month            int64    `json:"month"`
	Day              *int64   `json:"day"`
	MovementType     string   `json:"movement_type"`
	TotalDistanceKm  float64  `json:"total_distance_km"`
	TotalPoints      int64    `json:"total_points"`
	UniqueUploads    int64    `json:"unique_uploads"`
	ProtectedAreaIds *string  `json:"protected_area_ids"`
	CoveragePercent  *float64 `json:"coverage_percent"`
}

type FeatureGeometry struct {
	ID             int64      `json:"id"`
	FeatureType    string     `json:"feature_type"`
	FeatureID      string     `json:"feature_id"`
	ParkID         string     `json:"park_id"`
	Geojson        string     `json:"geojson"`
	BboxMinx       *float64   `json:"bbox_minx"`
	BboxMiny       *float64   `json:"bbox_miny"`
	BboxMaxx       *float64   `json:"bbox_maxx"`
	BboxMaxy       *float64   `json:"bbox_maxy"`
	StartDate      *string    `json:"start_date"`
	EndDate        *string    `json:"end_date"`
	PropertiesJson *string    `json:"properties_json"`
	CreatedAt      *time.Time `json:"created_at"`
}

type FireDailyGrid struct {
	ID              int64    `json:"id"`
	GridCellID      string   `json:"grid_cell_id"`
	Date            string   `json:"date"`
	FireCount       int64    `json:"fire_count"`
	TotalFrp        *float64 `json:"total_frp"`
	AvgConfidence   *float64 `json:"avg_confidence"`
	InProtectedArea *int64   `json:"in_protected_area"`
	ProtectedAreaID *string  `json:"protected_area_id"`
}

type FireDataSync struct {
	ID              int64   `json:"id"`
	ParkID          string  `json:"park_id"`
	BboxWest        float64 `json:"bbox_west"`
	BboxSouth       float64 `json:"bbox_south"`
	BboxEast        float64 `json:"bbox_east"`
	BboxNorth       float64 `json:"bbox_north"`
	BufferKm        float64 `json:"buffer_km"`
	FirstDate       *string `json:"first_date"`
	LastDate        *string `json:"last_date"`
	LastSyncAt      *string `json:"last_sync_at"`
	TotalDetections *int64  `json:"total_detections"`
}

type FireDetection struct {
	ID              int64    `json:"id"`
	Latitude        float64  `json:"latitude"`
	Longitude       float64  `json:"longitude"`
	Brightness      *float64 `json:"brightness"`
	Scan            *float64 `json:"scan"`
	Track           *float64 `json:"track"`
	AcqDate         string   `json:"acq_date"`
	AcqTime         *string  `json:"acq_time"`
	Satellite       *string  `json:"satellite"`
	Instrument      *string  `json:"instrument"`
	Confidence      *string  `json:"confidence"`
	Version         *string  `json:"version"`
	BrightT31       *float64 `json:"bright_t31"`
	Frp             *float64 `json:"frp"`
	Daynight        *string  `json:"daynight"`
	GridCellID      *string  `json:"grid_cell_id"`
	InProtectedArea *int64   `json:"in_protected_area"`
	ProtectedAreaID *string  `json:"protected_area_id"`
}

type FireGroupAlert struct {
	ID                int64      `json:"id"`
	ParkID            string     `json:"park_id"`
	GroupName         string     `json:"group_name"`
	AlertType         string     `json:"alert_type"`
	FirstDetectedAt   time.Time  `json:"first_detected_at"`
	LastUpdatedAt     time.Time  `json:"last_updated_at"`
	LeftAt            *time.Time `json:"left_at"`
	FireCount         *int64     `json:"fire_count"`
	DaysActive        *int64     `json:"days_active"`
	CentroidLat       *float64   `json:"centroid_lat"`
	CentroidLon       *float64   `json:"centroid_lon"`
	LatestLat         *float64   `json:"latest_lat"`
	LatestLon         *float64   `json:"latest_lon"`
	MovementDirection *string    `json:"movement_direction"`
	IsDismissed       *bool      `json:"is_dismissed"`
	CreatedAt         *time.Time `json:"created_at"`
}

type GhslDatum struct {
	ID              int64    `json:"id"`
	ParkID          string   `json:"park_id"`
	BuiltUpKm2      *float64 `json:"built_up_km2"`
	SettlementCount *int64   `json:"settlement_count"`
	AnalyzedAt      *string  `json:"analyzed_at"`
}

type GpxLearningQueue struct {
	ID           int64      `json:"id"`
	UploadID     *int64     `json:"upload_id"`
	ParkID       *string    `json:"park_id"`
	Status       *string    `json:"status"`
	ErrorMessage *string    `json:"error_message"`
	CreatedAt    *time.Time `json:"created_at"`
	StartedAt    *time.Time `json:"started_at"`
	CompletedAt  *time.Time `json:"completed_at"`
}

type GpxLearningResult struct {
	ID                    int64      `json:"id"`
	UploadID              *int64     `json:"upload_id"`
	ParkID                string     `json:"park_id"`
	ParkName              *string    `json:"park_name"`
	VehicleMedianSpeedKmh *float64   `json:"vehicle_median_speed_kmh"`
	VehicleMaxSpeedKmh    *float64   `json:"vehicle_max_speed_kmh"`
	FootMedianSpeedKmh    *float64   `json:"foot_median_speed_kmh"`
	FootMaxSpeedKmh       *float64   `json:"foot_max_speed_kmh"`
	FootMcpAreaKm2        *float64   `json:"foot_mcp_area_km2"`
	NewRoadsFound         *int64     `json:"new_roads_found"`
	NewRoadsKm            *float64   `json:"new_roads_km"`
	RoadConfidencePct     *float64   `json:"road_confidence_pct"`
	NewAirstripsFound     *int64     `json:"new_airstrips_found"`
	AirstripConfidencePct *float64   `json:"airstrip_confidence_pct"`
	NewPlacesFound        *int64     `json:"new_places_found"`
	PlaceTypesJson        *string    `json:"place_types_json"`
	PlaceConfidencePct    *float64   `json:"place_confidence_pct"`
	SummaryText           *string    `json:"summary_text"`
	DiscoveriesJson       *string    `json:"discoveries_json"`
	CreatedAt             *time.Time `json:"created_at"`
}

type GpxUpload struct {
	ID               int64      `json:"id"`
	UserID           string     `json:"user_id"`
	Filename         string     `json:"filename"`
	MovementType     string     `json:"movement_type"`
	ProtectedAreaID  *string    `json:"protected_area_id"`
	UploadDate       time.Time  `json:"upload_date"`
	StartTime        *time.Time `json:"start_time"`
	EndTime          *time.Time `json:"end_time"`
	TotalDistanceKm  float64    `json:"total_distance_km"`
	TotalPoints      int64      `json:"total_points"`
	FileHash         *string    `json:"file_hash"`
	ProcessingStatus *string    `json:"processing_status"`
	ErrorMessage     *string    `json:"error_message"`
}

type GpxUploadLog struct {
	ID                     int64     `json:"id"`
	UploadID               *int64    `json:"upload_id"`
	UserID                 string    `json:"user_id"`
	UserEmail              *string   `json:"user_email"`
	Filename               string    `json:"filename"`
	UploadTime             time.Time `json:"upload_time"`
	IsValid                bool      `json:"is_valid"`
	TotalPoints            int64     `json:"total_points"`
	ValidationErrors       *string   `json:"validation_errors"`
	ValidationWarnings     *string   `json:"validation_warnings"`
	ProtectedAreaID        *string   `json:"protected_area_id"`
	ProtectedAreaName      *string   `json:"protected_area_name"`
	PatrolKm               float64   `json:"patrol_km"`
	RoadKm                 float64   `json:"road_km"`
	BoundaryKm             float64   `json:"boundary_km"`
	ExcludedKm             float64   `json:"excluded_km"`
	TotalSegments          int64     `json:"total_segments"`
	PatrolSegments         int64     `json:"patrol_segments"`
	StaticSegments         int64     `json:"static_segments"`
	ExcludedSegments       int64     `json:"excluded_segments"`
	ClassifiedSegmentsJson *string   `json:"classified_segments_json"`
	ProcessingStatus       *string   `json:"processing_status"`
	RejectionReason        *string   `json:"rejection_reason"`
}

type GridCell struct {
	ID        string  `json:"id"`
	LatCenter float64 `json:"lat_center"`
	LonCenter float64 `json:"lon_center"`
	LatMin    float64 `json:"lat_min"`
	LatMax    float64 `json:"lat_max"`
	LonMin    float64 `json:"lon_min"`
	LonMax    float64 `json:"lon_max"`
}

type LearnedAirstrip struct {
	ID            int64      `json:"id"`
	ParkID        string     `json:"park_id"`
	Lat           float64    `json:"lat"`
	Lon           float64    `json:"lon"`
	HeadingDeg    *float64   `json:"heading_deg"`
	LengthM       *float64   `json:"length_m"`
	AircraftType  *string    `json:"aircraft_type"`
	LandingCount  *int64     `json:"landing_count"`
	TakeoffCount  *int64     `json:"takeoff_count"`
	ConfidencePct *float64   `json:"confidence_pct"`
	Status        *string    `json:"status"`
	ApprovedBy    *string    `json:"approved_by"`
	ApprovedAt    *time.Time `json:"approved_at"`
	ApproachJson  *string    `json:"approach_json"`
	CreatedAt     *time.Time `json:"created_at"`
	UpdatedAt     *time.Time `json:"updated_at"`
}

type LearnedAirstripsHistory struct {
	HistoryID    int64      `json:"history_id"`
	OriginalID   int64      `json:"original_id"`
	ParkID       string     `json:"park_id"`
	Lat          float64    `json:"lat"`
	Lon          float64    `json:"lon"`
	HeadingDeg   *float64   `json:"heading_deg"`
	LengthM      *float64   `json:"length_m"`
	AircraftType *string    `json:"aircraft_type"`
	LandingCount *int64     `json:"landing_count"`
	Confidence   *float64   `json:"confidence"`
	IsApproved   *int64     `json:"is_approved"`
	IsRejected   *int64     `json:"is_rejected"`
	Version      int64      `json:"version"`
	Action       string     `json:"action"`
	ActionBy     *string    `json:"action_by"`
	ActionAt     *time.Time `json:"action_at"`
}

type LearnedPlace struct {
	ID                 int64      `json:"id"`
	ParkID             string     `json:"park_id"`
	Lat                float64    `json:"lat"`
	Lon                float64    `json:"lon"`
	PlaceType          *string    `json:"place_type"`
	Name               *string    `json:"name"`
	VisitCount         *int64     `json:"visit_count"`
	AvgDurationMinutes *float64   `json:"avg_duration_minutes"`
	ConfidencePct      *float64   `json:"confidence_pct"`
	Status             *string    `json:"status"`
	ApprovedBy         *string    `json:"approved_by"`
	ApprovedAt         *time.Time `json:"approved_at"`
	CreatedAt          *time.Time `json:"created_at"`
	UpdatedAt          *time.Time `json:"updated_at"`
}

type LearnedPlacesHistory struct {
	HistoryID          int64      `json:"history_id"`
	OriginalID         int64      `json:"original_id"`
	ParkID             string     `json:"park_id"`
	Lat                float64    `json:"lat"`
	Lon                float64    `json:"lon"`
	PlaceType          *string    `json:"place_type"`
	VisitCount         *int64     `json:"visit_count"`
	AvgDurationMinutes *float64   `json:"avg_duration_minutes"`
	Confidence         *float64   `json:"confidence"`
	IsApproved         *int64     `json:"is_approved"`
	IsRejected         *int64     `json:"is_rejected"`
	Version            int64      `json:"version"`
	Action             string     `json:"action"`
	ActionBy           *string    `json:"action_by"`
	ActionAt           *time.Time `json:"action_at"`
}

type LearnedRoad struct {
	ID            int64      `json:"id"`
	ParkID        string     `json:"park_id"`
	Geojson       string     `json:"geojson"`
	LengthM       *float64   `json:"length_m"`
	MatchCount    *int64     `json:"match_count"`
	ConfidencePct *float64   `json:"confidence_pct"`
	Status        *string    `json:"status"`
	ApprovedBy    *string    `json:"approved_by"`
	ApprovedAt    *time.Time `json:"approved_at"`
	CreatedAt     *time.Time `json:"created_at"`
	UpdatedAt     *time.Time `json:"updated_at"`
}

type LearnedRoadsHistory struct {
	HistoryID  int64      `json:"history_id"`
	OriginalID int64      `json:"original_id"`
	ParkID     string     `json:"park_id"`
	Geojson    string     `json:"geojson"`
	DistanceKm *float64   `json:"distance_km"`
	MatchCount *int64     `json:"match_count"`
	Confidence *float64   `json:"confidence"`
	IsApproved *int64     `json:"is_approved"`
	IsRejected *int64     `json:"is_rejected"`
	Version    int64      `json:"version"`
	Action     string     `json:"action"`
	ActionBy   *string    `json:"action_by"`
	ActionAt   *time.Time `json:"action_at"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type OsmRoadlessDatum struct {
	ID                 int64    `json:"id"`
	ParkID             string   `json:"park_id"`
	RoadlessPercentage *float64 `json:"roadless_percentage"`
	TotalRoadKm        *float64 `json:"total_road_km"`
	AnalyzedAt         *string  `json:"analyzed_at"`
}

type PaPublication struct {
	ID           int64     `json:"id"`
	PaID         string    `json:"pa_id"`
	OpenalexID   string    `json:"openalex_id"`
	Title        string    `json:"title"`
	Authors      *string   `json:"authors"`
	Year         *int64    `json:"year"`
	Doi          *string   `json:"doi"`
	Url          *string   `json:"url"`
	Abstract     *string   `json:"abstract"`
	CitedByCount *int64    `json:"cited_by_count"`
	CreatedAt    time.Time `json:"created_at"`
}

type PaPublicationSync struct {
	PaID        string    `json:"pa_id"`
	LastSync    time.Time `json:"last_sync"`
	ResultCount int64     `json:"result_count"`
}

type ParkChecklist struct {
	ID          int64      `json:"id"`
	PaID        string     `json:"pa_id"`
	ItemID      string     `json:"item_id"`
	Status      string     `json:"status"`
	Notes       *string    `json:"notes"`
	DocumentUrl *string    `json:"document_url"`
	UpdatedBy   *string    `json:"updated_by"`
	UpdatedAt   *time.Time `json:"updated_at"`
}

type ParkDocument struct {
	ID          int64      `json:"id"`
	PaID        string     `json:"pa_id"`
	Category    string     `json:"category"`
	ItemID      *string    `json:"item_id"`
	Title       string     `json:"title"`
	Description *string    `json:"description"`
	FileUrl     *string    `json:"file_url"`
	FileType    *string    `json:"file_type"`
	UploadedBy  *string    `json:"uploaded_by"`
	UploadedAt  *time.Time `json:"uploaded_at"`
	Year        *int64     `json:"year"`
	Summary     *string    `json:"summary"`
}

type ParkFireAnalysis struct {
	ID                     int64    `json:"id"`
	ParkID                 string   `json:"park_id"`
	AnalyzedAt             *string  `json:"analyzed_at"`
	TotalFires             *int64   `json:"total_fires"`
	TotalInfractions       *int64   `json:"total_infractions"`
	InfractionRate         *float64 `json:"infraction_rate"`
	PeakInfractionDay      *string  `json:"peak_infraction_day"`
	PeakInfractionCount    *int64   `json:"peak_infraction_count"`
	NetSouthKm             *float64 `json:"net_south_km"`
	AvgDailyMovementKm     *float64 `json:"avg_daily_movement_km"`
	MonthlyStatsJson       *string  `json:"monthly_stats_json"`
	GroupsStoppedInside    *int64   `json:"groups_stopped_inside"`
	GroupsTransitedThrough *int64   `json:"groups_transited_through"`
}

type ParkGroupInfraction struct {
	ID                  int64    `json:"id"`
	ParkID              string   `json:"park_id"`
	Year                int64    `json:"year"`
	TotalGroups         *int64   `json:"total_groups"`
	GroupsStoppedInside *int64   `json:"groups_stopped_inside"`
	GroupsTransited     *int64   `json:"groups_transited"`
	AvgDaysBurning      *float64 `json:"avg_days_burning"`
	AnalyzedAt          *string  `json:"analyzed_at"`
}

type ParkPatrolMcp struct {
	ID           int64      `json:"id"`
	ParkID       string     `json:"park_id"`
	Mcp90Geojson *string    `json:"mcp_90_geojson"`
	McpAreaKm2   *float64   `json:"mcp_area_km2"`
	CentroidLat  *float64   `json:"centroid_lat"`
	CentroidLon  *float64   `json:"centroid_lon"`
	PointCount   *int64     `json:"point_count"`
	UpdatedAt    *time.Time `json:"updated_at"`
}

type ParkSettlement struct {
	ID                 int64      `json:"id"`
	ParkID             string     `json:"park_id"`
	Lat                float64    `json:"lat"`
	Lon                float64    `json:"lon"`
	AreaM2             *float64   `json:"area_m2"`
	PopulationEst      *int64     `json:"population_est"`
	HouseholdsEst      *int64     `json:"households_est"`
	NearestPlace       *string    `json:"nearest_place"`
	DistanceToPlaceKm  *float64   `json:"distance_to_place_km"`
	DirectionFromPlace *string    `json:"direction_from_place"`
	SettlementType     *string    `json:"settlement_type"`
	InBuffer           *int64     `json:"in_buffer"`
	TileRow            *int64     `json:"tile_row"`
	TileCol            *int64     `json:"tile_col"`
	DetectedAt         *time.Time `json:"detected_at"`
}

type ParkVehicleStat struct {
	ID              int64      `json:"id"`
	ParkID          string     `json:"park_id"`
	MovementType    string     `json:"movement_type"`
	TotalDistanceKm *float64   `json:"total_distance_km"`
	TotalTimeHours  *float64   `json:"total_time_hours"`
	MedianSpeedKmh  *float64   `json:"median_speed_kmh"`
	MaxSpeedKmh     *float64   `json:"max_speed_kmh"`
	P90SpeedKmh     *float64   `json:"p90_speed_kmh"`
	SampleCount     *int64     `json:"sample_count"`
	UpdatedAt       *time.Time `json:"updated_at"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type SettlementIntensity struct {
	ID                   int64      `json:"id"`
	SettlementID         int64      `json:"settlement_id"`
	ParkID               string     `json:"park_id"`
	Year                 int64      `json:"year"`
	Month                *int64     `json:"month"`
	TotalVisits          int64      `json:"total_visits"`
	TotalDurationMinutes float64    `json:"total_duration_minutes"`
	UniqueUploads        int64      `json:"unique_uploads"`
	FootVisits           *int64     `json:"foot_visits"`
	VehicleVisits        *int64     `json:"vehicle_visits"`
	AircraftVisits       *int64     `json:"aircraft_visits"`
	IsLikelyBase         *int64     `json:"is_likely_base"`
	UpdatedAt            *time.Time `json:"updated_at"`
}

type SettlementVisit struct {
	ID              int64      `json:"id"`
	SettlementID    int64      `json:"settlement_id"`
	UploadID        *int64     `json:"upload_id"`
	ParkID          string     `json:"park_id"`
	VisitDate       time.Time  `json:"visit_date"`
	VisitStart      *time.Time `json:"visit_start"`
	VisitEnd        *time.Time `json:"visit_end"`
	DurationMinutes float64    `json:"duration_minutes"`
	MovementType    string     `json:"movement_type"`
	ArrivingFrom    *string    `json:"arriving_from"`
	DepartingTo     *string    `json:"departing_to"`
	Year            int64      `json:"year"`
	Month           int64      `json:"month"`
	CreatedAt       *time.Time `json:"created_at"`
}

type SubcellVisit struct {
	ID         int64     `json:"id"`
	GridCellID string    `json:"grid_cell_id"`
	SubcellID  string    `json:"subcell_id"`
	VisitDate  time.Time `json:"visit_date"`
	VisitCount int64     `json:"visit_count"`
}

type TrackPoint struct {
	ID         int64      `json:"id"`
	UploadID   int64      `json:"upload_id"`
	Lat        float64    `json:"lat"`
	Lon        float64    `json:"lon"`
	Elevation  *float64   `json:"elevation"`
	Timestamp  *time.Time `json:"timestamp"`
	GridCellID *string    `json:"grid_cell_id"`
}

type User struct {
	ID               string     `json:"id"`
	Email            string     `json:"email"`
	Name             string     `json:"name"`
	Organization     string     `json:"organization"`
	OrganizationType string     `json:"organization_type"`
	Role             string     `json:"role"`
	CreatedAt        time.Time  `json:"created_at"`
	ApprovedAt       *time.Time `json:"approved_at"`
	ApprovedBy       *string    `json:"approved_by"`
	PasswordHash     string     `json:"password_hash"`
}

type VehicleTrack struct {
	ID           int64      `json:"id"`
	ParkID       string     `json:"park_id"`
	UploadID     *int64     `json:"upload_id"`
	Geojson      string     `json:"geojson"`
	LengthM      *float64   `json:"length_m"`
	MovementType *string    `json:"movement_type"`
	CreatedAt    *time.Time `json:"created_at"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
