// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"
)

type AircraftPattern struct {
	ID           int64      `json:"id"`
	ParkID       string     `json:"park_id"`
	UploadID     *int64     `json:"upload_id"`
	PatternType  string     `json:"pattern_type"`
	AircraftType *string    `json:"aircraft_type"`
	StartLat     *float64   `json:"start_lat"`
	StartLon     *float64   `json:"start_lon"`
	EndLat       *float64   `json:"end_lat"`
	EndLon       *float64   `json:"end_lon"`
	Geojson      *string    `json:"geojson"`
	AvgSpeedKmh  *float64   `json:"avg_speed_kmh"`
	CreatedAt    *time.Time `json:"created_at"`
}

type Aoi struct {
	ID               string     `json:"id"`
	Name             string     `json:"name"`
	Geometry         string     `json:"geometry"`
	BboxMinx         *float64   `json:"bbox_minx"`
	BboxMiny         *float64   `json:"bbox_miny"`
	BboxMaxx         *float64   `json:"bbox_maxx"`
	BboxMaxy         *float64   `json:"bbox_maxy"`
	AreaKm2          *float64   `json:"area_km2"`
	FromDate         *string    `json:"from_date"`
	ToDate           *string    `json:"to_date"`
	OwnerPrincipalID *int64     `json:"owner_principal_id"`
	Visibility       string     `json:"visibility"`
	State            string     `json:"state"`
	CreatedAt        *time.Time `json:"created_at"`
	Notes            *string    `json:"notes"`
	LineageID        *string    `json:"lineage_id"`
	Version          int64      `json:"version"`
	SupersededBy     *string    `json:"superseded_by"`
	ArchivedAt       *time.Time `json:"archived_at"`
}

type AoiDataset struct {
	AoiID      string     `json:"aoi_id"`
	Dataset    string     `json:"dataset"`
	Enabled    int64      `json:"enabled"`
	Priority   int64      `json:"priority"`
	State      string     `json:"state"`
	DependsOn  *string    `json:"depends_on"`
	Cursor     *string    `json:"cursor"`
	UnitsTotal *int64     `json:"units_total"`
	UnitsDone  *int64     `json:"units_done"`
	Coverage   *float64   `json:"coverage"`
	LeaseOwner *string    `json:"lease_owner"`
	LeaseUntil *time.Time `json:"lease_until"`
	LastRunAt  *time.Time `json:"last_run_at"`
	NextRunAt  *time.Time `json:"next_run_at"`
	Detail     *string    `json:"detail"`
}

type AoiFire struct {
	AoiID  string `json:"aoi_id"`
	FireID int64  `json:"fire_id"`
}

type AoiGrant struct {
	AoiID       string     `json:"aoi_id"`
	PrincipalID int64      `json:"principal_id"`
	Scope       string     `json:"scope"`
	CreatedAt   *time.Time `json:"created_at"`
}

type AoiPark struct {
	AoiID      string  `json:"aoi_id"`
	ParkID     string  `json:"park_id"`
	FracOfAoi  float64 `json:"frac_of_aoi"`
	FracOfPark float64 `json:"frac_of_park"`
}

type AutofetchSource struct {
	ID         int64      `json:"id"`
	ApiType    string     `json:"api_type"`
	ServiceUrl string     `json:"service_url"`
	Username   string     `json:"username"`
	Password   string     `json:"password"`
	IntervalH  int64      `json:"interval_h"`
	Enabled    int64      `json:"enabled"`
	ParkNames  string     `json:"park_names"`
	CreatedAt  *time.Time `json:"created_at"`
	LastRunAt  *time.Time `json:"last_run_at"`
	LastStatus *string    `json:"last_status"`
	LastPoints *int64     `json:"last_points"`
	Env        string     `json:"env"`
	OwnerRef   string     `json:"owner_ref"`
	Visibility string     `json:"visibility"`
	DataEnv    string     `json:"data_env"`
	Title      string     `json:"title"`
}

type AutofetchViewer struct {
	SourceID     int64  `json:"source_id"`
	PrincipalRef string `json:"principal_ref"`
	Label        string `json:"label"`
	CreatedAt    string `json:"created_at"`
}

type DatasetVersion struct {
	ID          int64      `json:"id"`
	ParkID      string     `json:"park_id"`
	DatasetType string     `json:"dataset_type"`
	Version     int64      `json:"version"`
	DataJson    string     `json:"data_json"`
	CreatedBy   *string    `json:"created_by"`
	CreatedAt   *time.Time `json:"created_at"`
	IsActive    *int64     `json:"is_active"`
}

type DeforestationEvent struct {
	ID                       int64      `json:"id"`
	ParkID                   string     `json:"park_id"`
	Year                     int64      `json:"year"`
	Lat                      float64    `json:"lat"`
	Lon                      float64    `json:"lon"`
	AreaKm2                  *float64   `json:"area_km2"`
	PatternType              *string    `json:"pattern_type"`
	Classification           *string    `json:"classification"`
	Narrative                *string    `json:"narrative"`
	PolygonIds               *string    `json:"polygon_ids"`
	ClassificationConfidence *float64   `json:"classification_confidence"`
	FiresSameYear            *int64     `json:"fires_same_year"`
	FireRatio                *float64   `json:"fire_ratio"`
	NearestSettlementKm      *float64   `json:"nearest_settlement_km"`
	ClassifiedAt             *time.Time `json:"classified_at"`
	PixelCount               *int64     `json:"pixel_count"`
	AreaMethod               *string    `json:"area_method"`
	NeedsReview              int64      `json:"needs_review"`
	CroplandFrac2019         *float64   `json:"cropland_frac_2019"`
	CroplandSource           *string    `json:"cropland_source"`
	CroplandConversionFrac   *float64   `json:"cropland_conversion_frac"`
	CroplandEventFrac2019    *float64   `json:"cropland_event_frac_2019"`
}

type EffortDatum struct {
	ID               int64    `json:"id"`
	GridCellID       string   `json:"grid_cell_id"`
	Year             int64    `json:"year"`
	Month            int64    `json:"month"`
	Day              *int64   `json:"day"`
	MovementType     string   `json:"movement_type"`
	TotalDistanceKm  float64  `json:"total_distance_km"`
	TotalPoints      int64    `json:"total_points"`
	UniqueUploads    int64    `json:"unique_uploads"`
	ProtectedAreaIds *string  `json:"protected_area_ids"`
	CoveragePercent  *float64 `json:"coverage_percent"`
	AvgSpeedKmh      *float64 `json:"avg_speed_kmh"`
	AvgAltitudeM     *float64 `json:"avg_altitude_m"`
	Env              string   `json:"env"`
}

type FeatureGeometry struct {
	ID             int64      `json:"id"`
	FeatureType    string     `json:"feature_type"`
	FeatureID      string     `json:"feature_id"`
	ParkID         string     `json:"park_id"`
	Geojson        string     `json:"geojson"`
	BboxMinx       *float64   `json:"bbox_minx"`
	BboxMiny       *float64   `json:"bbox_miny"`
	BboxMaxx       *float64   `json:"bbox_maxx"`
	BboxMaxy       *float64   `json:"bbox_maxy"`
	StartDate      *string    `json:"start_date"`
	EndDate        *string    `json:"end_date"`
	PropertiesJson *string    `json:"properties_json"`
	CreatedAt      *time.Time `json:"created_at"`
	StatValue      *float64   `json:"stat_value"`
	DistToParkKm   *float64   `json:"dist_to_park_km"`
	TrajDays       *string    `json:"traj_days"`
}

type FireDailyGrid struct {
	ID              int64    `json:"id"`
	GridCellID      string   `json:"grid_cell_id"`
	Date            string   `json:"date"`
	FireCount       int64    `json:"fire_count"`
	TotalFrp        *float64 `json:"total_frp"`
	AvgConfidence   *float64 `json:"avg_confidence"`
	InProtectedArea *int64   `json:"in_protected_area"`
	ProtectedAreaID *string  `json:"protected_area_id"`
}

type FireDataSync struct {
	ID              int64   `json:"id"`
	ParkID          string  `json:"park_id"`
	BboxWest        float64 `json:"bbox_west"`
	BboxSouth       float64 `json:"bbox_south"`
	BboxEast        float64 `json:"bbox_east"`
	BboxNorth       float64 `json:"bbox_north"`
	BufferKm        float64 `json:"buffer_km"`
	FirstDate       *string `json:"first_date"`
	LastDate        *string `json:"last_date"`
	LastSyncAt      *string `json:"last_sync_at"`
	TotalDetections *int64  `json:"total_detections"`
}

type FireDetection struct {
	ID              int64    `json:"id"`
	Latitude        float64  `json:"latitude"`
	Longitude       float64  `json:"longitude"`
	Brightness      *float64 `json:"brightness"`
	Scan            *float64 `json:"scan"`
	Track           *float64 `json:"track"`
	AcqDate         string   `json:"acq_date"`
	AcqTime         *string  `json:"acq_time"`
	Satellite       *string  `json:"satellite"`
	Instrument      *string  `json:"instrument"`
	Confidence      *string  `json:"confidence"`
	Version         *string  `json:"version"`
	BrightT31       *float64 `json:"bright_t31"`
	Frp             *float64 `json:"frp"`
	Daynight        *string  `json:"daynight"`
	GridCellID      *string  `json:"grid_cell_id"`
	InProtectedArea *int64   `json:"in_protected_area"`
	ProtectedAreaID *string  `json:"protected_area_id"`
}

type FireGroupAlert struct {
	ID                int64      `json:"id"`
	ParkID            string     `json:"park_id"`
	GroupName         string     `json:"group_name"`
	AlertType         string     `json:"alert_type"`
	FirstDetectedAt   time.Time  `json:"first_detected_at"`
	LastUpdatedAt     time.Time  `json:"last_updated_at"`
	LeftAt            *time.Time `json:"left_at"`
	FireCount         *int64     `json:"fire_count"`
	DaysActive        *int64     `json:"days_active"`
	CentroidLat       *float64   `json:"centroid_lat"`
	CentroidLon       *float64   `json:"centroid_lon"`
	LatestLat         *float64   `json:"latest_lat"`
	LatestLon         *float64   `json:"latest_lon"`
	MovementDirection *string    `json:"movement_direction"`
	IsDismissed       *bool      `json:"is_dismissed"`
	CreatedAt         *time.Time `json:"created_at"`
}

type FireSensorEpoch struct {
	Month       string `json:"month"`
	Sensors     string `json:"sensors"`
	SensorCount int64  `json:"sensor_count"`
	Detections  int64  `json:"detections"`
	ComputedAt  string `json:"computed_at"`
}

type GeopackageJob struct {
	ID             string  `json:"id"`
	CacheKey       string  `json:"cache_key"`
	AreaID         string  `json:"area_id"`
	AreaName       string  `json:"area_name"`
	IsAoi          int64   `json:"is_aoi"`
	PrincipalID    *int64  `json:"principal_id"`
	Env            string  `json:"env"`
	FromDate       string  `json:"from_date"`
	ToDate         string  `json:"to_date"`
	Effort         int64   `json:"effort"`
	State          string  `json:"state"`
	Progress       float64 `json:"progress"`
	Step           string  `json:"step"`
	FilePath       string  `json:"file_path"`
	SizeBytes      int64   `json:"size_bytes"`
	LayersJson     string  `json:"layers_json"`
	Error          string  `json:"error"`
	CreatedAt      string  `json:"created_at"`
	StartedAt      *string `json:"started_at"`
	FinishedAt     *string `json:"finished_at"`
	ExpiresAt      *string `json:"expires_at"`
	Downloads      int64   `json:"downloads"`
	LastDownloadAt *string `json:"last_download_at"`
	RawFire        int64   `json:"raw_fire"`
	ViewJson       string  `json:"view_json"`
}

type GhslDatum struct {
	ID              int64    `json:"id"`
	ParkID          string   `json:"park_id"`
	BuiltUpKm2      *float64 `json:"built_up_km2"`
	SettlementCount *int64   `json:"settlement_count"`
	AnalyzedAt      *string  `json:"analyzed_at"`
}

type GpxLearningQueue struct {
	ID           int64      `json:"id"`
	UploadID     *int64     `json:"upload_id"`
	ParkID       *string    `json:"park_id"`
	Status       *string    `json:"status"`
	ErrorMessage *string    `json:"error_message"`
	CreatedAt    *time.Time `json:"created_at"`
	StartedAt    *time.Time `json:"started_at"`
	CompletedAt  *time.Time `json:"completed_at"`
}

type GpxLearningResult struct {
	ID                    int64      `json:"id"`
	UploadID              *int64     `json:"upload_id"`
	ParkID                string     `json:"park_id"`
	ParkName              *string    `json:"park_name"`
	VehicleMedianSpeedKmh *float64   `json:"vehicle_median_speed_kmh"`
	VehicleMaxSpeedKmh    *float64   `json:"vehicle_max_speed_kmh"`
	FootMedianSpeedKmh    *float64   `json:"foot_median_speed_kmh"`
	FootMaxSpeedKmh       *float64   `json:"foot_max_speed_kmh"`
	FootMcpAreaKm2        *float64   `json:"foot_mcp_area_km2"`
	NewRoadsFound         *int64     `json:"new_roads_found"`
	NewRoadsKm            *float64   `json:"new_roads_km"`
	RoadConfidencePct     *float64   `json:"road_confidence_pct"`
	NewAirstripsFound     *int64     `json:"new_airstrips_found"`
	AirstripConfidencePct *float64   `json:"airstrip_confidence_pct"`
	NewPlacesFound        *int64     `json:"new_places_found"`
	PlaceTypesJson        *string    `json:"place_types_json"`
	PlaceConfidencePct    *float64   `json:"place_confidence_pct"`
	SummaryText           *string    `json:"summary_text"`
	DiscoveriesJson       *string    `json:"discoveries_json"`
	CreatedAt             *time.Time `json:"created_at"`
}

type GpxUpload struct {
	ID               int64      `json:"id"`
	UserID           string     `json:"user_id"`
	Filename         string     `json:"filename"`
	MovementType     string     `json:"movement_type"`
	ProtectedAreaID  *string    `json:"protected_area_id"`
	UploadDate       time.Time  `json:"upload_date"`
	StartTime        *time.Time `json:"start_time"`
	EndTime          *time.Time `json:"end_time"`
	TotalDistanceKm  float64    `json:"total_distance_km"`
	TotalPoints      int64      `json:"total_points"`
	FileHash         *string    `json:"file_hash"`
	ProcessingStatus *string    `json:"processing_status"`
	ErrorMessage     *string    `json:"error_message"`
	Env              string     `json:"env"`
}

type GpxUploadLog struct {
	ID                     int64     `json:"id"`
	UploadID               *int64    `json:"upload_id"`
	UserID                 string    `json:"user_id"`
	UserEmail              *string   `json:"user_email"`
	Filename               string    `json:"filename"`
	UploadTime             time.Time `json:"upload_time"`
	IsValid                bool      `json:"is_valid"`
	TotalPoints            int64     `json:"total_points"`
	ValidationErrors       *string   `json:"validation_errors"`
	ValidationWarnings     *string   `json:"validation_warnings"`
	ProtectedAreaID        *string   `json:"protected_area_id"`
	ProtectedAreaName      *string   `json:"protected_area_name"`
	PatrolKm               float64   `json:"patrol_km"`
	RoadKm                 float64   `json:"road_km"`
	BoundaryKm             float64   `json:"boundary_km"`
	ExcludedKm             float64   `json:"excluded_km"`
	TotalSegments          int64     `json:"total_segments"`
	PatrolSegments         int64     `json:"patrol_segments"`
	StaticSegments         int64     `json:"static_segments"`
	ExcludedSegments       int64     `json:"excluded_segments"`
	FootSegments           *int64    `json:"foot_segments"`
	FootKm                 *float64  `json:"foot_km"`
	FootMinutes            *float64  `json:"foot_minutes"`
	VehicleSegments        *int64    `json:"vehicle_segments"`
	VehicleKm              *float64  `json:"vehicle_km"`
	VehicleMinutes         *float64  `json:"vehicle_minutes"`
	AircraftSegments       *int64    `json:"aircraft_segments"`
	AircraftKm             *float64  `json:"aircraft_km"`
	AircraftMinutes        *float64  `json:"aircraft_minutes"`
	ReconSegments          *int64    `json:"recon_segments"`
	ReconKm                *float64  `json:"recon_km"`
	ReconMinutes           *float64  `json:"recon_minutes"`
	FastVehicleSegments    *int64    `json:"fast_vehicle_segments"`
	FastVehicleKm          *float64  `json:"fast_vehicle_km"`
	FastVehicleMinutes     *float64  `json:"fast_vehicle_minutes"`
	TransitSegments        *int64    `json:"transit_segments"`
	TransitKm              *float64  `json:"transit_km"`
	LogisticsSegments      *int64    `json:"logistics_segments"`
	LogisticsKm            *float64  `json:"logistics_km"`
	ClassifiedSegmentsJson *string   `json:"classified_segments_json"`
	ProcessingStatus       *string   `json:"processing_status"`
	RejectionReason        *string   `json:"rejection_reason"`
	BoatSegments           *int64    `json:"boat_segments"`
	BoatKm                 *float64  `json:"boat_km"`
	BoatMinutes            *float64  `json:"boat_minutes"`
	FixedWingSegments      *int64    `json:"fixed_wing_segments"`
	FixedWingKm            *float64  `json:"fixed_wing_km"`
	FixedWingMinutes       *float64  `json:"fixed_wing_minutes"`
	RotorWingSegments      *int64    `json:"rotor_wing_segments"`
	RotorWingKm            *float64  `json:"rotor_wing_km"`
	RotorWingMinutes       *float64  `json:"rotor_wing_minutes"`
	Env                    string    `json:"env"`
}

type GridCell struct {
	ID        string  `json:"id"`
	LatCenter float64 `json:"lat_center"`
	LonCenter float64 `json:"lon_center"`
	LatMin    float64 `json:"lat_min"`
	LatMax    float64 `json:"lat_max"`
	LonMin    float64 `json:"lon_min"`
	LonMax    float64 `json:"lon_max"`
}

type HttpCache struct {
	Url       string     `json:"url"`
	Status    *int64     `json:"status"`
	Body      []byte     `json:"body"`
	FetchedAt *time.Time `json:"fetched_at"`
}

type LearnedAirstrip struct {
	ID            int64      `json:"id"`
	ParkID        string     `json:"park_id"`
	Lat           float64    `json:"lat"`
	Lon           float64    `json:"lon"`
	HeadingDeg    *float64   `json:"heading_deg"`
	LengthM       *float64   `json:"length_m"`
	AircraftType  *string    `json:"aircraft_type"`
	LandingCount  *int64     `json:"landing_count"`
	TakeoffCount  *int64     `json:"takeoff_count"`
	ConfidencePct *float64   `json:"confidence_pct"`
	Status        *string    `json:"status"`
	ApprovedBy    *string    `json:"approved_by"`
	ApprovedAt    *time.Time `json:"approved_at"`
	ApproachJson  *string    `json:"approach_json"`
	CreatedAt     *time.Time `json:"created_at"`
	UpdatedAt     *time.Time `json:"updated_at"`
}

type LearnedAirstripsHistory struct {
	HistoryID    int64      `json:"history_id"`
	OriginalID   int64      `json:"original_id"`
	ParkID       string     `json:"park_id"`
	Lat          float64    `json:"lat"`
	Lon          float64    `json:"lon"`
	HeadingDeg   *float64   `json:"heading_deg"`
	LengthM      *float64   `json:"length_m"`
	AircraftType *string    `json:"aircraft_type"`
	LandingCount *int64     `json:"landing_count"`
	Confidence   *float64   `json:"confidence"`
	IsApproved   *int64     `json:"is_approved"`
	IsRejected   *int64     `json:"is_rejected"`
	Version      int64      `json:"version"`
	Action       string     `json:"action"`
	ActionBy     *string    `json:"action_by"`
	ActionAt     *time.Time `json:"action_at"`
}

type LearnedPlace struct {
	ID                 int64      `json:"id"`
	ParkID             string     `json:"park_id"`
	Lat                float64    `json:"lat"`
	Lon                float64    `json:"lon"`
	PlaceType          *string    `json:"place_type"`
	Name               *string    `json:"name"`
	VisitCount         *int64     `json:"visit_count"`
	AvgDurationMinutes *float64   `json:"avg_duration_minutes"`
	ConfidencePct      *float64   `json:"confidence_pct"`
	Status             *string    `json:"status"`
	ApprovedBy         *string    `json:"approved_by"`
	ApprovedAt         *time.Time `json:"approved_at"`
	CreatedAt          *time.Time `json:"created_at"`
	UpdatedAt          *time.Time `json:"updated_at"`
}

type LearnedPlacesHistory struct {
	HistoryID          int64      `json:"history_id"`
	OriginalID         int64      `json:"original_id"`
	ParkID             string     `json:"park_id"`
	Lat                float64    `json:"lat"`
	Lon                float64    `json:"lon"`
	PlaceType          *string    `json:"place_type"`
	VisitCount         *int64     `json:"visit_count"`
	AvgDurationMinutes *float64   `json:"avg_duration_minutes"`
	Confidence         *float64   `json:"confidence"`
	IsApproved         *int64     `json:"is_approved"`
	IsRejected         *int64     `json:"is_rejected"`
	Version            int64      `json:"version"`
	Action             string     `json:"action"`
	ActionBy           *string    `json:"action_by"`
	ActionAt           *time.Time `json:"action_at"`
}

type LearnedRoad struct {
	ID            int64      `json:"id"`
	ParkID        string     `json:"park_id"`
	Geojson       string     `json:"geojson"`
	LengthM       *float64   `json:"length_m"`
	MatchCount    *int64     `json:"match_count"`
	ConfidencePct *float64   `json:"confidence_pct"`
	Status        *string    `json:"status"`
	ApprovedBy    *string    `json:"approved_by"`
	ApprovedAt    *time.Time `json:"approved_at"`
	CreatedAt     *time.Time `json:"created_at"`
	UpdatedAt     *time.Time `json:"updated_at"`
}

type LearnedRoadsHistory struct {
	HistoryID  int64      `json:"history_id"`
	OriginalID int64      `json:"original_id"`
	ParkID     string     `json:"park_id"`
	Geojson    string     `json:"geojson"`
	DistanceKm *float64   `json:"distance_km"`
	MatchCount *int64     `json:"match_count"`
	Confidence *float64   `json:"confidence"`
	IsApproved *int64     `json:"is_approved"`
	IsRejected *int64     `json:"is_rejected"`
	Version    int64      `json:"version"`
	Action     string     `json:"action"`
	ActionBy   *string    `json:"action_by"`
	ActionAt   *time.Time `json:"action_at"`
}

type MapPref struct {
	PwdRef           string  `json:"pwd_ref"`
	DefaultBase      *string `json:"default_base"`
	DefaultSatellite *string `json:"default_satellite"`
	UpdatedAt        string  `json:"updated_at"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type NarrativeCache struct {
	ParkID     string `json:"park_id"`
	Kind       string `json:"kind"`
	Params     string `json:"params"`
	Payload    string `json:"payload"`
	SourceRev  string `json:"source_rev"`
	ComputedAt string `json:"computed_at"`
}

type Notification struct {
	ID               int64      `json:"id"`
	ParkID           string     `json:"park_id"`
	NotificationType string     `json:"notification_type"`
	Title            string     `json:"title"`
	Message          *string    `json:"message"`
	ReferenceID      *string    `json:"reference_id"`
	ReferenceUrl     *string    `json:"reference_url"`
	IsRead           *int64     `json:"is_read"`
	CreatedAt        *time.Time `json:"created_at"`
	Env              string     `json:"env"`
}

type OsmRoadlessDatum struct {
	ID                 int64    `json:"id"`
	ParkID             string   `json:"park_id"`
	RoadlessPercentage *float64 `json:"roadless_percentage"`
	TotalRoadKm        *float64 `json:"total_road_km"`
	AnalyzedAt         *string  `json:"analyzed_at"`
}

type PaPublication struct {
	ID           int64     `json:"id"`
	PaID         string    `json:"pa_id"`
	OpenalexID   string    `json:"openalex_id"`
	Title        string    `json:"title"`
	Authors      *string   `json:"authors"`
	Year         *int64    `json:"year"`
	Doi          *string   `json:"doi"`
	Url          *string   `json:"url"`
	Abstract     *string   `json:"abstract"`
	CitedByCount *int64    `json:"cited_by_count"`
	CreatedAt    time.Time `json:"created_at"`
}

type PaPublicationSync struct {
	PaID        string    `json:"pa_id"`
	LastSync    time.Time `json:"last_sync"`
	ResultCount int64     `json:"result_count"`
}

type ParkBasin struct {
	ParkID    string     `json:"park_id"`
	Kind      string     `json:"kind"`
	OutletLat float64    `json:"outlet_lat"`
	OutletLon float64    `json:"outlet_lon"`
	AreaKm2   *float64   `json:"area_km2"`
	LengthKm  *float64   `json:"length_km"`
	Geojson   string     `json:"geojson"`
	Source    string     `json:"source"`
	Meta      *string    `json:"meta"`
	FetchedAt *time.Time `json:"fetched_at"`
}

type ParkBasinPart struct {
	ParkID    string     `json:"park_id"`
	Kind      string     `json:"kind"`
	Idx       int64      `json:"idx"`
	OutletLat float64    `json:"outlet_lat"`
	OutletLon float64    `json:"outlet_lon"`
	River     *string    `json:"river"`
	AreaKm2   *float64   `json:"area_km2"`
	LengthKm  *float64   `json:"length_km"`
	Geojson   string     `json:"geojson"`
	Source    string     `json:"source"`
	Meta      *string    `json:"meta"`
	FetchedAt *time.Time `json:"fetched_at"`
}

type ParkBasinRiver struct {
	ParkID      string   `json:"park_id"`
	Comid       int64    `json:"comid"`
	StreamOrder *int64   `json:"stream_order"`
	LengthKm    *float64 `json:"length_km"`
	Geojson     string   `json:"geojson"`
}

type ParkChecklist struct {
	ID          int64      `json:"id"`
	PaID        string     `json:"pa_id"`
	ItemID      string     `json:"item_id"`
	Status      string     `json:"status"`
	Notes       *string    `json:"notes"`
	DocumentUrl *string    `json:"document_url"`
	UpdatedBy   *string    `json:"updated_by"`
	UpdatedAt   *time.Time `json:"updated_at"`
}

type ParkDocument struct {
	ID          int64      `json:"id"`
	PaID        string     `json:"pa_id"`
	Category    string     `json:"category"`
	ItemID      *string    `json:"item_id"`
	Title       string     `json:"title"`
	Description *string    `json:"description"`
	FileUrl     *string    `json:"file_url"`
	FileType    *string    `json:"file_type"`
	UploadedBy  *string    `json:"uploaded_by"`
	UploadedAt  *time.Time `json:"uploaded_at"`
	Year        *int64     `json:"year"`
	Summary     *string    `json:"summary"`
}

type ParkFireAnalysis struct {
	ID                     int64    `json:"id"`
	ParkID                 string   `json:"park_id"`
	AnalyzedAt             *string  `json:"analyzed_at"`
	TotalFires             *int64   `json:"total_fires"`
	TotalInfractions       *int64   `json:"total_infractions"`
	InfractionRate         *float64 `json:"infraction_rate"`
	PeakInfractionDay      *string  `json:"peak_infraction_day"`
	PeakInfractionCount    *int64   `json:"peak_infraction_count"`
	NetSouthKm             *float64 `json:"net_south_km"`
	AvgDailyMovementKm     *float64 `json:"avg_daily_movement_km"`
	MonthlyStatsJson       *string  `json:"monthly_stats_json"`
	GroupsStoppedInside    *int64   `json:"groups_stopped_inside"`
	GroupsTransitedThrough *int64   `json:"groups_transited_through"`
}

type ParkGroupInfraction struct {
	ID                  int64    `json:"id"`
	ParkID              string   `json:"park_id"`
	Year                int64    `json:"year"`
	TotalGroups         *int64   `json:"total_groups"`
	GroupsStoppedInside *int64   `json:"groups_stopped_inside"`
	GroupsTransited     *int64   `json:"groups_transited"`
	AvgDaysBurning      *float64 `json:"avg_days_burning"`
	AnalyzedAt          *string  `json:"analyzed_at"`
}

type ParkOnboardingRequest struct {
	ID          int64      `json:"id"`
	WdpaID      int64      `json:"wdpa_id"`
	Name        string     `json:"name"`
	Country     *string    `json:"country"`
	CountryCode *string    `json:"country_code"`
	ParkID      *string    `json:"park_id"`
	Status      string     `json:"status"`
	Detail      *string    `json:"detail"`
	Env         string     `json:"env"`
	RequestedAt *time.Time `json:"requested_at"`
	ProcessedAt *time.Time `json:"processed_at"`
}

type ParkOnboardingSubscriber struct {
	RequestID   int64      `json:"request_id"`
	PwdRef      string     `json:"pwd_ref"`
	Env         string     `json:"env"`
	RequestedAt *time.Time `json:"requested_at"`
}

type ParkPatrolMcp struct {
	ID           int64      `json:"id"`
	ParkID       string     `json:"park_id"`
	Mcp90Geojson *string    `json:"mcp_90_geojson"`
	McpAreaKm2   *float64   `json:"mcp_area_km2"`
	CentroidLat  *float64   `json:"centroid_lat"`
	CentroidLon  *float64   `json:"centroid_lon"`
	PointCount   *int64     `json:"point_count"`
	UpdatedAt    *time.Time `json:"updated_at"`
}

type ParkSettlement struct {
	ID                       int64      `json:"id"`
	ParkID                   string     `json:"park_id"`
	Lat                      float64    `json:"lat"`
	Lon                      float64    `json:"lon"`
	AreaM2                   *float64   `json:"area_m2"`
	PopulationEst            *int64     `json:"population_est"`
	HouseholdsEst            *int64     `json:"households_est"`
	NearestPlace             *string    `json:"nearest_place"`
	DistanceToPlaceKm        *float64   `json:"distance_to_place_km"`
	DirectionFromPlace       *string    `json:"direction_from_place"`
	SettlementType           *string    `json:"settlement_type"`
	InBuffer                 *int64     `json:"in_buffer"`
	TileRow                  *int64     `json:"tile_row"`
	TileCol                  *int64     `json:"tile_col"`
	DetectedAt               *time.Time `json:"detected_at"`
	Classification           *string    `json:"classification"`
	ClassificationConfidence *float64   `json:"classification_confidence"`
	Narrative                *string    `json:"narrative"`
	PolygonIds               *string    `json:"polygon_ids"`
	Fires1km                 *int64     `json:"fires_1km"`
	Fires5km                 *int64     `json:"fires_5km"`
	FireSeasonality          *string    `json:"fire_seasonality"`
	DeforestNearbyKm2        *float64   `json:"deforest_nearby_km2"`
	ClassifiedAt             *time.Time `json:"classified_at"`
	ExtentM2                 *float64   `json:"extent_m2"`
	AreaSource               *string    `json:"area_source"`
	PopulationSource         *string    `json:"population_source"`
	Epoch                    *string    `json:"epoch"`
	FireContextAt            *time.Time `json:"fire_context_at"`
	Persistence              *string    `json:"persistence"`
	PersistenceSource        *string    `json:"persistence_source"`
	SurfaceE2000M2           *float64   `json:"surface_e2000_m2"`
	SurfaceE2015M2           *float64   `json:"surface_e2015_m2"`
	CroplandFrac2019         *float64   `json:"cropland_frac_2019"`
	CroplandFrac2003         *float64   `json:"cropland_frac_2003"`
	CroplandSource           *string    `json:"cropland_source"`
}

type ParkVehicleStat struct {
	ID              int64      `json:"id"`
	ParkID          string     `json:"park_id"`
	MovementType    string     `json:"movement_type"`
	TotalDistanceKm *float64   `json:"total_distance_km"`
	TotalTimeHours  *float64   `json:"total_time_hours"`
	MedianSpeedKmh  *float64   `json:"median_speed_kmh"`
	MaxSpeedKmh     *float64   `json:"max_speed_kmh"`
	P90SpeedKmh     *float64   `json:"p90_speed_kmh"`
	SampleCount     *int64     `json:"sample_count"`
	UpdatedAt       *time.Time `json:"updated_at"`
}

type Principal struct {
	ID        int64      `json:"id"`
	Kind      string     `json:"kind"`
	Ref       string     `json:"ref"`
	Label     *string    `json:"label"`
	CreatedAt *time.Time `json:"created_at"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type SettlementIntensity struct {
	ID                   int64      `json:"id"`
	SettlementID         int64      `json:"settlement_id"`
	ParkID               string     `json:"park_id"`
	Year                 int64      `json:"year"`
	Month                *int64     `json:"month"`
	TotalVisits          int64      `json:"total_visits"`
	TotalDurationMinutes float64    `json:"total_duration_minutes"`
	UniqueUploads        int64      `json:"unique_uploads"`
	FootVisits           *int64     `json:"foot_visits"`
	VehicleVisits        *int64     `json:"vehicle_visits"`
	AircraftVisits       *int64     `json:"aircraft_visits"`
	IsLikelyBase         *int64     `json:"is_likely_base"`
	UpdatedAt            *time.Time `json:"updated_at"`
}

type SettlementVisit struct {
	ID              int64      `json:"id"`
	SettlementID    int64      `json:"settlement_id"`
	UploadID        *int64     `json:"upload_id"`
	ParkID          string     `json:"park_id"`
	VisitDate       time.Time  `json:"visit_date"`
	VisitStart      *time.Time `json:"visit_start"`
	VisitEnd        *time.Time `json:"visit_end"`
	DurationMinutes float64    `json:"duration_minutes"`
	MovementType    string     `json:"movement_type"`
	ArrivingFrom    *string    `json:"arriving_from"`
	DepartingTo     *string    `json:"departing_to"`
	Year            int64      `json:"year"`
	Month           int64      `json:"month"`
	CreatedAt       *time.Time `json:"created_at"`
}

type SharedFile struct {
	ID             string  `json:"id"`
	PwdRef         string  `json:"pwd_ref"`
	Env            string  `json:"env"`
	Name           string  `json:"name"`
	SizeBytes      int64   `json:"size_bytes"`
	CreatedAt      string  `json:"created_at"`
	ExpiresAt      string  `json:"expires_at"`
	Downloads      int64   `json:"downloads"`
	LastDownloadAt *string `json:"last_download_at"`
	Enc            int64   `json:"enc"`
	Nonce          []byte  `json:"nonce"`
	MaxDownloads   int64   `json:"max_downloads"`
	Kind           string  `json:"kind"`
	Private        int64   `json:"private"`
}

type ShortLink struct {
	Slug        string  `json:"slug"`
	Url         string  `json:"url"`
	AliasOf     *string `json:"alias_of"`
	Kind        string  `json:"kind"`
	Title       string  `json:"title"`
	Env         string  `json:"env"`
	PwdRef      string  `json:"pwd_ref"`
	Guest       int64   `json:"guest"`
	PrincipalID *int64  `json:"principal_id"`
	ExpiresAt   *string `json:"expires_at"`
	RevokedAt   *string `json:"revoked_at"`
	CreatedAt   string  `json:"created_at"`
	Hits        int64   `json:"hits"`
	LastHitAt   *string `json:"last_hit_at"`
	Scope       string  `json:"scope"`
	DateFrom    string  `json:"date_from"`
	DateTo      string  `json:"date_to"`
}

type ShortLinkTag struct {
	Slug      string `json:"slug"`
	Tag       string `json:"tag"`
	CreatedAt string `json:"created_at"`
}

type SubcellVisit struct {
	ID         int64     `json:"id"`
	GridCellID string    `json:"grid_cell_id"`
	SubcellID  string    `json:"subcell_id"`
	VisitDate  time.Time `json:"visit_date"`
	VisitCount int64     `json:"visit_count"`
	Env        string    `json:"env"`
}

type TileSource struct {
	ID          string  `json:"id"`
	PwdRef      string  `json:"pwd_ref"`
	Name        string  `json:"name"`
	UrlEnc      []byte  `json:"url_enc"`
	Host        string  `json:"host"`
	Scheme      string  `json:"scheme"`
	MinZoom     int64   `json:"min_zoom"`
	MaxZoom     int64   `json:"max_zoom"`
	TileSize    int64   `json:"tile_size"`
	Attribution string  `json:"attribution"`
	Kind        string  `json:"kind"`
	VerifiedAt  *string `json:"verified_at"`
	ProbeBytes  int64   `json:"probe_bytes"`
	CreatedAt   string  `json:"created_at"`
}

type TrackPoint struct {
	ID           int64      `json:"id"`
	UploadID     int64      `json:"upload_id"`
	Lat          float64    `json:"lat"`
	Lon          float64    `json:"lon"`
	Elevation    *float64   `json:"elevation"`
	Timestamp    *time.Time `json:"timestamp"`
	GridCellID   *string    `json:"grid_cell_id"`
	MovementType *string    `json:"movement_type"`
	Env          string     `json:"env"`
}

type UploadQueue struct {
	ID             int64      `json:"id"`
	UserID         string     `json:"user_id"`
	UserEmail      string     `json:"user_email"`
	Filename       string     `json:"filename"`
	FileHash       *string    `json:"file_hash"`
	FileContent    []byte     `json:"file_content"`
	Status         string     `json:"status"`
	ErrorMessage   *string    `json:"error_message"`
	CreatedAt      *time.Time `json:"created_at"`
	StartedAt      *time.Time `json:"started_at"`
	CompletedAt    *time.Time `json:"completed_at"`
	ResultUploadID *int64     `json:"result_upload_id"`
	ResultJson     *string    `json:"result_json"`
	Env            string     `json:"env"`
}

type User struct {
	ID               string     `json:"id"`
	Email            string     `json:"email"`
	Name             string     `json:"name"`
	Organization     string     `json:"organization"`
	OrganizationType string     `json:"organization_type"`
	Role             string     `json:"role"`
	CreatedAt        time.Time  `json:"created_at"`
	ApprovedAt       *time.Time `json:"approved_at"`
	ApprovedBy       *string    `json:"approved_by"`
	PasswordHash     string     `json:"password_hash"`
}

type VehicleTrack struct {
	ID           int64      `json:"id"`
	ParkID       string     `json:"park_id"`
	UploadID     *int64     `json:"upload_id"`
	Geojson      string     `json:"geojson"`
	LengthM      *float64   `json:"length_m"`
	MovementType *string    `json:"movement_type"`
	CreatedAt    *time.Time `json:"created_at"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
