// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package dbgen

import (
	"context"
)

const deleteOldNotifications = `-- name: DeleteOldNotifications :exec
DELETE FROM notifications WHERE created_at < datetime('now', '-30 days') AND is_read = 1
`

func (q *Queries) DeleteOldNotifications(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOldNotifications)
	return err
}

const getNotificationsByPark = `-- name: GetNotificationsByPark :many
SELECT id, park_id, notification_type, title, message, reference_id, reference_url, is_read, created_at, env FROM notifications 
WHERE park_id = ? 
ORDER BY created_at DESC 
LIMIT ?
`

type GetNotificationsByParkParams struct {
	ParkID string `json:"park_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) GetNotificationsByPark(ctx context.Context, arg GetNotificationsByParkParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsByPark, arg.ParkID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.ParkID,
			&i.NotificationType,
			&i.Title,
			&i.Message,
			&i.ReferenceID,
			&i.ReferenceUrl,
			&i.IsRead,
			&i.CreatedAt,
			&i.Env,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationsByType = `-- name: GetNotificationsByType :many
SELECT id, park_id, notification_type, title, message, reference_id, reference_url, is_read, created_at, env FROM notifications 
WHERE notification_type = ? 
ORDER BY created_at DESC 
LIMIT ?
`

type GetNotificationsByTypeParams struct {
	NotificationType string `json:"notification_type"`
	Limit            int64  `json:"limit"`
}

func (q *Queries) GetNotificationsByType(ctx context.Context, arg GetNotificationsByTypeParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsByType, arg.NotificationType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.ParkID,
			&i.NotificationType,
			&i.Title,
			&i.Message,
			&i.ReferenceID,
			&i.ReferenceUrl,
			&i.IsRead,
			&i.CreatedAt,
			&i.Env,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadNotificationCount = `-- name: GetUnreadNotificationCount :one
SELECT COUNT(*) as count FROM notifications WHERE is_read = 0
`

func (q *Queries) GetUnreadNotificationCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUnreadNotificationCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUnreadNotifications = `-- name: GetUnreadNotifications :many
SELECT id, park_id, notification_type, title, message, reference_id, reference_url, is_read, created_at, env FROM notifications 
WHERE is_read = 0 
ORDER BY created_at DESC 
LIMIT ?
`

func (q *Queries) GetUnreadNotifications(ctx context.Context, limit int64) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getUnreadNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.ParkID,
			&i.NotificationType,
			&i.Title,
			&i.Message,
			&i.ReferenceID,
			&i.ReferenceUrl,
			&i.IsRead,
			&i.CreatedAt,
			&i.Env,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (park_id, notification_type, title, message, reference_id, reference_url)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertNotificationParams struct {
	ParkID           string  `json:"park_id"`
	NotificationType string  `json:"notification_type"`
	Title            string  `json:"title"`
	Message          *string `json:"message"`
	ReferenceID      *string `json:"reference_id"`
	ReferenceUrl     *string `json:"reference_url"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertNotification,
		arg.ParkID,
		arg.NotificationType,
		arg.Title,
		arg.Message,
		arg.ReferenceID,
		arg.ReferenceUrl,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET is_read = 1 WHERE is_read = 0
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET is_read = 1 WHERE id = ?
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markNotificationRead, id)
	return err
}
