// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: publications.sql

package dbgen

import (
	"context"
)

const getAllSyncedPAIDs = `-- name: GetAllSyncedPAIDs :many
SELECT pa_id FROM pa_publication_sync
`

func (q *Queries) GetAllSyncedPAIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllSyncedPAIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var pa_id string
		if err := rows.Scan(&pa_id); err != nil {
			return nil, err
		}
		items = append(items, pa_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPAPublicationSync = `-- name: GetPAPublicationSync :one
SELECT pa_id, last_sync, result_count FROM pa_publication_sync WHERE pa_id = ?
`

func (q *Queries) GetPAPublicationSync(ctx context.Context, paID string) (PaPublicationSync, error) {
	row := q.db.QueryRowContext(ctx, getPAPublicationSync, paID)
	var i PaPublicationSync
	err := row.Scan(&i.PaID, &i.LastSync, &i.ResultCount)
	return i, err
}

const getPAsNeedingPublicationSync = `-- name: GetPAsNeedingPublicationSync :many
SELECT pa_id FROM pa_publication_sync 
WHERE last_sync < datetime('now', '-7 days')
ORDER BY last_sync ASC
LIMIT ?
`

func (q *Queries) GetPAsNeedingPublicationSync(ctx context.Context, limit int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getPAsNeedingPublicationSync, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var pa_id string
		if err := rows.Scan(&pa_id); err != nil {
			return nil, err
		}
		items = append(items, pa_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicationCountByPA = `-- name: GetPublicationCountByPA :one
SELECT COUNT(*) as count FROM pa_publications WHERE pa_id = ?
`

func (q *Queries) GetPublicationCountByPA(ctx context.Context, paID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPublicationCountByPA, paID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPublicationsByPA = `-- name: GetPublicationsByPA :many
SELECT id, pa_id, openalex_id, title, authors, year, doi, url, abstract, cited_by_count, created_at FROM pa_publications WHERE pa_id = ? ORDER BY year DESC, cited_by_count DESC LIMIT 50
`

func (q *Queries) GetPublicationsByPA(ctx context.Context, paID string) ([]PaPublication, error) {
	rows, err := q.db.QueryContext(ctx, getPublicationsByPA, paID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaPublication{}
	for rows.Next() {
		var i PaPublication
		if err := rows.Scan(
			&i.ID,
			&i.PaID,
			&i.OpenalexID,
			&i.Title,
			&i.Authors,
			&i.Year,
			&i.Doi,
			&i.Url,
			&i.Abstract,
			&i.CitedByCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPublication = `-- name: InsertPublication :exec
INSERT OR IGNORE INTO pa_publications (pa_id, openalex_id, title, authors, year, doi, url, abstract, cited_by_count)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPublicationParams struct {
	PaID         string  `json:"pa_id"`
	OpenalexID   string  `json:"openalex_id"`
	Title        string  `json:"title"`
	Authors      *string `json:"authors"`
	Year         *int64  `json:"year"`
	Doi          *string `json:"doi"`
	Url          *string `json:"url"`
	Abstract     *string `json:"abstract"`
	CitedByCount *int64  `json:"cited_by_count"`
}

func (q *Queries) InsertPublication(ctx context.Context, arg InsertPublicationParams) error {
	_, err := q.db.ExecContext(ctx, insertPublication,
		arg.PaID,
		arg.OpenalexID,
		arg.Title,
		arg.Authors,
		arg.Year,
		arg.Doi,
		arg.Url,
		arg.Abstract,
		arg.CitedByCount,
	)
	return err
}

const upsertPAPublicationSync = `-- name: UpsertPAPublicationSync :exec
INSERT INTO pa_publication_sync (pa_id, last_sync, result_count)
VALUES (?, CURRENT_TIMESTAMP, ?)
ON CONFLICT(pa_id) DO UPDATE SET last_sync = CURRENT_TIMESTAMP, result_count = excluded.result_count
`

type UpsertPAPublicationSyncParams struct {
	PaID        string `json:"pa_id"`
	ResultCount int64  `json:"result_count"`
}

func (q *Queries) UpsertPAPublicationSync(ctx context.Context, arg UpsertPAPublicationSyncParams) error {
	_, err := q.db.ExecContext(ctx, upsertPAPublicationSync, arg.PaID, arg.ResultCount)
	return err
}
