// Package srv provides GPX validation and classification for conservation patrol tracking.
package srv

import (
	"encoding/json"
	"fmt"
	"math"
	"time"

	"srv.exe.dev/srv/gpx"
)

// GPXValidationResult contains the results of GPX file validation and classification
type GPXValidationResult struct {
	IsValid            bool                `json:"is_valid"`
	TotalPoints        int                 `json:"total_points"`
	ValidationErrors   []string            `json:"validation_errors,omitempty"`
	ValidationWarnings []string            `json:"validation_warnings,omitempty"`

	// Classification
	ClassifiedSegments []ClassifiedSegment `json:"classified_segments"`

	// Stats for user feedback
	PatrolKm         float64 `json:"patrol_km"`
	RoadKm           float64 `json:"road_km"`
	BoundaryKm       float64 `json:"boundary_km"`
	StaticSegments   int     `json:"static_segments"`
	ExcludedSegments int     `json:"excluded_segments"`
	ExcludedKm       float64 `json:"excluded_km"`

	// Protected area detection
	ProtectedAreaID   string `json:"protected_area_id,omitempty"`
	ProtectedAreaName string `json:"protected_area_name,omitempty"`
}

// ClassifiedSegment represents a classified portion of a GPX track
type ClassifiedSegment struct {
	Classification  string        `json:"classification"` // patrol, boundary, road, poi, static, auto_generated
	MovementType    string        `json:"movement_type,omitempty"` // foot, vehicle, aircraft
	StartIndex      int           `json:"start_index"`
	EndIndex        int           `json:"end_index"`
	DistanceKm      float64       `json:"distance_km"`
	Duration        time.Duration `json:"-"`
	DurationStr     string        `json:"duration,omitempty"`
	AvgSpeedKmh     float64       `json:"avg_speed_kmh,omitempty"`
	Reason          string        `json:"reason"`
	IncludeInEffort bool          `json:"include_in_effort"`
	GeoJSON         string        `json:"geojson,omitempty"`
	Points          []gpx.Point   `json:"-"` // For internal processing
}

// MinimumWaypoints is the minimum required waypoints for a valid GPX file
const MinimumWaypoints = 10

// ValidateAndClassifyGPX validates a GPX file and classifies its segments
func ValidateAndClassifyGPX(data *gpx.GPXData) *GPXValidationResult {
	result := &GPXValidationResult{
		IsValid:            true,
		ClassifiedSegments: []ClassifiedSegment{},
	}

	// Count total points
	for _, track := range data.Tracks {
		for _, seg := range track.Segments {
			result.TotalPoints += len(seg)
		}
	}

	// Validation: minimum points
	if result.TotalPoints < MinimumWaypoints {
		result.IsValid = false
		result.ValidationErrors = append(result.ValidationErrors,
			fmt.Sprintf("Insufficient waypoints: %d (minimum %d required)", result.TotalPoints, MinimumWaypoints))
		return result
	}

	// Split GPX data into time-bounded segments (30 min max) to avoid
	// treating multi-day tracks as single segments with unrealistic distances
	timeSegments := gpx.SplitIntoSegments(data, 0)

	// Process each time-bounded segment
	for _, timeSeg := range timeSegments {
		seg := timeSeg.Points
		if len(seg) < 2 {
			continue
		}

		// Check for auto-generated patterns
		if isAutoGenerated(seg) {
			classified := ClassifiedSegment{
				Classification:  "auto_generated",
				StartIndex:      0,
				EndIndex:        len(seg) - 1,
				DistanceKm:      calculateSegmentDistance(seg),
				Reason:          "Detected systematic pattern (regular intervals or grid coordinates)",
				IncludeInEffort: false,
			}
			result.ClassifiedSegments = append(result.ClassifiedSegments, classified)
			result.ExcludedSegments++
			result.ExcludedKm += classified.DistanceKm
			result.ValidationWarnings = append(result.ValidationWarnings,
				"Segment detected as auto-generated and excluded from effort mapping")
			continue
		}

		// Check for static segments
		staticSegs := detectStaticSegments(seg)
		if len(staticSegs) > 0 {
			for _, ss := range staticSegs {
				result.ClassifiedSegments = append(result.ClassifiedSegments, ss)
				result.StaticSegments++
				result.ExcludedKm += ss.DistanceKm
			}
		}

		// Check for boundary traces
		if isBoundaryTrace(seg) {
			classified := ClassifiedSegment{
				Classification:  "boundary",
				StartIndex:      0,
				EndIndex:        len(seg) - 1,
				DistanceKm:      calculateSegmentDistance(seg),
				Reason:          "Detected as boundary trace (closed polygon)",
				IncludeInEffort: false,
				GeoJSON:         pointsToGeoJSON(seg),
			}
			result.ClassifiedSegments = append(result.ClassifiedSegments, classified)
			result.BoundaryKm += classified.DistanceKm
			continue
		}

		// Check for road traces
		if isRoadTrace(seg) {
			classified := ClassifiedSegment{
				Classification:  "road",
				StartIndex:      0,
				EndIndex:        len(seg) - 1,
				DistanceKm:      calculateSegmentDistance(seg),
				Reason:          "Detected as road trace (high bearing consistency)",
				IncludeInEffort: false,
				GeoJSON:         pointsToGeoJSON(seg),
			}
			result.ClassifiedSegments = append(result.ClassifiedSegments, classified)
			result.RoadKm += classified.DistanceKm
			continue
		}

		// Determine movement type from speed
		movementType := "foot"
		avgSpeed := 0.0
		if len(seg) >= 2 {
			tempSeg := gpx.Segment{Points: seg}
			avgSpeed = gpx.CalculateSpeed(seg)
			tempSeg.AvgSpeedKmh = avgSpeed
			movementType = gpx.ClassifyMovementType(tempSeg)
		}

		distanceKm := calculateSegmentDistance(seg)
		
		// Aircraft movements are not counted as patrol effort
		// They are logged separately as transfer/logistics
		if movementType == "aircraft" {
			classified := ClassifiedSegment{
				Classification:  "aircraft",
				MovementType:    "aircraft",
				StartIndex:      0,
				EndIndex:        len(seg) - 1,
				DistanceKm:      distanceKm,
				AvgSpeedKmh:     avgSpeed,
				Reason:          fmt.Sprintf("Aircraft movement (avg %.0f km/h)", avgSpeed),
				IncludeInEffort: false,
				Points:          seg,
			}
			if len(seg) > 0 && seg[0].Time != nil && seg[len(seg)-1].Time != nil {
				duration := seg[len(seg)-1].Time.Sub(*seg[0].Time)
				classified.Duration = duration
				classified.DurationStr = formatDuration(duration)
			}
			result.ClassifiedSegments = append(result.ClassifiedSegments, classified)
			result.ExcludedKm += distanceKm
			continue
		}

		// Valid patrol track (foot or vehicle)
		classified := ClassifiedSegment{
			Classification:  "patrol",
			MovementType:    movementType,
			StartIndex:      0,
			EndIndex:        len(seg) - 1,
			DistanceKm:      distanceKm,
			AvgSpeedKmh:     avgSpeed,
			Reason:          "Valid patrol track",
			IncludeInEffort: true,
			Points:          seg,
		}
		if len(seg) > 0 && seg[0].Time != nil && seg[len(seg)-1].Time != nil {
			duration := seg[len(seg)-1].Time.Sub(*seg[0].Time)
			classified.Duration = duration
			classified.DurationStr = formatDuration(duration)
		}
		result.ClassifiedSegments = append(result.ClassifiedSegments, classified)
		result.PatrolKm += distanceKm
	}

	// Final validation checks
	if result.PatrolKm == 0 && result.TotalPoints >= MinimumWaypoints {
		result.ValidationWarnings = append(result.ValidationWarnings,
			"No valid patrol segments detected - all data was classified as boundaries, roads, or auto-generated")
	}

	return result
}

// isAutoGenerated detects if a segment appears to be computer-generated
// Checks for:
// 1. Sub-second time intervals (e.g., 0.001s between points)
// 2. Grid-pattern coordinates (coordinates on exact grid lines)
// 3. Impossible speeds combined with microsecond intervals
// NOTE: Regular 3-second intervals from GPS devices are NORMAL and should NOT be flagged
func isAutoGenerated(points []gpx.Point) bool {
	if len(points) < 10 {
		return false
	}

	// Check for sub-second intervals - this is the key indicator of auto-generated data
	// Real GPS devices record at least 1 second apart
	subSecondCount := 0
	for i := 1; i < len(points); i++ {
		if points[i].Time != nil && points[i-1].Time != nil {
			interval := points[i].Time.Sub(*points[i-1].Time).Seconds()
			if interval > 0 && interval < 0.5 { // Less than 0.5 seconds = definitely auto-generated
				subSecondCount++
			}
		}
	}
	// If more than 20% of intervals are sub-second, it's auto-generated
	if float64(subSecondCount)/float64(len(points)-1) > 0.2 {
		return true
	}

	// Check for grid pattern coordinates
	gridCount := 0
	for _, pt := range points {
		// Check if coordinates are on exact grid (e.g., 0.001 degree increments)
		latFrac := math.Abs(pt.Lat*1000 - math.Round(pt.Lat*1000))
		lonFrac := math.Abs(pt.Lon*1000 - math.Round(pt.Lon*1000))
		if latFrac < 0.0001 && lonFrac < 0.0001 {
			gridCount++
		}
	}
	// If more than 80% of points are on exact grid, suspicious
	if float64(gridCount)/float64(len(points)) > 0.8 {
		return true
	}

	// Check for impossible speeds (> 500 km/h consistently)
	impossibleSpeedCount := 0
	for i := 1; i < len(points); i++ {
		if points[i].Time != nil && points[i-1].Time != nil {
			duration := points[i].Time.Sub(*points[i-1].Time).Hours()
			if duration > 0 {
				dist := haversineDistanceKm(points[i-1].Lat, points[i-1].Lon, points[i].Lat, points[i].Lon)
				speed := dist / duration
				if speed > 500 { // > 500 km/h
					impossibleSpeedCount++
				}
			}
		}
	}
	if float64(impossibleSpeedCount)/float64(len(points)) > 0.5 {
		return true
	}

	return false
}

// detectStaticSegments finds segments where the device wasn't moving
// Returns segments where speed < 0.1 km/h for > 30 minutes
func detectStaticSegments(points []gpx.Point) []ClassifiedSegment {
	var staticSegs []ClassifiedSegment

	if len(points) < 5 {
		return staticSegs
	}

	staticStart := -1
	staticStartTime := time.Time{}

	for i := 1; i < len(points); i++ {
		dist := haversineDistanceKm(points[i-1].Lat, points[i-1].Lon, points[i].Lat, points[i].Lon)

		// If movement is very small (< 10 meters)
		if dist < 0.01 {
			if staticStart == -1 {
				staticStart = i - 1
				if points[i-1].Time != nil {
					staticStartTime = *points[i-1].Time
				}
			}
		} else {
			// Movement detected - check if we had a static segment
			if staticStart != -1 && points[i-1].Time != nil && !staticStartTime.IsZero() {
				duration := points[i-1].Time.Sub(staticStartTime)
				if duration > 30*time.Minute {
					seg := ClassifiedSegment{
					Classification:  "static",
					StartIndex:      staticStart,
					EndIndex:        i - 1,
					DistanceKm:      0,
					Duration:        duration,
					DurationStr:     formatDuration(duration),
					Reason:          fmt.Sprintf("Stationary for %s", formatDuration(duration)),
					IncludeInEffort: false,
				}
				staticSegs = append(staticSegs, seg)
				}
			}
			staticStart = -1
			staticStartTime = time.Time{}
		}
	}

	// Check final segment
	if staticStart != -1 && len(points) > 0 && points[len(points)-1].Time != nil && !staticStartTime.IsZero() {
		duration := points[len(points)-1].Time.Sub(staticStartTime)
		if duration > 30*time.Minute {
			seg := ClassifiedSegment{
				Classification:  "static",
				StartIndex:      staticStart,
				EndIndex:        len(points) - 1,
				DistanceKm:      0,
				Duration:        duration,
				DurationStr:     formatDuration(duration),
				Reason:          fmt.Sprintf("Stationary for %s", formatDuration(duration)),
				IncludeInEffort: false,
			}
			staticSegs = append(staticSegs, seg)
		}
	}

	return staticSegs
}

// isBoundaryTrace detects if segment is a park boundary trace
// Characteristics: forms a closed polygon, area > 1 km², low sinuosity
func isBoundaryTrace(points []gpx.Point) bool {
	if len(points) < 20 {
		return false
	}

	// Check if it forms a closed polygon (start and end within 500m)
	startEnd := haversineDistanceKm(points[0].Lat, points[0].Lon,
		points[len(points)-1].Lat, points[len(points)-1].Lon)
	if startEnd > 0.5 {
		return false // Not a closed polygon
	}

	// Calculate approximate area using shoelace formula
	var area float64
	for i := 0; i < len(points)-1; i++ {
		area += points[i].Lon * points[i+1].Lat
		area -= points[i+1].Lon * points[i].Lat
	}
	area = math.Abs(area) / 2.0

	// Convert to approximate km² (rough conversion at equator)
	areaKm2 := area * 111 * 111

	// Boundary traces typically enclose large areas (> 1 km²)
	if areaKm2 > 1.0 {
		// Also check if it has very consistent bearing changes (regular polygon shape)
		return true
	}

	return false
}

// isRoadTrace detects if segment is a road network trace
// Characteristics: high bearing consistency, follows linear patterns
func isRoadTrace(points []gpx.Point) bool {
	if len(points) < 10 {
		return false
	}

	// Calculate bearings between consecutive points
	var bearings []float64
	for i := 1; i < len(points); i++ {
		bearing := calculateBearing(points[i-1].Lat, points[i-1].Lon,
			points[i].Lat, points[i].Lon)
		bearings = append(bearings, bearing)
	}

	if len(bearings) < 5 {
		return false
	}

	// Count segments where bearing changes by less than 10 degrees
	straightCount := 0
	for i := 1; i < len(bearings); i++ {
		diff := math.Abs(bearings[i] - bearings[i-1])
		if diff > 180 {
			diff = 360 - diff
		}
		if diff < 10 {
			straightCount++
		}
	}

	// If more than 90% of segments are straight, likely a road trace
	straightRatio := float64(straightCount) / float64(len(bearings)-1)
	if straightRatio > 0.9 {
		return true
	}

	return false
}

// calculateSegmentDistance calculates total distance of a segment
func calculateSegmentDistance(points []gpx.Point) float64 {
	var total float64
	for i := 1; i < len(points); i++ {
		total += haversineDistanceKm(points[i-1].Lat, points[i-1].Lon,
			points[i].Lat, points[i].Lon)
	}
	return total
}

// formatDuration formats a duration as a human-readable string
func formatDuration(d time.Duration) string {
	if d < time.Minute {
		return fmt.Sprintf("%ds", int(d.Seconds()))
	}
	if d < time.Hour {
		return fmt.Sprintf("%dm", int(d.Minutes()))
	}
	hours := int(d.Hours())
	minutes := int(d.Minutes()) % 60
	if minutes > 0 {
		return fmt.Sprintf("%dh%dm", hours, minutes)
	}
	return fmt.Sprintf("%dh", hours)
}

// pointsToGeoJSON converts points to a GeoJSON LineString
func pointsToGeoJSON(points []gpx.Point) string {
	if len(points) < 2 {
		return ""
	}

	coords := make([][]float64, len(points))
	for i, pt := range points {
		coords[i] = []float64{pt.Lon, pt.Lat}
	}

	geojson := map[string]interface{}{
		"type":        "LineString",
		"coordinates": coords,
	}

	bytes, _ := json.Marshal(geojson)
	return string(bytes)
}
