package srv

import (
	"bytes"
	"context"
	"crypto/md5"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"sync"
	"sync/atomic"
	"time"

	zenodo "github.com/raffopenssh/zenodo-mirror-go-pkg"
	"srv.exe.dev/srv/areas"
)

// zenodoMBTilesMetadata returns Zenodo metadata for an MBTiles upload.
func zenodoMBTilesMetadata(parkName, source string, minZoom, maxZoom int) zenodo.MetadataFunc {
	return func(key, filename, version string) map[string]interface{} {
		return map[string]interface{}{
			"metadata": map[string]interface{}{
				"title":        fmt.Sprintf("5MP Offline Tiles – %s (%s, z%d–%d)", parkName, source, minZoom, maxZoom),
				"upload_type":  "dataset",
				"description":  fmt.Sprintf("MBTiles satellite imagery for %s from %s, zoom levels %d–%d. Generated by 5MP Conservation Monitoring.", parkName, source, minZoom, maxZoom),
				"access_right": "restricted",
				"creators":     []map[string]interface{}{{"name": "5MP Conservation Monitoring"}},
			},
		}
	}
}

// Build/size limits.
//
// In-memory builds (preferred — disk usage costs extra on this VM) peak at
// ~3× raw tile bytes (SQLite overhead + Serialize copy); the 7.2 GB VM
// supports ~2 GB files that way. Larger builds fall back to a disk temp file
// and stream-upload, up to maxMBTilesSize. The disk path is reserved for
// non-test (prod-password) users; test users keep the RAM-only limit.
const (
	inMemoryRAMBudget = 7 * 1024 * 1024 * 1024 // peak RAM ceiling for in-memory builds
	maxMBTilesSize    = 8 * 1024 * 1024 * 1024 // absolute file-size cap (disk-backed, Zenodo allows 50GB)
	mbtilesDiskMargin = 1.2                    // require 1.2× estimated size free on disk
	mbtilesMinFree    = 2 * 1024 * 1024 * 1024 // always leave 2 GB free
)

// ZenodoMBTilesJob represents a tile generation + Zenodo upload job.
type ZenodoMBTilesJob struct {
	ID              string     `json:"id"`
	ParkID          string     `json:"park_id"`
	ParkName        string     `json:"park_name"`
	Source          string     `json:"source"`
	MinZoom         int        `json:"min_zoom"`
	MaxZoom         int        `json:"max_zoom"`
	BufferKm        float64    `json:"buffer_km"`
	BBox            [4]float64 `json:"bbox"`
	Status          string     `json:"status"` // pending, downloading, uploading, completed, failed
	Progress        float64    `json:"progress"`
	Phase           string     `json:"phase"` // "tiles", "upload"
	TotalTiles      int64      `json:"total_tiles"`
	DownloadedTiles int64      `json:"downloaded_tiles"`
	FileSize        int64      `json:"file_size_bytes"`
	Error           string     `json:"error,omitempty"`
	CreatedAt       time.Time  `json:"created_at"`
	CompletedAt     *time.Time `json:"completed_at,omitempty"`
	Env             string     `json:"env,omitempty"` // tenant (RequestEnv) — scopes notifications

	// Zenodo result fields
	ZenodoDepoID int    `json:"zenodo_depo_id,omitempty"`
	ZenodoDOI    string `json:"zenodo_doi,omitempty"`
	DownloadURL  string `json:"download_url,omitempty"` // Zenodo bucket download URL
}

// ZenodoMBTilesQueue manages tile generation + Zenodo upload jobs.
type ZenodoMBTilesQueue struct {
	jobs       map[string]*ZenodoMBTilesJob
	mu         sync.RWMutex
	processing atomic.Bool
	ctx        context.Context
	cancel     context.CancelFunc

	zenodoClient   *zenodo.Client
	zenodoManifest *zenodo.Manifest

	maxCPU int
	db     interface {
		Exec(string, ...interface{}) (sql.Result, error)
	}
}

var zenodoMBQueue *ZenodoMBTilesQueue

// InitZenodoMBTilesQueue initializes the Zenodo-backed MBTiles queue.
func InitZenodoMBTilesQueue(zenodoToken string, db interface {
	Exec(string, ...interface{}) (sql.Result, error)
}) error {
	if zenodoToken == "" {
		slog.Warn("Zenodo MBTiles queue not initialized: no token provided")
		return fmt.Errorf("zenodo token required")
	}

	ctx, cancel := context.WithCancel(context.Background())

	client := zenodo.New(zenodoToken,
		zenodo.WithMaxRetries(3),
		zenodo.WithRetryWait(5*time.Second),
		zenodo.WithHTTPClient(&http.Client{Timeout: 30 * time.Minute}),
	)

	manifest, err := zenodo.NewManifest("data/mbtiles_zenodo_manifest.json")
	if err != nil {
		cancel()
		return fmt.Errorf("load zenodo manifest: %w", err)
	}

	nCPU := 4 // concurrent tile downloads

	zenodoMBQueue = &ZenodoMBTilesQueue{
		jobs:           make(map[string]*ZenodoMBTilesJob),
		ctx:            ctx,
		cancel:         cancel,
		zenodoClient:   client,
		zenodoManifest: manifest,
		maxCPU:         nCPU,
		db:             db,
	}

	go zenodoMBQueue.processJobs()

	slog.Info("Zenodo MBTiles queue initialized", "manifestEntries", manifest.Len())
	return nil
}

func (q *ZenodoMBTilesQueue) addJob(job *ZenodoMBTilesJob) {
	q.mu.Lock()
	defer q.mu.Unlock()
	job.Status = "pending"
	job.CreatedAt = time.Now()
	q.jobs[job.ID] = job
}

func (q *ZenodoMBTilesQueue) getJob(id string) *ZenodoMBTilesJob {
	q.mu.RLock()
	defer q.mu.RUnlock()
	return q.jobs[id]
}

func (q *ZenodoMBTilesQueue) listJobs() []*ZenodoMBTilesJob {
	q.mu.RLock()
	defer q.mu.RUnlock()
	out := make([]*ZenodoMBTilesJob, 0, len(q.jobs))
	for _, j := range q.jobs {
		out = append(out, j)
	}
	return out
}

func (q *ZenodoMBTilesQueue) processJobs() {
	ticker := time.NewTicker(3 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-q.ctx.Done():
			return
		case <-ticker.C:
			if q.processing.Load() {
				continue
			}
			q.mu.Lock()
			var next *ZenodoMBTilesJob
			for _, j := range q.jobs {
				if j.Status == "pending" {
					next = j
					break
				}
			}
			q.mu.Unlock()

			if next != nil {
				q.processing.Store(true)
				q.executeJob(next)
				q.processing.Store(false)
			}
		}
	}
}

func (q *ZenodoMBTilesQueue) executeJob(job *ZenodoMBTilesJob) {
	defer func() {
		if r := recover(); r != nil {
			q.failJob(job, fmt.Sprintf("panic: %v", r))
		}
	}()

	slog.Info("Starting Zenodo MBTiles job", "id", job.ID, "park", job.ParkID, "source", job.Source)

	q.mu.Lock()
	job.Status = "downloading"
	job.Phase = "tiles"
	q.mu.Unlock()

	// Phase 1: Build MBTiles. Prefer in-memory (disk usage costs extra on this
	// VM); fall back to a disk temp file only when the estimate doesn't fit in
	// RAM (disk path is only reachable for non-test users — gated at create).
	ramNeeded := estimateRAMRequired(job.BBox, job.MinZoom, job.MaxZoom)
	useMemory := ramNeeded <= inMemoryRAMBudget

	var data []byte // set for in-memory builds
	var tmpPath string
	var fileSize int64
	var err error

	if useMemory {
		data, err = q.buildMBTilesInMemory(job)
		if err != nil {
			q.failJob(job, fmt.Sprintf("build in-memory: %s", err))
			return
		}
		fileSize = int64(len(data))
		slog.Info("MBTiles built in memory", "id", job.ID, "size_mb", fileSize/(1024*1024), "tiles", job.DownloadedTiles)
	} else {
		tmpPath, err = q.buildMBTilesToDisk(job)
		if tmpPath != "" {
			defer os.Remove(tmpPath)
		}
		if err != nil {
			q.failJob(job, fmt.Sprintf("build mbtiles: %s", err))
			return
		}
		if info, statErr := os.Stat(tmpPath); statErr == nil {
			fileSize = info.Size()
		}
		slog.Info("MBTiles built on disk", "id", job.ID, "path", tmpPath, "size_mb", fileSize/(1024*1024), "tiles", job.DownloadedTiles)
	}

	// Phase 2: Upload to Zenodo (streams from disk for large builds)
	q.mu.Lock()
	job.Status = "uploading"
	job.Phase = "upload"
	job.FileSize = fileSize
	q.mu.Unlock()

	if useMemory {
		err = q.uploadBytesToZenodo(job, data)
		data = nil // release large slice
	} else {
		err = q.uploadFileToZenodo(job, tmpPath)
	}
	if err != nil {
		q.failJob(job, fmt.Sprintf("zenodo upload: %s", err))
		return
	}

	// Success
	q.mu.Lock()
	job.Status = "completed"
	now := time.Now()
	job.CompletedAt = &now
	q.mu.Unlock()

	slog.Info("Zenodo MBTiles job completed",
		"id", job.ID,
		"depoID", job.ZenodoDepoID,
		"size_mb", job.FileSize/(1024*1024),
	)

	// Create notification
	q.createNotification(job)

	// Auto-clean job metadata after 24 hours
	go func(jobID string) {
		time.Sleep(24 * time.Hour)
		q.mu.Lock()
		delete(q.jobs, jobID)
		q.mu.Unlock()
	}(job.ID)
}

// fillMBTilesDB initializes the MBTiles schema and downloads all tiles into db.
// Shared by the in-memory and disk-backed build paths.
func (q *ZenodoMBTilesQueue) fillMBTilesDB(db *sql.DB, job *ZenodoMBTilesJob, source TileSource) error {
	mbJob := &MBTilesJob{
		ParkName: job.ParkName,
		BBox:     job.BBox,
		MinZoom:  job.MinZoom,
		MaxZoom:  job.MaxZoom,
	}
	if err := initMBTilesSchema(db, mbJob, source); err != nil {
		return fmt.Errorf("init schema: %w", err)
	}

	tiles := calculateTiles(job.BBox, job.MinZoom, job.MaxZoom)
	job.TotalTiles = int64(len(tiles))

	slog.Info("Downloading tiles", "total", job.TotalTiles, "source", source.Name)

	insertStmt, err := db.Prepare("INSERT OR REPLACE INTO tiles (zoom_level, tile_column, tile_row, tile_data) VALUES (?, ?, ?, ?)")
	if err != nil {
		return fmt.Errorf("prepare insert: %w", err)
	}
	defer insertStmt.Close()

	semaphore := make(chan struct{}, q.maxCPU)
	var wg sync.WaitGroup
	var downloaded atomic.Int64
	var errors atomic.Int64
	var insertMu sync.Mutex

	for _, tile := range tiles {
		select {
		case <-q.ctx.Done():
			return fmt.Errorf("cancelled")
		default:
		}

		wg.Add(1)
		semaphore <- struct{}{}

		go func(t Tile) {
			defer wg.Done()
			defer func() { <-semaphore }()

			data, err := downloadTile(source, t)
			if err != nil {
				errors.Add(1)
				return
			}

			tmsY := (1 << t.Z) - 1 - t.Y

			insertMu.Lock()
			insertStmt.Exec(t.Z, t.X, tmsY, data)
			insertMu.Unlock()

			count := downloaded.Add(1)
			job.DownloadedTiles = count
			job.Progress = float64(count) / float64(job.TotalTiles) * 90 // 0-90% for tiles
		}(tile)
	}

	wg.Wait()

	if errors.Load() > job.TotalTiles/2 {
		return fmt.Errorf("too many errors: %d/%d failed", errors.Load(), job.TotalTiles)
	}
	return nil
}

// buildMBTilesInMemory builds the MBTiles DB in RAM and serializes it to []byte.
// Preferred path (disk usage costs extra on this VM); only used when the
// estimated peak RAM fits within inMemoryRAMBudget.
//
// Memory lifecycle:
//  1. Tiles downloaded → inserted into in-memory SQLite (peak: ~DB size)
//  2. Serialize() allocates a []byte copy (brief peak: ~2× DB size)
//  3. DB closed + GC forced immediately → back to ~1× (the serialized bytes)
func (q *ZenodoMBTilesQueue) buildMBTilesInMemory(job *ZenodoMBTilesJob) ([]byte, error) {
	source, ok := TileSources[job.Source]
	if !ok {
		return nil, fmt.Errorf("unknown tile source: %s", job.Source)
	}

	db, err := sql.Open("sqlite", ":memory:")
	if err != nil {
		return nil, fmt.Errorf("open memory db: %w", err)
	}
	// Single connection required for Serialize
	db.SetMaxOpenConns(1)
	db.SetMaxIdleConns(1)

	if err := q.fillMBTilesDB(db, job, source); err != nil {
		db.Close()
		return nil, err
	}

	// Serialize the in-memory database to []byte
	job.Progress = 92

	conn, err := db.Conn(context.Background())
	if err != nil {
		db.Close()
		return nil, fmt.Errorf("get conn: %w", err)
	}

	var serialized []byte
	err = conn.Raw(func(driverConn interface{}) error {
		type serializer interface {
			Serialize() ([]byte, error)
		}
		s, ok := driverConn.(serializer)
		if !ok {
			return fmt.Errorf("driver conn does not implement Serialize")
		}
		var serErr error
		serialized, serErr = s.Serialize()
		return serErr
	})

	conn.Close()
	db.Close()
	runtime.GC() // Reclaim SQLite memory before upload

	if err != nil {
		return nil, fmt.Errorf("serialize: %w", err)
	}
	return serialized, nil
}

// buildMBTilesToDisk builds the MBTiles DB in a temp file on disk. Fallback
// for builds too large for RAM — allows files up to maxMBTilesSize (8 GB).
// Returns the temp file path (caller removes it).
func (q *ZenodoMBTilesQueue) buildMBTilesToDisk(job *ZenodoMBTilesJob) (string, error) {
	source, ok := TileSources[job.Source]
	if !ok {
		return "", fmt.Errorf("unknown tile source: %s", job.Source)
	}

	tmpDir := "data/mbtiles_output"
	os.MkdirAll(tmpDir, 0755)
	tmpPath := filepath.Join(tmpDir, fmt.Sprintf("zenodo_%s_%s_%s.mbtiles.tmp", job.ParkID, job.Source, job.ID))

	db, err := sql.Open("sqlite", tmpPath)
	if err != nil {
		return tmpPath, fmt.Errorf("open temp db: %w", err)
	}

	db.SetMaxOpenConns(1)
	db.SetMaxIdleConns(1)
	// Bulk-load pragmas: no durability needed for a throwaway build file
	db.Exec("PRAGMA journal_mode=OFF")
	db.Exec("PRAGMA synchronous=OFF")

	if err := q.fillMBTilesDB(db, job, source); err != nil {
		db.Close()
		return tmpPath, err
	}

	job.Progress = 92
	if err := db.Close(); err != nil {
		return tmpPath, fmt.Errorf("close db: %w", err)
	}

	return tmpPath, nil
}

// uploadBytesToZenodo uploads an in-memory MBTiles build.
func (q *ZenodoMBTilesQueue) uploadBytesToZenodo(job *ZenodoMBTilesJob, data []byte) error {
	return q.uploadToZenodo(job, bytes.NewReader(data), int64(len(data)), md5hex(data))
}

// uploadFileToZenodo streams the MBTiles file from disk to Zenodo
// (constant memory regardless of file size).
func (q *ZenodoMBTilesQueue) uploadFileToZenodo(job *ZenodoMBTilesJob, path string) error {
	checksum, fileSize, err := md5File(path)
	if err != nil {
		return fmt.Errorf("checksum: %w", err)
	}
	f, err := os.Open(path)
	if err != nil {
		return fmt.Errorf("open: %w", err)
	}
	defer f.Close()
	return q.uploadToZenodo(job, f, fileSize, checksum)
}

// uploadToZenodo uploads MBTiles content from a seekable reader to Zenodo.
// Seekable so failed PUTs can rewind and retry.
func (q *ZenodoMBTilesQueue) uploadToZenodo(job *ZenodoMBTilesJob, body io.ReadSeeker, size int64, checksum string) error {
	job.Progress = 93

	key := fmt.Sprintf("mbtiles_%s_%s", job.ParkID, job.Source)
	filename := fmt.Sprintf("%s_%s.mbtiles", job.ParkID, job.Source)
	version := time.Now().UTC().Format("2006-01-02T15:04:05")

	meta := zenodoMBTilesMetadata(job.ParkName, job.Source, job.MinZoom, job.MaxZoom)

	// Check if we already have a deposition for this park+source
	existing := q.zenodoManifest.Get(key)

	var depoID int
	var bucketURL string

	if existing != nil && existing.DepoID > 0 {
		// Update existing deposition
		slog.Info("Updating existing Zenodo deposition", "key", key, "depoID", existing.DepoID)
		depoID = existing.DepoID
		bucketURL = existing.BucketURL

		// Delete old file
		deleteURL := fmt.Sprintf("%s/%s", existing.BucketURL, existing.Filename)
		q.zenodoDoRequest("DELETE", deleteURL, nil, "")
	} else {
		// Create new deposition
		slog.Info("Creating new Zenodo deposition", "key", key)

		respBody, status, err := q.zenodoDoRequest("POST",
			fmt.Sprintf("%s/api/deposit/depositions", q.zenodoClient.BaseURL),
			bytes.NewReader([]byte("{}")), "application/json")
		if err != nil {
			return fmt.Errorf("create deposition: %w", err)
		}
		if status < 200 || status >= 300 {
			return fmt.Errorf("create deposition HTTP %d: %s", status, respBody)
		}

		var depo struct {
			ID    int `json:"id"`
			Links struct {
				Bucket string `json:"bucket"`
			} `json:"links"`
		}
		if err := json.Unmarshal(respBody, &depo); err != nil {
			return fmt.Errorf("parse deposition: %w", err)
		}
		depoID = depo.ID
		bucketURL = depo.Links.Bucket
	}

	// Upload file to bucket (streamed; constant memory). Large files over a
	// residential-grade uplink can take a long time and hit transient Zenodo
	// errors — be very patient: no client timeout, several retries with
	// exponential backoff, rewinding the body between attempts.
	job.Progress = 95
	slog.Info("Uploading MBTiles to Zenodo", "key", key, "size_mb", size/(1024*1024))

	uploadURL := fmt.Sprintf("%s/%s", bucketURL, filename)
	const maxAttempts = 5
	var lastErr error
	for attempt := 1; attempt <= maxAttempts; attempt++ {
		if _, err := body.Seek(0, io.SeekStart); err != nil {
			return fmt.Errorf("rewind body: %w", err)
		}
		respBody, status, err := q.zenodoDoStream("PUT", uploadURL, body, size, "application/octet-stream")
		if err == nil && status >= 200 && status < 300 {
			lastErr = nil
			break
		}
		if err != nil {
			lastErr = fmt.Errorf("upload file (attempt %d/%d): %w", attempt, maxAttempts, err)
		} else {
			lastErr = fmt.Errorf("upload file HTTP %d (attempt %d/%d): %s", status, attempt, maxAttempts, respBody)
			// Don't retry permanent client errors (bad token, quota, etc.)
			if status >= 400 && status < 500 && status != 408 && status != 429 {
				return lastErr
			}
		}
		slog.Warn("Zenodo upload attempt failed", "key", key, "attempt", attempt, "error", lastErr)
		if attempt < maxAttempts {
			select {
			case <-q.ctx.Done():
				return fmt.Errorf("cancelled during upload retry")
			case <-time.After(time.Duration(30*(1<<(attempt-1))) * time.Second): // 30s, 1m, 2m, 4m
			}
		}
	}
	if lastErr != nil {
		return lastErr
	}

	// Set metadata
	job.Progress = 98
	metaPayload := meta(key, filename, version)
	metaJSON, _ := json.Marshal(metaPayload)
	metaURL := fmt.Sprintf("%s/api/deposit/depositions/%d", q.zenodoClient.BaseURL, depoID)
	metaRespBody, metaStatus, metaErr := q.zenodoDoRequest("PUT", metaURL, bytes.NewReader(metaJSON), "application/json")
	if metaErr != nil {
		return fmt.Errorf("set metadata: %w", metaErr)
	}
	if metaStatus < 200 || metaStatus >= 300 {
		return fmt.Errorf("set metadata HTTP %d: %s", metaStatus, metaRespBody)
	}

	// Update manifest
	entry := &zenodo.Entry{
		Key:        key,
		DepoID:     depoID,
		BucketURL:  bucketURL,
		Filename:   filename,
		Size:       size,
		Checksum:   checksum,
		UploadedAt: time.Now().UTC(),
		Version:    version,
	}
	q.zenodoManifest.Set(key, entry)
	if err := q.zenodoManifest.Save(); err != nil {
		slog.Warn("Failed to save zenodo manifest", "error", err)
	}

	// Set job result fields
	job.ZenodoDepoID = depoID
	job.DownloadURL = fmt.Sprintf("%s/%s", bucketURL, filename)
	job.Progress = 100

	return nil
}

// zenodoStreamClient has no overall timeout — an 8 GB PUT can legitimately
// take hours. Stalled connections are still detected via TCP keepalives and
// response-header timeout on the transport.
var zenodoStreamClient = &http.Client{
	Transport: &http.Transport{
		ResponseHeaderTimeout: 10 * time.Minute, // time after body sent until Zenodo responds
		ExpectContinueTimeout: 30 * time.Second,
	},
}

// zenodoDoStream performs a request with a streaming body of known size
// (used for large file PUTs — constant memory, no client timeout).
func (q *ZenodoMBTilesQueue) zenodoDoStream(method, url string, body io.Reader, size int64, contentType string) ([]byte, int, error) {
	req, err := http.NewRequestWithContext(q.ctx, method, url, body)
	if err != nil {
		return nil, 0, err
	}
	req.ContentLength = size
	req.Header.Set("Authorization", "Bearer "+q.zenodoClient.Token)
	if contentType != "" {
		req.Header.Set("Content-Type", contentType)
	}
	resp, err := zenodoStreamClient.Do(req)
	if err != nil {
		return nil, 0, err
	}
	defer resp.Body.Close()
	var buf bytes.Buffer
	buf.ReadFrom(resp.Body)
	return buf.Bytes(), resp.StatusCode, nil
}

// md5File returns the md5 hex checksum and size of a file (streamed).
func md5File(path string) (string, int64, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", 0, err
	}
	defer f.Close()
	h := md5.New()
	n, err := io.Copy(h, f)
	if err != nil {
		return "", 0, err
	}
	return hex.EncodeToString(h.Sum(nil)), n, nil
}

// zenodoDoRequest is a thin wrapper that reuses the client's token/retries
// but accepts an io.Reader directly (no file required).
func (q *ZenodoMBTilesQueue) zenodoDoRequest(method, url string, body *bytes.Reader, contentType string) ([]byte, int, error) {
	var req *http.Request
	var err error
	if body != nil {
		req, err = http.NewRequest(method, url, body)
	} else {
		req, err = http.NewRequest(method, url, nil)
	}
	if err != nil {
		return nil, 0, err
	}
	req.Header.Set("Authorization", "Bearer "+q.zenodoClient.Token)
	if contentType != "" {
		req.Header.Set("Content-Type", contentType)
	}

	resp, err := q.zenodoClient.HTTPClient.Do(req)
	if err != nil {
		return nil, 0, err
	}
	defer resp.Body.Close()

	var buf bytes.Buffer
	buf.ReadFrom(resp.Body)
	return buf.Bytes(), resp.StatusCode, nil
}

func (q *ZenodoMBTilesQueue) failJob(job *ZenodoMBTilesJob, errMsg string) {
	q.mu.Lock()
	job.Status = "failed"
	job.Error = errMsg
	q.mu.Unlock()
	slog.Error("Zenodo MBTiles job failed", "id", job.ID, "error", errMsg)

	if q.db != nil {
		q.db.Exec(`INSERT INTO notifications (park_id, notification_type, title, message, env, created_at)
			VALUES (?, 'mbtiles_failed', ?, ?, ?, datetime('now'))`,
			job.ParkID,
			fmt.Sprintf("MBTiles Failed: %s", job.ParkName),
			fmt.Sprintf("Tile generation for %s failed: %s", job.ParkName, errMsg),
			jobEnv(job),
		)
	}
}

func (q *ZenodoMBTilesQueue) createNotification(job *ZenodoMBTilesJob) {
	if q.db == nil {
		return
	}
	sizeMB := job.FileSize / (1024 * 1024)

	// Include manifest key so download works even after job expires.
	manifestKey := fmt.Sprintf("mbtiles_%s_%s", job.ParkID, job.Source)
	refURL := fmt.Sprintf("/api/mbtiles/%s/download?key=%s", job.ID, manifestKey)

	q.db.Exec(`INSERT INTO notifications (park_id, notification_type, title, message, reference_url, env, created_at)
		VALUES (?, 'mbtiles_complete', ?, ?, ?, ?, datetime('now'))`,
		job.ParkID,
		fmt.Sprintf("MBTiles Ready: %s", job.ParkName),
		fmt.Sprintf("Offline tiles for %s (%s, z1–%d, %d MB) stored on Zenodo", job.ParkName, job.Source, job.MaxZoom, sizeMB),
		refURL,
		jobEnv(job),
	)
}

// jobEnv returns the env a job was created under, defaulting to prod.
func jobEnv(job *ZenodoMBTilesJob) string {
	if job.Env == "" {
		return clientTenant
	}
	return job.Env
}

func md5hex(data []byte) string {
	h := md5.Sum(data)
	return hex.EncodeToString(h[:])
}

// estimateTileBytes returns estimated MBTiles file size.
// Real-world average: ~10 KB/tile for satellite imagery (measured from actual uploads).
func estimateTileBytes(nTiles int) int64 {
	return int64(nTiles) * 10 * 1024 // 10 KB/tile
}

// estimateRAMRequired estimates peak RAM for the in-memory MBTiles build.
//
// Memory breakdown:
//   - In-memory SQLite holds tiles in B-tree pages with ~50% overhead
//     over raw tile data (page headers, free space, indexes).
//   - Serialize() allocates a full copy of the DB as []byte.
//   - Peak = SQLite DB size + serialized copy ≈ 3× raw tile data.
//   - Plus ~500 MB baseline for server + OS.
//
// Validated: Nyerere z16 (366K tiles, ~3.6 GB raw) OOM'd at 56% on 7.4 GB VM,
// confirming that actual memory usage is ~3× raw tile estimate.
func estimateRAMRequired(bbox [4]float64, minZoom, maxZoom int) int64 {
	tiles := calculateTiles(bbox, minZoom, maxZoom)
	rawSize := estimateTileBytes(len(tiles))
	// Peak: ~1.5× for SQLite in-memory overhead, ×2 for Serialize() copy = 3×
	peak := int64(float64(rawSize) * 3.0)
	// Add baseline server + OS overhead
	const baselineOverhead = 500 * 1024 * 1024 // 500 MB
	return peak + baselineOverhead
}

// checkMBTilesCapacity decides whether a build of the given extent is allowed.
// extended=true (prod-password users) permits the disk-backed path up to
// maxMBTilesSize; extended=false (test users) is limited to what fits in RAM.
func checkMBTilesCapacity(bbox [4]float64, maxZoom int, extended bool) (bool, string) {
	tiles := calculateTiles(bbox, 1, maxZoom)
	estimatedSize := estimateTileBytes(len(tiles))
	ramNeeded := estimateRAMRequired(bbox, 1, maxZoom)

	// Fits in RAM → always fine (preferred path, no disk usage)
	if ramNeeded <= inMemoryRAMBudget {
		return true, ""
	}

	if !extended {
		maxFileMB := (inMemoryRAMBudget - 500*1024*1024) / 3 / (1024 * 1024)
		return false, fmt.Sprintf(
			"Estimated peak RAM ~%.1f GB exceeds available ~%.1f GB. Max file size ~%d MB with test access. Reduce zoom level.",
			float64(ramNeeded)/(1024*1024*1024),
			float64(inMemoryRAMBudget)/(1024*1024*1024),
			maxFileMB,
		)
	}

	// Extended: disk-backed build
	if estimatedSize > maxMBTilesSize {
		return false, fmt.Sprintf(
			"Estimated file ~%.1f GB exceeds the %d GB limit. Reduce zoom level.",
			float64(estimatedSize)/(1024*1024*1024),
			maxMBTilesSize/(1024*1024*1024),
		)
	}
	avail := getAvailableDiskSpace("data")
	required := uint64(float64(estimatedSize)*mbtilesDiskMargin) + mbtilesMinFree
	if required > avail {
		return false, fmt.Sprintf(
			"Insufficient disk space: need ~%.1f GB free, only %.1f GB available. Reduce zoom level.",
			float64(required)/(1024*1024*1024),
			float64(avail)/(1024*1024*1024),
		)
	}
	return true, ""
}

// ─── HTTP Handlers ───────────────────────────────────────────────────────────

// HandleAPIZenodoMBTilesCreate starts a new MBTiles-to-Zenodo job.
func (s *Server) HandleAPIZenodoMBTilesCreate(w http.ResponseWriter, r *http.Request) {
	if zenodoMBQueue == nil {
		http.Error(w, "Zenodo MBTiles not configured", http.StatusServiceUnavailable)
		return
	}

	parkID := r.PathValue("id")
	if parkID == "" {
		http.Error(w, "Park ID required", http.StatusBadRequest)
		return
	}

	areaName, rawBBox, ok := s.resolveAreaBBox(parkID)
	if !ok {
		http.Error(w, "Park not found", http.StatusNotFound)
		return
	}

	source := r.URL.Query().Get("source")
	if source == "" {
		source = "esri"
	}
	if _, ok := TileSources[source]; !ok {
		http.Error(w, "Invalid source. Use: esri, bing, google", http.StatusBadRequest)
		return
	}

	maxZoom := 17
	if mzStr := r.URL.Query().Get("maxZoom"); mzStr != "" {
		if mz, err := fmt.Sscanf(mzStr, "%d", &maxZoom); err != nil || mz < 1 {
			maxZoom = 17
		}
		if maxZoom < 1 {
			maxZoom = 1
		}
		if maxZoom > 19 {
			maxZoom = 19
		}
	}

	bufferKm := 5.0
	bbox := bufferBBox(rawBBox, bufferKm)
	tiles := calculateTiles(bbox, 1, maxZoom)
	estimatedSize := estimateTileBytes(len(tiles))

	// The shared demo sandbox keeps the RAM-only limit; real tenants get the
	// extended disk-backed path (larger files, but disk usage costs extra).
	extended := RequestEnv(r) != sandboxTenant
	if ok, reason := checkMBTilesCapacity(bbox, maxZoom, extended); !ok {
		http.Error(w, reason, http.StatusRequestEntityTooLarge)
		return
	}

	job := &ZenodoMBTilesJob{
		ID:       fmt.Sprintf("%d", time.Now().UnixNano()),
		ParkID:   parkID,
		ParkName: areaName,
		Source:   source,
		MinZoom:  1,
		MaxZoom:  maxZoom,
		BufferKm: bufferKm,
		BBox:     bbox,
		Env:      RequestEnv(r),
	}

	zenodoMBQueue.addJob(job)

	estSeconds := len(tiles) / 100
	if estSeconds < 60 {
		estSeconds = 60
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]interface{}{
		"job_id":            job.ID,
		"park_id":           parkID,
		"source":            source,
		"total_tiles":       len(tiles),
		"estimated_size_mb": estimatedSize / (1024 * 1024),
		"estimated_seconds": estSeconds,
		"storage":           "zenodo",
		"status_url":        fmt.Sprintf("/api/mbtiles/%s/status?pwd=%s", job.ID, r.URL.Query().Get("pwd")),
	})
}

// HandleAPIZenodoMBTilesEstimate returns size/time estimates for Zenodo upload.
func (s *Server) HandleAPIZenodoMBTilesEstimate(w http.ResponseWriter, r *http.Request) {
	parkID := r.PathValue("id")
	_, rawBBox, ok := s.resolveAreaBBox(parkID)
	if !ok {
		http.Error(w, "Park not found", http.StatusNotFound)
		return
	}

	maxZoom := 17
	if mzStr := r.URL.Query().Get("maxZoom"); mzStr != "" {
		fmt.Sscanf(mzStr, "%d", &maxZoom)
		if maxZoom < 1 {
			maxZoom = 1
		}
		if maxZoom > 19 {
			maxZoom = 19
		}
	}

	bbox := bufferBBox(rawBBox, 5.0)
	tiles := calculateTiles(bbox, 1, maxZoom)
	estimatedSize := estimateTileBytes(len(tiles))
	ramNeeded := estimateRAMRequired(bbox, 1, maxZoom)
	estSeconds := len(tiles) / 100

	// The shared demo sandbox is limited to in-memory builds; real tenants get
	// the extended disk-backed path up to maxMBTilesSize.
	extended := RequestEnv(r) != sandboxTenant
	sufficient, capacityReason := checkMBTilesCapacity(bbox, maxZoom, extended)

	// Check if already uploaded to Zenodo
	key := fmt.Sprintf("mbtiles_%s_%s", parkID, r.URL.Query().Get("source"))
	if key == fmt.Sprintf("mbtiles_%s_", parkID) {
		key = fmt.Sprintf("mbtiles_%s_esri", parkID)
	}
	var existingDepoID int
	if zenodoMBQueue != nil {
		if entry := zenodoMBQueue.zenodoManifest.Get(key); entry != nil {
			existingDepoID = entry.DepoID
		}
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]interface{}{
		"park_id":           parkID,
		"total_tiles":       len(tiles),
		"estimated_size_mb": estimatedSize / (1024 * 1024),
		"estimated_seconds": estSeconds,
		"bbox":              bbox,
		"min_zoom":          1,
		"max_zoom":          maxZoom,
		"sufficient_space":  sufficient,
		"capacity_reason":   capacityReason,
		"extended_limits":   extended,
		"build_mode":        map[bool]string{true: "memory", false: "disk"}[ramNeeded <= inMemoryRAMBudget],
		"max_file_gb":       maxMBTilesSize / (1024 * 1024 * 1024),
		"storage":           "zenodo",
		"ram_needed_mb":     ramNeeded / (1024 * 1024),
		"existing_depo_id":  existingDepoID,
		"sources":           []string{"esri", "bing", "google"},
	})
}

// HandleAPIZenodoMBTilesStatus returns job status (reuses the same endpoint path).
func (s *Server) HandleAPIZenodoMBTilesStatus(w http.ResponseWriter, r *http.Request) {
	jobID := r.PathValue("id")

	// Check Zenodo queue first
	if zenodoMBQueue != nil {
		if job := zenodoMBQueue.getJob(jobID); job != nil {
			w.Header().Set("Content-Type", "application/json")
			json.NewEncoder(w).Encode(job)
			return
		}
	}

	// Fall back to legacy disk-based queue
	if mbtilesQueue != nil {
		if job := mbtilesQueue.GetJob(jobID); job != nil {
			w.Header().Set("Content-Type", "application/json")
			json.NewEncoder(w).Encode(job)
			return
		}
	}

	http.Error(w, "Job not found", http.StatusNotFound)
}

// HandleAPIZenodoMBTilesDownload proxies the download from Zenodo (or redirects).
func (s *Server) HandleAPIZenodoMBTilesDownload(w http.ResponseWriter, r *http.Request) {
	jobID := r.PathValue("id")

	// Check active Zenodo job first
	if zenodoMBQueue != nil {
		if job := zenodoMBQueue.getJob(jobID); job != nil {
			if job.Status != "completed" {
				http.Error(w, fmt.Sprintf("Job not ready: %s", job.Status), http.StatusBadRequest)
				return
			}
			if job.DownloadURL != "" {
				proxyZenodoDownload(w, job.DownloadURL, fmt.Sprintf("%s_%s.mbtiles", job.ParkID, job.Source))
				return
			}
			http.Error(w, "No download URL available", http.StatusNotFound)
			return
		}

		// Job expired but may still be in manifest — look up by key param
		if key := r.URL.Query().Get("key"); key != "" {
			if entry := zenodoMBQueue.zenodoManifest.Get(key); entry != nil {
				downloadURL := fmt.Sprintf("%s/%s", entry.BucketURL, entry.Filename)
				proxyZenodoDownload(w, downloadURL, entry.Filename)
				return
			}
		}
	}

	// Fall back to legacy disk-based download
	s.HandleAPIMBTilesDownload(w, r)
}

// proxyZenodoDownload streams a file from Zenodo to the client.
func proxyZenodoDownload(w http.ResponseWriter, downloadURL, filename string) {
	q := zenodoMBQueue
	req, err := http.NewRequest("GET", downloadURL, nil)
	if err != nil {
		http.Error(w, "Failed to create request", http.StatusInternalServerError)
		return
	}
	req.Header.Set("Authorization", "Bearer "+q.zenodoClient.Token)

	resp, err := q.zenodoClient.HTTPClient.Do(req)
	if err != nil {
		http.Error(w, "Failed to fetch from Zenodo", http.StatusBadGateway)
		return
	}
	defer resp.Body.Close()

	w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=%s", filename))
	w.Header().Set("Content-Type", "application/x-sqlite3")
	if resp.ContentLength > 0 {
		w.Header().Set("Content-Length", fmt.Sprintf("%d", resp.ContentLength))
	}
	w.WriteHeader(resp.StatusCode)
	buf := make([]byte, 256*1024)
	for {
		n, readErr := resp.Body.Read(buf)
		if n > 0 {
			w.Write(buf[:n])
		}
		if readErr != nil {
			break
		}
	}
}

// HandleAPIZenodoMBTilesList lists jobs from both queues.
func (s *Server) HandleAPIZenodoMBTilesList(w http.ResponseWriter, r *http.Request) {
	var allJobs []interface{}

	if zenodoMBQueue != nil {
		for _, j := range zenodoMBQueue.listJobs() {
			allJobs = append(allJobs, j)
		}
	}

	// Include legacy jobs too
	if mbtilesQueue != nil {
		for _, j := range mbtilesQueue.ListJobs() {
			allJobs = append(allJobs, j)
		}
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(allJobs)
}

// Helper to check calculateBufferedBBox signature - it uses *areas.ProtectedArea
var _ = func() { var a *areas.ProtectedArea; calculateBufferedBBox(a, 0) }
