package srv

import (
	"bytes"
	"context"
	"crypto/md5"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"sync"
	"sync/atomic"
	"time"

	zenodo "github.com/raffopenssh/zenodo-mirror-go-pkg"
	"srv.exe.dev/srv/areas"
)

// zenodoMBTilesMetadata returns Zenodo metadata for an MBTiles upload.
func zenodoMBTilesMetadata(parkName, source string, minZoom, maxZoom int) zenodo.MetadataFunc {
	return func(key, filename, version string) map[string]interface{} {
		return map[string]interface{}{
			"metadata": map[string]interface{}{
				"title":        fmt.Sprintf("5MP Offline Tiles – %s (%s, z%d–%d)", parkName, source, minZoom, maxZoom),
				"upload_type":  "dataset",
				"description":  fmt.Sprintf("MBTiles satellite imagery for %s from %s, zoom levels %d–%d. Generated by 5MP Conservation Monitoring.", parkName, source, minZoom, maxZoom),
				"access_right": "restricted",
				"creators":     []map[string]interface{}{{"name": "5MP Conservation Monitoring"}},
			},
		}
	}
}

// ZenodoMBTilesJob represents a tile generation + Zenodo upload job.
type ZenodoMBTilesJob struct {
	ID              string     `json:"id"`
	ParkID          string     `json:"park_id"`
	ParkName        string     `json:"park_name"`
	Source          string     `json:"source"`
	MinZoom         int        `json:"min_zoom"`
	MaxZoom         int        `json:"max_zoom"`
	BufferKm        float64    `json:"buffer_km"`
	BBox            [4]float64 `json:"bbox"`
	Status          string     `json:"status"` // pending, downloading, uploading, completed, failed
	Progress        float64    `json:"progress"`
	Phase           string     `json:"phase"` // "tiles", "upload"
	TotalTiles      int64      `json:"total_tiles"`
	DownloadedTiles int64      `json:"downloaded_tiles"`
	FileSize        int64      `json:"file_size_bytes"`
	Error           string     `json:"error,omitempty"`
	CreatedAt       time.Time  `json:"created_at"`
	CompletedAt     *time.Time `json:"completed_at,omitempty"`

	// Zenodo result fields
	ZenodoDepoID int    `json:"zenodo_depo_id,omitempty"`
	ZenodoDOI    string `json:"zenodo_doi,omitempty"`
	DownloadURL  string `json:"download_url,omitempty"` // Zenodo bucket download URL
}

// ZenodoMBTilesQueue manages tile generation + Zenodo upload jobs.
type ZenodoMBTilesQueue struct {
	jobs       map[string]*ZenodoMBTilesJob
	mu         sync.RWMutex
	processing atomic.Bool
	ctx        context.Context
	cancel     context.CancelFunc

	zenodoClient   *zenodo.Client
	zenodoManifest *zenodo.Manifest

	maxCPU int
	db     interface{ Exec(string, ...interface{}) (sql.Result, error) }
}

var zenodoMBQueue *ZenodoMBTilesQueue

// InitZenodoMBTilesQueue initializes the Zenodo-backed MBTiles queue.
func InitZenodoMBTilesQueue(zenodoToken string, db interface{ Exec(string, ...interface{}) (sql.Result, error) }) error {
	if zenodoToken == "" {
		slog.Warn("Zenodo MBTiles queue not initialized: no token provided")
		return fmt.Errorf("zenodo token required")
	}

	ctx, cancel := context.WithCancel(context.Background())

	client := zenodo.New(zenodoToken,
		zenodo.WithMaxRetries(3),
		zenodo.WithRetryWait(5*time.Second),
		zenodo.WithHTTPClient(&http.Client{Timeout: 30 * time.Minute}),
	)

	manifest, err := zenodo.NewManifest("data/mbtiles_zenodo_manifest.json")
	if err != nil {
		cancel()
		return fmt.Errorf("load zenodo manifest: %w", err)
	}

	nCPU := 4 // concurrent tile downloads

	zenodoMBQueue = &ZenodoMBTilesQueue{
		jobs:           make(map[string]*ZenodoMBTilesJob),
		ctx:            ctx,
		cancel:         cancel,
		zenodoClient:   client,
		zenodoManifest: manifest,
		maxCPU:         nCPU,
		db:             db,
	}

	go zenodoMBQueue.processJobs()

	slog.Info("Zenodo MBTiles queue initialized", "manifestEntries", manifest.Len())
	return nil
}

func (q *ZenodoMBTilesQueue) addJob(job *ZenodoMBTilesJob) {
	q.mu.Lock()
	defer q.mu.Unlock()
	job.Status = "pending"
	job.CreatedAt = time.Now()
	q.jobs[job.ID] = job
}

func (q *ZenodoMBTilesQueue) getJob(id string) *ZenodoMBTilesJob {
	q.mu.RLock()
	defer q.mu.RUnlock()
	return q.jobs[id]
}

func (q *ZenodoMBTilesQueue) listJobs() []*ZenodoMBTilesJob {
	q.mu.RLock()
	defer q.mu.RUnlock()
	out := make([]*ZenodoMBTilesJob, 0, len(q.jobs))
	for _, j := range q.jobs {
		out = append(out, j)
	}
	return out
}

func (q *ZenodoMBTilesQueue) processJobs() {
	ticker := time.NewTicker(3 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-q.ctx.Done():
			return
		case <-ticker.C:
			if q.processing.Load() {
				continue
			}
			q.mu.Lock()
			var next *ZenodoMBTilesJob
			for _, j := range q.jobs {
				if j.Status == "pending" {
					next = j
					break
				}
			}
			q.mu.Unlock()

			if next != nil {
				q.processing.Store(true)
				q.executeJob(next)
				q.processing.Store(false)
			}
		}
	}
}

func (q *ZenodoMBTilesQueue) executeJob(job *ZenodoMBTilesJob) {
	defer func() {
		if r := recover(); r != nil {
			q.failJob(job, fmt.Sprintf("panic: %v", r))
		}
	}()

	slog.Info("Starting Zenodo MBTiles job", "id", job.ID, "park", job.ParkID, "source", job.Source)

	q.mu.Lock()
	job.Status = "downloading"
	job.Phase = "tiles"
	q.mu.Unlock()

	// Phase 1: Build MBTiles in memory
	data, err := q.buildMBTilesInMemory(job)
	if err != nil {
		q.failJob(job, fmt.Sprintf("build in-memory: %s", err))
		return
	}

	slog.Info("MBTiles built in memory",
		"id", job.ID,
		"size_mb", len(data)/(1024*1024),
		"tiles", job.DownloadedTiles,
	)

	// Phase 2: Upload to Zenodo
	q.mu.Lock()
	job.Status = "uploading"
	job.Phase = "upload"
	job.FileSize = int64(len(data))
	q.mu.Unlock()

	err = q.uploadToZenodo(job, data)
	// Release the large slice immediately
	data = nil
	if err != nil {
		q.failJob(job, fmt.Sprintf("zenodo upload: %s", err))
		return
	}

	// Success
	q.mu.Lock()
	job.Status = "completed"
	now := time.Now()
	job.CompletedAt = &now
	q.mu.Unlock()

	slog.Info("Zenodo MBTiles job completed",
		"id", job.ID,
		"depoID", job.ZenodoDepoID,
		"size_mb", job.FileSize/(1024*1024),
	)

	// Create notification
	q.createNotification(job)

	// Auto-clean job metadata after 24 hours
	go func(jobID string) {
		time.Sleep(24 * time.Hour)
		q.mu.Lock()
		delete(q.jobs, jobID)
		q.mu.Unlock()
	}(job.ID)
}

// buildMBTilesInMemory downloads tiles and builds a complete MBTiles SQLite
// database in memory, then serializes it to []byte.
func (q *ZenodoMBTilesQueue) buildMBTilesInMemory(job *ZenodoMBTilesJob) ([]byte, error) {
	source, ok := TileSources[job.Source]
	if !ok {
		return nil, fmt.Errorf("unknown tile source: %s", job.Source)
	}

	// Open in-memory SQLite
	db, err := sql.Open("sqlite", ":memory:")
	if err != nil {
		return nil, fmt.Errorf("open memory db: %w", err)
	}
	defer db.Close()

	// Keep a single connection (required for Serialize)
	db.SetMaxOpenConns(1)
	db.SetMaxIdleConns(1)

	// Initialize MBTiles schema
	mbJob := &MBTilesJob{
		ParkName: job.ParkName,
		BBox:     job.BBox,
		MinZoom:  job.MinZoom,
		MaxZoom:  job.MaxZoom,
	}
	if err := initMBTilesSchema(db, mbJob, source); err != nil {
		return nil, fmt.Errorf("init schema: %w", err)
	}

	// Calculate tiles
	tiles := calculateTiles(job.BBox, job.MinZoom, job.MaxZoom)
	job.TotalTiles = int64(len(tiles))

	slog.Info("Downloading tiles to memory", "total", job.TotalTiles, "source", source.Name)

	// Prepare insert
	insertStmt, err := db.Prepare("INSERT OR REPLACE INTO tiles (zoom_level, tile_column, tile_row, tile_data) VALUES (?, ?, ?, ?)")
	if err != nil {
		return nil, fmt.Errorf("prepare insert: %w", err)
	}
	defer insertStmt.Close()

	// Download tiles with concurrency
	semaphore := make(chan struct{}, q.maxCPU)
	var wg sync.WaitGroup
	var downloaded atomic.Int64
	var errors atomic.Int64
	var insertMu sync.Mutex

	for _, tile := range tiles {
		select {
		case <-q.ctx.Done():
			return nil, fmt.Errorf("cancelled")
		default:
		}

		wg.Add(1)
		semaphore <- struct{}{}

		go func(t Tile) {
			defer wg.Done()
			defer func() { <-semaphore }()

			data, err := downloadTile(source, t)
			if err != nil {
				errors.Add(1)
				return
			}

			tmsY := (1 << t.Z) - 1 - t.Y

			insertMu.Lock()
			insertStmt.Exec(t.Z, t.X, tmsY, data)
			insertMu.Unlock()

			count := downloaded.Add(1)
			job.DownloadedTiles = count
			job.Progress = float64(count) / float64(job.TotalTiles) * 90 // 0-90% for tiles
		}(tile)
	}

	wg.Wait()

	if errors.Load() > job.TotalTiles/2 {
		return nil, fmt.Errorf("too many errors: %d/%d failed", errors.Load(), job.TotalTiles)
	}

	// Serialize the in-memory database to []byte
	job.Progress = 92

	conn, err := db.Conn(context.Background())
	if err != nil {
		return nil, fmt.Errorf("get conn: %w", err)
	}
	defer conn.Close()

	var serialized []byte
	err = conn.Raw(func(driverConn interface{}) error {
		type serializer interface {
			Serialize() ([]byte, error)
		}
		s, ok := driverConn.(serializer)
		if !ok {
			return fmt.Errorf("driver conn does not implement Serialize")
		}
		var serErr error
		serialized, serErr = s.Serialize()
		return serErr
	})
	if err != nil {
		return nil, fmt.Errorf("serialize: %w", err)
	}

	return serialized, nil
}

// uploadToZenodo uploads the MBTiles bytes directly to Zenodo without
// writing to disk.
func (q *ZenodoMBTilesQueue) uploadToZenodo(job *ZenodoMBTilesJob, data []byte) error {
	job.Progress = 93

	key := fmt.Sprintf("mbtiles_%s_%s", job.ParkID, job.Source)
	filename := fmt.Sprintf("%s_%s.mbtiles", job.ParkID, job.Source)
	version := time.Now().UTC().Format("2006-01-02T15:04:05")
	checksum := md5hex(data)

	meta := zenodoMBTilesMetadata(job.ParkName, job.Source, job.MinZoom, job.MaxZoom)

	// Check if we already have a deposition for this park+source
	existing := q.zenodoManifest.Get(key)

	var depoID int
	var bucketURL string

	if existing != nil && existing.DepoID > 0 {
		// Update existing deposition
		slog.Info("Updating existing Zenodo deposition", "key", key, "depoID", existing.DepoID)
		depoID = existing.DepoID
		bucketURL = existing.BucketURL

		// Delete old file
		deleteURL := fmt.Sprintf("%s/%s", existing.BucketURL, existing.Filename)
		q.zenodoDoRequest("DELETE", deleteURL, nil, "")
	} else {
		// Create new deposition
		slog.Info("Creating new Zenodo deposition", "key", key)

		respBody, status, err := q.zenodoDoRequest("POST",
			fmt.Sprintf("%s/api/deposit/depositions", q.zenodoClient.BaseURL),
			bytes.NewReader([]byte("{}")), "application/json")
		if err != nil {
			return fmt.Errorf("create deposition: %w", err)
		}
		if status < 200 || status >= 300 {
			return fmt.Errorf("create deposition HTTP %d: %s", status, respBody)
		}

		var depo struct {
			ID    int `json:"id"`
			Links struct {
				Bucket string `json:"bucket"`
			} `json:"links"`
		}
		if err := json.Unmarshal(respBody, &depo); err != nil {
			return fmt.Errorf("parse deposition: %w", err)
		}
		depoID = depo.ID
		bucketURL = depo.Links.Bucket
	}

	// Upload file to bucket
	job.Progress = 95
	slog.Info("Uploading MBTiles to Zenodo", "key", key, "size_mb", len(data)/(1024*1024))

	uploadURL := fmt.Sprintf("%s/%s", bucketURL, filename)
	respBody, status, err := q.zenodoDoRequest("PUT", uploadURL, bytes.NewReader(data), "application/octet-stream")
	if err != nil {
		return fmt.Errorf("upload file: %w", err)
	}
	if status < 200 || status >= 300 {
		return fmt.Errorf("upload file HTTP %d: %s", status, respBody)
	}

	// Set metadata
	job.Progress = 98
	metaPayload := meta(key, filename, version)
	metaJSON, _ := json.Marshal(metaPayload)
	metaURL := fmt.Sprintf("%s/api/deposit/depositions/%d", q.zenodoClient.BaseURL, depoID)
	respBody, status, err = q.zenodoDoRequest("PUT", metaURL, bytes.NewReader(metaJSON), "application/json")
	if err != nil {
		return fmt.Errorf("set metadata: %w", err)
	}
	if status < 200 || status >= 300 {
		return fmt.Errorf("set metadata HTTP %d: %s", status, respBody)
	}

	// Update manifest
	entry := &zenodo.Entry{
		Key:        key,
		DepoID:     depoID,
		BucketURL:  bucketURL,
		Filename:   filename,
		Size:       int64(len(data)),
		Checksum:   checksum,
		UploadedAt: time.Now().UTC(),
		Version:    version,
	}
	q.zenodoManifest.Set(key, entry)
	if err := q.zenodoManifest.Save(); err != nil {
		slog.Warn("Failed to save zenodo manifest", "error", err)
	}

	// Set job result fields
	job.ZenodoDepoID = depoID
	job.DownloadURL = fmt.Sprintf("%s/%s", bucketURL, filename)
	job.Progress = 100

	return nil
}

// zenodoDoRequest is a thin wrapper that reuses the client's token/retries
// but accepts an io.Reader directly (no file required).
func (q *ZenodoMBTilesQueue) zenodoDoRequest(method, url string, body *bytes.Reader, contentType string) ([]byte, int, error) {
	var req *http.Request
	var err error
	if body != nil {
		req, err = http.NewRequest(method, url, body)
	} else {
		req, err = http.NewRequest(method, url, nil)
	}
	if err != nil {
		return nil, 0, err
	}
	req.Header.Set("Authorization", "Bearer "+q.zenodoClient.Token)
	if contentType != "" {
		req.Header.Set("Content-Type", contentType)
	}

	resp, err := q.zenodoClient.HTTPClient.Do(req)
	if err != nil {
		return nil, 0, err
	}
	defer resp.Body.Close()

	var buf bytes.Buffer
	buf.ReadFrom(resp.Body)
	return buf.Bytes(), resp.StatusCode, nil
}

func (q *ZenodoMBTilesQueue) failJob(job *ZenodoMBTilesJob, errMsg string) {
	q.mu.Lock()
	job.Status = "failed"
	job.Error = errMsg
	q.mu.Unlock()
	slog.Error("Zenodo MBTiles job failed", "id", job.ID, "error", errMsg)

	if q.db != nil {
		q.db.Exec(`INSERT INTO notifications (park_id, notification_type, title, message, created_at)
			VALUES (?, 'mbtiles_failed', ?, ?, datetime('now'))`,
			job.ParkID,
			fmt.Sprintf("MBTiles Failed: %s", job.ParkName),
			fmt.Sprintf("Tile generation for %s failed: %s", job.ParkName, errMsg),
		)
	}
}

func (q *ZenodoMBTilesQueue) createNotification(job *ZenodoMBTilesJob) {
	if q.db == nil {
		return
	}
	sizeMB := job.FileSize / (1024 * 1024)

	// Include manifest key so download works even after job expires.
	manifestKey := fmt.Sprintf("mbtiles_%s_%s", job.ParkID, job.Source)
	refURL := fmt.Sprintf("/api/mbtiles/%s/download?key=%s", job.ID, manifestKey)

	q.db.Exec(`INSERT INTO notifications (park_id, notification_type, title, message, reference_url, created_at)
		VALUES (?, 'mbtiles_complete', ?, ?, ?, datetime('now'))`,
		job.ParkID,
		fmt.Sprintf("MBTiles Ready: %s", job.ParkName),
		fmt.Sprintf("Offline tiles for %s (%s, z1–%d, %d MB) stored on Zenodo", job.ParkName, job.Source, job.MaxZoom, sizeMB),
		refURL,
	)
}

func md5hex(data []byte) string {
	h := md5.Sum(data)
	return hex.EncodeToString(h[:])
}

// estimateTileBytes returns estimated MBTiles file size.
// Real-world average: ~10 KB/tile for satellite imagery (measured from actual uploads).
func estimateTileBytes(nTiles int) int64 {
	return int64(nTiles) * 10 * 1024 // 10 KB/tile
}

// estimateRAMRequired estimates peak RAM for in-memory MBTiles build.
// Peak = SQLite DB in memory + Serialize() copy (briefly held simultaneously).
func estimateRAMRequired(bbox [4]float64, minZoom, maxZoom int) int64 {
	tiles := calculateTiles(bbox, minZoom, maxZoom)
	dbSize := estimateTileBytes(len(tiles))
	// Serialize() briefly doubles the memory, plus ~10% SQLite overhead
	return int64(float64(dbSize) * 2.1)
}

// ─── HTTP Handlers ───────────────────────────────────────────────────────────

// HandleAPIZenodoMBTilesCreate starts a new MBTiles-to-Zenodo job.
func (s *Server) HandleAPIZenodoMBTilesCreate(w http.ResponseWriter, r *http.Request) {
	if zenodoMBQueue == nil {
		http.Error(w, "Zenodo MBTiles not configured", http.StatusServiceUnavailable)
		return
	}

	parkID := r.PathValue("id")
	if parkID == "" {
		http.Error(w, "Park ID required", http.StatusBadRequest)
		return
	}

	area := s.AreaStore.GetByID(parkID)
	if area == nil {
		http.Error(w, "Park not found", http.StatusNotFound)
		return
	}

	source := r.URL.Query().Get("source")
	if source == "" {
		source = "esri"
	}
	if _, ok := TileSources[source]; !ok {
		http.Error(w, "Invalid source. Use: esri, bing, google", http.StatusBadRequest)
		return
	}

	maxZoom := 17
	if mzStr := r.URL.Query().Get("maxZoom"); mzStr != "" {
		if mz, err := fmt.Sscanf(mzStr, "%d", &maxZoom); err != nil || mz < 1 {
			maxZoom = 17
		}
		if maxZoom < 1 {
			maxZoom = 1
		}
		if maxZoom > 19 {
			maxZoom = 19
		}
	}

	bufferKm := 5.0
	bbox := calculateBufferedBBox(area, bufferKm)
	tiles := calculateTiles(bbox, 1, maxZoom)
	estimatedSize := estimateTileBytes(len(tiles))
	ramNeeded := estimateRAMRequired(bbox, 1, maxZoom)

	// Check RAM limit (leave 2GB headroom for OS + server)
	const maxRAM = 6 * 1024 * 1024 * 1024 // 6GB peak RAM (leaves ~1GB for OS+server)
	if ramNeeded > maxRAM {
		http.Error(w, fmt.Sprintf(
			"Estimated size too large for in-memory build: ~%.1f GB (max ~%.1f GB). Reduce zoom level.",
			float64(estimatedSize)/(1024*1024*1024),
			float64(maxRAM)/2.1/(1024*1024*1024),
		), http.StatusRequestEntityTooLarge)
		return
	}

	job := &ZenodoMBTilesJob{
		ID:       fmt.Sprintf("%d", time.Now().UnixNano()),
		ParkID:   parkID,
		ParkName: area.Name,
		Source:   source,
		MinZoom:  1,
		MaxZoom:  maxZoom,
		BufferKm: bufferKm,
		BBox:     bbox,
	}

	zenodoMBQueue.addJob(job)

	estSeconds := len(tiles) / 100
	if estSeconds < 60 {
		estSeconds = 60
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]interface{}{
		"job_id":            job.ID,
		"park_id":           parkID,
		"source":            source,
		"total_tiles":       len(tiles),
		"estimated_size_mb": estimatedSize / (1024 * 1024),
		"estimated_seconds": estSeconds,
		"storage":           "zenodo",
		"status_url":        fmt.Sprintf("/api/mbtiles/%s/status?pwd=%s", job.ID, r.URL.Query().Get("pwd")),
	})
}

// HandleAPIZenodoMBTilesEstimate returns size/time estimates for Zenodo upload.
func (s *Server) HandleAPIZenodoMBTilesEstimate(w http.ResponseWriter, r *http.Request) {
	parkID := r.PathValue("id")
	area := s.AreaStore.GetByID(parkID)
	if area == nil {
		http.Error(w, "Park not found", http.StatusNotFound)
		return
	}

	maxZoom := 17
	if mzStr := r.URL.Query().Get("maxZoom"); mzStr != "" {
		fmt.Sscanf(mzStr, "%d", &maxZoom)
		if maxZoom < 1 {
			maxZoom = 1
		}
		if maxZoom > 19 {
			maxZoom = 19
		}
	}

	bbox := calculateBufferedBBox(area, 5.0)
	tiles := calculateTiles(bbox, 1, maxZoom)
	estimatedSize := estimateTileBytes(len(tiles))
	ramNeeded := estimateRAMRequired(bbox, 1, maxZoom)
	estSeconds := len(tiles) / 100

	const maxRAM = 6 * 1024 * 1024 * 1024
	sufficient := ramNeeded <= maxRAM

	// Check if already uploaded to Zenodo
	key := fmt.Sprintf("mbtiles_%s_%s", parkID, r.URL.Query().Get("source"))
	if key == fmt.Sprintf("mbtiles_%s_", parkID) {
		key = fmt.Sprintf("mbtiles_%s_esri", parkID)
	}
	var existingDepoID int
	if zenodoMBQueue != nil {
		if entry := zenodoMBQueue.zenodoManifest.Get(key); entry != nil {
			existingDepoID = entry.DepoID
		}
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]interface{}{
		"park_id":           parkID,
		"total_tiles":       len(tiles),
		"estimated_size_mb": estimatedSize / (1024 * 1024),
		"estimated_seconds": estSeconds,
		"bbox":              bbox,
		"min_zoom":          1,
		"max_zoom":          maxZoom,
		"sufficient_space":  sufficient,
		"storage":           "zenodo",
		"ram_needed_mb":     ramNeeded / (1024 * 1024),
		"existing_depo_id":  existingDepoID,
		"sources":           []string{"esri", "bing", "google"},
	})
}

// HandleAPIZenodoMBTilesStatus returns job status (reuses the same endpoint path).
func (s *Server) HandleAPIZenodoMBTilesStatus(w http.ResponseWriter, r *http.Request) {
	jobID := r.PathValue("id")

	// Check Zenodo queue first
	if zenodoMBQueue != nil {
		if job := zenodoMBQueue.getJob(jobID); job != nil {
			w.Header().Set("Content-Type", "application/json")
			json.NewEncoder(w).Encode(job)
			return
		}
	}

	// Fall back to legacy disk-based queue
	if mbtilesQueue != nil {
		if job := mbtilesQueue.GetJob(jobID); job != nil {
			w.Header().Set("Content-Type", "application/json")
			json.NewEncoder(w).Encode(job)
			return
		}
	}

	http.Error(w, "Job not found", http.StatusNotFound)
}

// HandleAPIZenodoMBTilesDownload proxies the download from Zenodo (or redirects).
func (s *Server) HandleAPIZenodoMBTilesDownload(w http.ResponseWriter, r *http.Request) {
	jobID := r.PathValue("id")

	// Check active Zenodo job first
	if zenodoMBQueue != nil {
		if job := zenodoMBQueue.getJob(jobID); job != nil {
			if job.Status != "completed" {
				http.Error(w, fmt.Sprintf("Job not ready: %s", job.Status), http.StatusBadRequest)
				return
			}
			if job.DownloadURL != "" {
				proxyZenodoDownload(w, job.DownloadURL, fmt.Sprintf("%s_%s.mbtiles", job.ParkID, job.Source))
				return
			}
			http.Error(w, "No download URL available", http.StatusNotFound)
			return
		}

		// Job expired but may still be in manifest — look up by key param
		if key := r.URL.Query().Get("key"); key != "" {
			if entry := zenodoMBQueue.zenodoManifest.Get(key); entry != nil {
				downloadURL := fmt.Sprintf("%s/%s", entry.BucketURL, entry.Filename)
				proxyZenodoDownload(w, downloadURL, entry.Filename)
				return
			}
		}
	}

	// Fall back to legacy disk-based download
	s.HandleAPIMBTilesDownload(w, r)
}

// proxyZenodoDownload streams a file from Zenodo to the client.
func proxyZenodoDownload(w http.ResponseWriter, downloadURL, filename string) {
	q := zenodoMBQueue
	req, err := http.NewRequest("GET", downloadURL, nil)
	if err != nil {
		http.Error(w, "Failed to create request", http.StatusInternalServerError)
		return
	}
	req.Header.Set("Authorization", "Bearer "+q.zenodoClient.Token)

	resp, err := q.zenodoClient.HTTPClient.Do(req)
	if err != nil {
		http.Error(w, "Failed to fetch from Zenodo", http.StatusBadGateway)
		return
	}
	defer resp.Body.Close()

	w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=%s", filename))
	w.Header().Set("Content-Type", "application/x-sqlite3")
	if resp.ContentLength > 0 {
		w.Header().Set("Content-Length", fmt.Sprintf("%d", resp.ContentLength))
	}
	w.WriteHeader(resp.StatusCode)
	buf := make([]byte, 256*1024)
	for {
		n, readErr := resp.Body.Read(buf)
		if n > 0 {
			w.Write(buf[:n])
		}
		if readErr != nil {
			break
		}
	}
}

// HandleAPIZenodoMBTilesList lists jobs from both queues.
func (s *Server) HandleAPIZenodoMBTilesList(w http.ResponseWriter, r *http.Request) {
	var allJobs []interface{}

	if zenodoMBQueue != nil {
		for _, j := range zenodoMBQueue.listJobs() {
			allJobs = append(allJobs, j)
		}
	}

	// Include legacy jobs too
	if mbtilesQueue != nil {
		for _, j := range mbtilesQueue.ListJobs() {
			allJobs = append(allJobs, j)
		}
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(allJobs)
}

// Helper to check calculateBufferedBBox signature - it uses *areas.ProtectedArea
var _ = func() { var a *areas.ProtectedArea; calculateBufferedBBox(a, 0) }
