#!/usr/bin/env python3
"""Generate the Go affinity-evidence table from the eval JSON.

Run after scripts/geomaps/eval_affinity.py. The generated Go is committed so
the server builds without Python or the (large / licence-sensitive) occurrence
files; the eval JSON remains local and the Go test pins every shipped row to it
when present.

A row is ONE MEASUREMENT, not a consensus. When two truth sets score the same
claim they both ship: agreement is evidence; disagreement is a mixed verdict,
not a number to average away.

A STRATUM IS MARKED AS ONE. The CAR gold lift depends on whether IPIS's
surveyors recorded an armed actor at the pit (2.04x vs 1.31x at w>=1, capture
p=0.0033), so the two halves ship - a pooled number with a known confound must
not be the only thing a surface can quote. But they are halves of ONE survey:
they cannot corroborate each other, and a consumer that counts them as two
independent agreements has let one list vote three times. `Stratum` carries that
so the distinction survives the file boundary.
"""
import json
import math
import sys

SRC = "data/eval/geo_affinity.json"
OUT = "srv/geomap_scores_table.go"


def verdict(lift):
    return "concentrates" if lift > 1.0 else "no better than area"


def gostr(s):
    return json.dumps(s, ensure_ascii=False)


def main():
    d = json.load(open(SRC))
    rows, truths, too_few = [], {}, {}
    strata_meta = d.get("strata", {})
    for sheet, by_truth in sorted(d["sheets"].items()):
        for tid, rec in sorted(by_truth.items()):
            eid = f"{sheet}/{tid}"
            truths[eid] = rec
            for kind, block, cap, base in (
                    ("unit", "units", "capture", "area_share"),
                    ("junction", "junctions", "site_near", "random_near")):
                for com, per_floor in sorted(rec[block].items()):
                    if "verdict" in per_floor:
                        too_few.setdefault(eid, {})[com] = per_floor["n"]
                        continue
                    for floor, m in sorted(per_floor.items(), key=lambda x: int(x[0])):
                        lift = m.get("lift")
                        if lift is None or not math.isfinite(lift):
                            continue
                        ctrl = m.get("control_ratio") if kind == "junction" else 0
                        if ctrl is None or not math.isfinite(ctrl):
                            ctrl = 0
                        rows.append({
                            "sheet": sheet, "evidence": eid, "truth_id": tid,
                            "commodity": com, "kind": kind, "floor": int(floor),
                            "capture": m[cap], "baseline": m[base], "lift": lift,
                            "control": ctrl, "n": m.get("n_sites", 0),
                            "scope": rec["truth"], "caveat": rec["caveat"],
                            "verdict": verdict(lift),
                            "stratum_of": rec.get("stratum_of") or "",
                            "stratum": rec.get("stratum") or "",
                        })

    L = []
    w = L.append
    w("// Code generated by scripts/geomaps/gen_scores_go.py. DO NOT EDIT.")
    w("// Each row is one truth set's measurement; disagreeing rows stay separate.")
    w("")
    w("package srv")
    w("")
    w(f"const geoAffinityNearKm = {d['near_km']:g}")
    w(f"const geoAffinityMinSites = {d['min_sites']}")
    w("")
    w("var geoAffinityTruth = map[string]geoTruthSet{")
    for eid, rec in sorted(truths.items()):
        w(f"\t{gostr(eid)}: {{Place: {gostr(rec['truth'])}, "
          f"Caveat: {gostr(rec['caveat'])}, "
          f"StratumOf: {gostr(rec.get('stratum_of') or '')}, "
          f"Stratum: {gostr(rec.get('stratum') or '')}, "
          f"Baseline: {gostr(rec.get('baseline_region') or '')}}},")
    w("}")
    w("")
    # THE SPREAD BETWEEN STRATA, WITH ITS p. A surface that quotes the pooled
    # CAR gold lift has to be able to say "and this number moves with who could
    # reach the ground" without re-reading a JSON file it does not ship.
    w("// geoAffinityStrataSpread: how far apart one survey's strata scored the")
    w("// same claim, keyed commodity|kind|wFLOOR. >1 means the pooled lift for")
    w("// that claim depends on the stratifier, not only on the rock.")
    w("var geoAffinityStrataSpread = map[string]map[string]float64{")
    for sheet, per in sorted(strata_meta.items()):
        inner = []
        for key, v in sorted(per.items()):
            if key.startswith("_") or not isinstance(v, dict):
                continue
            sp = v.get("spread")
            if sp is None or not math.isfinite(sp):
                continue
            inner.append(f"{gostr(key)}: {sp:.4f}")
        if inner:
            w(f"\t{gostr(sheet)}: {{{', '.join(inner)}}},")
    w("}")
    w("")
    w("var geoAffinityTooFew = map[string]map[string]int{")
    for eid, per in sorted(too_few.items()):
        inner = ", ".join(f"{gostr(c)}: {n}" for c, n in sorted(per.items()))
        w(f"\t{gostr(eid)}: {{{inner}}},")
    w("}")
    w("")
    w(f"// geoAffinityScores contains {len(rows)} measurements from {len(truths)} truth sets.")
    w("var geoAffinityScores = []geoAffinityScore{")
    for r in rows:
        w("\t{Commodity: %s, Kind: %s, MinWeight: %d, Capture: %.6f, "
          "Baseline: %.6f, Lift: %.6f, Control: %.6f, N: %d, Scope: %s, "
          "Caveat: %s, Verdict: %s, ScopeSheet: %s, EvidenceID: %s, "
          "StratumOf: %s, Stratum: %s}," % (
              gostr(r["commodity"]), gostr(r["kind"]), r["floor"],
              r["capture"], r["baseline"], r["lift"], r["control"], r["n"],
              gostr(r["scope"]), gostr(r["caveat"]), gostr(r["verdict"]),
              gostr(r["sheet"]), gostr(r["evidence"]),
              gostr(r["stratum_of"]), gostr(r["stratum"])))
    w("}")
    w("")
    open(OUT, "w").write("\n".join(L))
    print(f"wrote {OUT}: {len(rows)} measurements from {len(truths)} truth sets")


if __name__ == "__main__":
    sys.exit(main())
